assuntos_cjf = {'DIREITO PENAL': '287',
                'Crimes contra a Fé Pública': '3523',
                'Adulteração de Sinal Identificador de Veículo Automotor por Funcionário Público': '10992',
                'Crime de Desvio e/ou Circulação de Moeda Não Autorizada': '11006',
                'Crime de Moeda Falsa Praticado por Funcionário Público': '11007',
                'Falsidade ideológica praticada por Funcionário Público': '10995',
                'Falsificação de documento Público praticada por Funcionário Público': '10998',
                'Falsificação de Papéis Públicos Praticado por Funcionário Público': '11005',
                'Falsificação do Selo ou Sinal Público Praticado por Funcionário Público': '11004',
                'Petrechos de Falsificação de Papéis Públicos por Funcionário Público': '10993',
                'Petrechos para falsificação de moeda por Funcionário Público': '10994',
                'Crimes Contra as Finanças Públicas': '5875',
                'Corrupção Praticada por Prefeitos e Vereadores': '10991',
                'Má-gestão praticada por Prefeitos e Vereadores': '10990',
                'Crimes Praticados por Funcionários Públicos Contra a Administração em Geral': '3547',
                '"Lavagem" ou Ocultação de Bens, Direitos ou Valores Oriundos de Corrupção': '10982',
                'Crimes Praticados por Particular Contra a Administração em Geral': '5872',
                'Crimes Praticados por Particular Contra a Administração Pública Estrangeira': '5873',
                'Crimes Previstos na Legislação Extravagante': '3603',
                'Crimes contra a Ordem Tributária praticado por Funcionário Público': '10985',
                'Crimes contra o Meio Ambiente e o Patrimônio Genético': '3618',
                'Crime contra a administração ambiental': '10986',
                'Crimes de Tráfico Ilícito e Uso Indevido de Drogas': '3607',
                'Tráfico Ilícito de Drogas praticado por Funcionário Público': '10987'}
