assuntos_cnj = {'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO': '9985',
                'Agentes Políticos': '10186',
                'Magistratura': '10187',
                'Aposentadoria': '10254',
                'Apuração de Infração Disciplinar': '11952',
                'Eleição': '11920',
                'Cargos de Direção': '11921',
                'Órgão Especial': '11922',
                'Juizados Especiais': '11911',
                'Composição de Turmas Recursais': '11913',
                'Juiz Leigo': '11912',
                'Licença': '11914',
                'Morosidade no Julgamento do Processo': '11950',
                'Participação Societária': '11915',
                'Plantão Judiciário': '11916',
                'Processo Disciplinar / Sindicância': '10190',
                'Promoção': '10192',
                'Remoção': '10229',
                'Remuneração': '10188',
                'Residência': '11917',
                'Substituição/Convocação em Tribunal': '11918',
                'Violação Prerrogativa Advogado': '11919',
                'Atos Administrativos': '9997',
                'Ato Normativo': '11899',
                'Recomendação': '11901',
                'Resolução': '11900',
                'Resolução Conjunta': '11902',
                'Fiscalização': '10015',
                'Inspeção': '11948',
                'Investigação Patrimonial': '11951',
                'Revisão/Desconstituição de Ato Administrativo': '11949',
                'Concurso Público / Edital': '10370',
                'Anulação e Correção de Provas / Questões': '10379',
                'Concurso para magistrado': '11903',
                'Concurso para serventia extrajudicial': '11910',
                'Concurso para servidor': '11909',
                'Condições Especiais para Prestação de Prova': '10384',
                'Curso de Formação': '10377',
                'Escolaridade': '10380',
                'Exame de Saúde e/ou Aptidão Física': '10376',
                'Exame Psicotécnico / Psiquiátrico': '10378',
                'Exigência de Prática Forense': '10374',
                'Inscrição / Documentação': '10372',
                'Limite de Idade': '10373',
                'Prazo de Validade': '10383',
                'Prova de Títulos': '10375',
                'Prova Objetiva': '11904',
                'Prova Oral': '11907',
                'Prova Prática-Sentença': '11906',
                'Prova Subjetiva': '11905',
                'Reserva de Vagas': '11908',
                'Reserva de Vagas para Deficientes': '10371',
                'Licitações': '10385',
                'Edital': '10388',
                'Orçamento': '10954',
                'Crédito Especial': '11897',
                'Crédito Extraordinário': '11898',
                'Crédito Suplementar': '10958',
                'Organização Político-administrativa / Administração Pública': '10157',
                'Criação / Extinção / Reestruturação de Orgãos ou Cargos Públicos': '10868',
                'Serviços': '10028',
                'Concessão / Permissão / Autorização': '10073',
                'Tabelionatos, Registros, Cartórios': '10083',
                'Cumulação': '11928',
                'Desmembramento': '11927',
                'Emolumentos': '11929',
                'Fraude': '11930',
                'Gratuidade': '11931',
                'Princípio da Territorialidade': '11932',
                'Provimento Irregular': '11933',
                'Registro Civil de Nascimento': '11934',
                'Registro de Imóveis': '11935',
                'Vacância': '11925',
                'Servidor Público Civil': '10219',
                'Jornada de Trabalho': '10287',
                'Licenças / Afastamentos': '10258',
                'Processo Administrativo Disciplinar ou Sindicância': '10279',
                'Regime Estatutário': '10220',
                'Cessão': '11936',
                'Desvio de Função': '11937',
                'Direito de Greve': '10227',
                'Nepotismo': '10881',
                'Provimento de Cargos': '11938',
                'Redistribuição': '10233',
                'Sistema Remuneratório e Benefícios': '10288',
                'Adicional de Horas Extras': '10303',
                'Teto Salarial': '10297',
                'DIREITO CIVIL': '899',
                'Família': '5626',
                'Violência Doméstica Contra a Mulher': '10948',
                'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                'Liquidação / Cumprimento / Execução': '9148',
                'Precatório': '10672',
                'Fraude / Quebra de ordem cronológica': '11923',
                'Pagamento': '11924',
                'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                'Do Juiz': '8884',
                'Impedimento': '10660',
                'Suspeição': '10659'}
