,just_eleit_zon_eleit = {'DIREITO ELEITORAL': '11428'
 'Administração da Justiça Eleitoral': '11557',
 'Conduta Vedada a Agente Público': '11558',
 'Descumprimento de Prazos Eleitorais': '11560',
 'Alistamento Eleitoral': '11574',
 'Alistamento Eleitoral - Cancelamento': '11575',
 'Alistamento Eleitoral - Domicílio Eleitoral': '11576',
 'Alistamento Eleitoral - Duplicidade/Pluralidade': '11577',
 'Alistamento Eleitoral - Exclusão': '11578',
 'Alistamento Eleitoral - Inscrição Eleitoral': '11579',
 'Impugnação - Alistamento Eleitoral': '11580',
 'Impugnação - Inscrição Eleitoral': '12051',
 'Impugnação - Transferência de Domicílio Eleitoral': '12055',
 'Crimes Eleitorais': '11429',
 'Crimes contra a Fé Pública Eleitoral': '11467',
 'Alteração do Resultado de Votação nos Mapas ou Boletins de Apuração': '11470',
 'Destruição de Dados Eleitorais': '11479',
 'Falsidade Ideológica': '11473',
 'Falsificação ou Alteração de Documento Público para Fins Eleitorais': '11472',
 'Obtenção de Acesso a Sistema de Dados Eleitorais': '11478',
 'Obtenção de Documento Falso para Fins Eleitorais': '11476',
 'Omissão da Entrega do Boletim de Urna': '11477',
 'Omissão na Expedição de Boletim de Apuração': '11468',
 'Omissão no Recebimento e Registro de Protestos, bem como, de sua Remessa à Instância Superior': '11471',
 'Omissão no Recolhimento das Cédulas Apuradas, no Fechamento e Lacração da Urna': '11469',
 'Reconhecimento Indevido de Firma ou Letras para Fins Eleitorais': '11474',
 'Recusa de Entrega de Boletim': '11481',
 'Uso de Documento Falso para Fins Eleitorais': '11475',
 'Crimes contra a Organização Administrativa da Justiça Eleitoral': '11430',
 'Contagem de Votos de Eleitores em Relação aos quais Houve Impugnação': '11435',
 'Fabricação, Aquisição, Fornecimento, Subtração ou Guarda de Materiais de Uso da Justiça Eleitoral': '11436',
 'Intervenção Indevida de Autoridade Junto à Mesa Receptora': '11431',
 'Não Observância de Chamamento de Eleitores para Votar': '11432',
 'Práticas Irregulares que Determinam a Anulação da Votação': '11433',
 'Votação de Eleitor na Seção Eleitoral na qual Não Está Inscrito ou Autorizado a Votar': '11434',
 'Crimes contra a Propaganda Eleitoral': '11482',
 'Autorização de Transmissão de Pessoa Não Detentora de Direitos Políticos em Atividades Partidárias e de Propaganda Eleitoral': '11494',
 'Calúnia na Propaganda Eleitoral': '11484',
 'Difamação na Propaganda Eleitoral': '11486',
 'Divulgação de Falsa Imputação': '11485',
 'Divulgação de Fatos Inverídicos na Propaganda Eleitoral': '11483',
 'Impedimento do Exercício da Propaganda': '11490',
 'Injúria Eleitoral Violenta': '11488',
 'Injúria na Propaganda Eleitoral': '11487',
 'Inutilização, Alteração ou Perturbação de Propaganda': '11489',
 'Participação de Pessoa Não Detentora de Direitos Políticos em Atividades Partidárias e de Propaganda Eleitoral': '11493',
 'Pesquisa Fraudulenta': '11495',
 'Realização de Propaganda Eleitoral em Língua Estrangeira': '11492',
 'Uso, na Propaganda Eleitoral, de Símbolo de Órgãos de Governo': '11496',
 'Utilização de Organização Comercial para Propaganda ou Aliciamento de Eleitores': '11491',
 'Crimes contra o Serviço da Justiça Eleitoral': '11437',
 'Dano a Equipamento Eleitoral': '11466',
 'Desatendimento à Requisição de Veículo ou Embarcação': '11454',
 'Descumprimento da Proibição de Fornecimento de Transporte ou Refeições a Eleitores': '11455',
 'Descumprimento do Dever de Informar o Número, Espécie e Lotação de Veículos e Embarcações': '11453',
 'Desobediência a Ordens ou Instruções da Justiça Eleitoral': '11452',
 'Induzimento à Inscrição de Eleitor em Infração às Normas Legais': '11439',
 'Inscrição Fraudulenta': '11438',
 'Inscrição Fraudulenta Efetivada pelo Juiz': '11440',
 'Majoração de Preços de Utilidade e Serviços Necessários à Realização das Eleições': '11444',
 'Não Cumprimento dos Deveres Impostos pelo Código Eleitoral à Autoridade Judiciária e aos Funcionários da Justiça Eleitoral': '11450',
 'Não Cumprimento, pela Autoridade Judiciária, do Dever de Representar Contra o Órgão do Ministério que Não Oferece Denúncia no Prazo Legal': '11448',
 'Não-Apresentação de Denúncia ou Não Execução de Sentença Penal Condenatória no Prazo Legal': '11447',
 'Negativa ou Retardamento de Inscrição sem Fundamento Legal': '11441',
 'Obstamento do Transporte e Fornecimento de Alimentos a Eleitores pela Justiça Eleitoral': '11464',
 'Ocultação, Sonegação ou Recusa de Fornecimento de Utilidades, Alimentos e Transporte no Dia da Eleição': '11445',
 'Perturbação ou Impedimento de Alistamento': '11442',
 'Promoção de Desordem nos Trabalhos Eleitorais': '11443',
 'Recusa ou Abandono do Serviço Eleitoral': '11449',
 'Retardamento ou Não-Publicação de Decisões, Citações ou Intimações da Justiça Eleitoral': '11446',
 'Utilização de Prédios ou Serviços de Repartições Públicas para Beneficiar Partido ou Organização de Caráter Político': '11451',
 'Utilização de Veículos e Embarcações Públicas em Campanha Eleitoral': '11465',
 'Crimes contra o Sigilo ou o Exercício do Voto': '11497',
 'Arregimentação de Eleitor ou Boca de Urna': '11513',
 'Coação Visando a Obtenção de Voto ou a sua Abstenção': '11502',
 'Concentração de Eleitores para Embaraçar ou Fraudar o Exercício do Voto': '11504',
 'Corrupção Eleitoral': '11501',
 'Destruição de Relação de Candidatos': '11511',
 'Destruição, Supressão ou Ocultação de Urna Contendo Votos ou Documentos Eleitorais': '11510',
 'Divulgação de Propaganda Eleitoral no Dia da Eleição': '11514',
 'Fornecimento ao Eleitor de Cédula Oficial Já Assinalada ou Marcada': '11505',
 'Fornecimento de Cédula Eleitoral Rubricada a Destempo': '11506',
 'Impedimento ou Embaraço ao Exercício do Sufrágio': '11499',
 'Prisão ou Detenção do Eleitor, Membro de Mesa Receptora, Fiscal, Delegado de Partido ou Candidato, Fora das Hipóteses Legais Permitidas': '11500',
 'Retenção de Título Eleitoral ou do Comprovante de Alistamento Eleitoral': '11498',
 'Retenção de Título ou Comprovante de Alistamento Eleitoral': '11515',
 'Uso Proibido de Alto-Falantes': '11512',
 'Violação do Sigilo da Urna ou dos Invólucros': '11509',
 'Violação do Sigilo do Voto': '11508',
 'Violência ou Grave Ameaça Visando a Obtenção de Voto ou a sua Abstenção': '11503',
 'Votação Múltipla ou Realizada em Lugar de Outrem': '11507',
 'Crimes contra os Partidos Políticos': '11517',
 'Arguição de Ineligibilidade Temerária ou de Má-Fé': '11522',
 'Coleta de Assinatura em Mais de Uma Ficha de Registro Partidário': '11520',
 'Inscrição Simultânea em Dois ou Mais Partidos': '11519',
 'Irregularidades dos Dados Publicados em Pesquisas Eleitorais': '11524',
 'Não-Acesso dos Partidos aos Dados Relativos às Pesquisas Eleitorais': '11523',
 'Preterição à Prioridade Postal': '11521',
 'Subscrição de Mais de Uma Ficha de Filiação Partidária': '11518',
 'Diplomação': '11724',
 'Direitos Políticos': '11725',
 'Direitos Políticos - Perda dos Direitos Políticos': '11726',
 'Direitos Políticos - Restabelecimento dos Direitos Políticos': '11727',
 'Direitos Políticos - Suspensão de Direitos Políticos': '11728',
 'Eleições': '11583',
 'Candidatos': '11584',
 'Condição de Elegibilidade': '11585',
 'Condição de Elegibilidade - Alistamento Eleitoral': '11586',
 'Condição de Elegibilidade - Domicílio Eleitoral na Circunscrição': '11587',
 'Condição de Elegibilidade - Filiação Partidária': '11589',
 'Condição de Elegibilidade - Idade Mínima': '11588',
 'Condição de Elegibilidade - Nacionalidade Brasileira': '11590',
 'Condição de Elegibilidade - Pleno Exercício dos Direitos Políticos': '11591',
 'Condição de Elegibilidade - Quitação Eleitoral': '11592',
 'Direito de Resposta': '11593',
 'Identificação Numérica de Candidato': '11594',
 'Inelegibilidade': '11595',
 'Inelegibilidade - Abuso do Poder Econômico ou Político': '11596',
 'Inelegibilidade - Analfabetismo': '11597',
 'Inelegibilidade - Condenação Criminal Transitada em Julgado': '11598',
 'Inelegibilidade - Declaração de Indignidade ou de Incompatibilidade com o Oficialato': '11599',
 'Inelegibilidade - Desincompatibilização': '11600',
 'Inelegibilidade - Inalistável': '11601',
 'Inelegibilidade - Parentesco': '11602',
 'Inelegibilidade - Reeleição': '11603',
 'Inelegibilidade - Rejeição de Contas Públicas': '11604',
 'Inelegibilidade - Representação ou Ação de Investigação Judicial Eleitoral Jugada Procedente pela Justiça Eleitoral': '11605',
 'Inelegibilidade - Terceiro Mandato': '11606',
 'Inelegibilidade - Vida Pregressa': '11607',
 'Inelegibilidade - Vínculo Afetivo': '11608',
 'Inelegibilidade - Vínculo Conjugal': '11609',
 'Inelegibilidade - Vínculo em União Estável': '11610',
 'Nome do Candidato': '11611',
 'Nome do Candidato - Homonímia': '11612',
 'Nome do Candidato - Variação Nominal': '11613',
 'Prestação de Contas - De Candidato': '12046',
 'Registro de Candidatura': '11615',
 'Impugnação ao Registro de Candidatura': '11616',
 'Registro de Candidatura - DRAP Partido/Coligação': '12044',
 'Registro de Candidatura - Preenchimento de Vaga Remanescente': '11617',
 'Registro de Candidatura - RRC - Candidato': '11618',
 'Registro de Candidatura - RRCI - Candidato Individual': '11619',
 'Registro de Candidatura - Substituição de Candidato': '11620',
 'Registro de Candidatura - Substituição de Candidato - Por Cancelamento de Registro': '11621',
 'Registro de Candidatura - Substituição de Candidato - Por Cassação de Registro': '11622',
 'Registro de Candidatura - Substituição de Candidato - Por Expulsão Partidária': '11623',
 'Registro de Candidatura - Substituição de Candidato - Por Falecimento': '11624',
 'Registro de Candidatura - Substituição de Candidato - Por Indeferimento de Registro': '11625',
 'Registro de Candidatura - Substituição de Candidato - Por Ineligibilidade': '11626',
 'Registro de Candidatura - Substituição de Candidato - Por Renúncia': '11627',
 'Cargos': '11628',
 'Cargo - Prefeito': '11633',
 'Cargo - Vereador': '11638',
 'Cargo - Vice-Prefeito': '11640',
 'Eleições - 1° Turno': '11642',
 'Eleições - 2° Turno': '11643',
 'Eleições - Anulação de Eleições': '11644',
 'Eleições - Eleição Majoritária': '11645',
 'Eleições - Eleição Proporcional': '11646',
 'Eleições - Eleição Suplementar': '11647',
 'Garantias Eleitorais': '11702',
 'Habeas Corpus': '11703',
 'Habeas Corpus - Liberatório': '11704',
 'Habeas Corpus - Preventivo': '11705',
 'Impugnação': '12049',
 'Impugnação - Identidade de Eleitor Admitido a Votar': '12050',
 'Impugnação - Nomeação de Membro da Junta Eleitoral': '12052',
 'Impugnação - Nomeação de Membro da Mesa Receptora': '12053',
 'Impugnação - Sistema Eletrônico de Votação': '12054',
 'Impugnação - Voto por Cédula': '12056',
 'Pesquisa Eleitoral': '11648',
 'Pesquisa Eleitoral - Divulgação de Pesquisa Eleitoral Fraudulenta': '11649',
 'Pesquisa Eleitoral - Divulgação de Pesquisa Eleitoral Sem Prévio Registro': '11650',
 'Pesquisa Eleitoral - Registro de Pesquisa Eleitoral': '11651',
 'Prestação de Contas': '12045',
 'Prestação de Contas - De Comitê Financeiro': '11687',
 'Propaganda Política - Propaganda Eleitoral': '11652',
 'Propaganda Política - Propaganda Eleitoral - Adesivo': '11653',
 'Propaganda Política - Propaganda Eleitoral - Alto-falante/Amplificador de Som': '11654',
 'Propaganda Política - Propaganda Eleitoral - Banner/Cartaz/Faixa': '11655',
 'Propaganda Política - Propaganda Eleitoral - Bem Particular': '11656',
 'Propaganda Política - Propaganda Eleitoral - Bem Particular de Uso Comum': '11657',
 'Propaganda Política - Propaganda Eleitoral - Bem Público': '11658',
 'Propaganda Política - Propaganda Eleitoral - Bem Tombado': '11659',
 'Propaganda Política - Propaganda Eleitoral - Boca de Urna': '11660',
 'Propaganda Política - Propaganda Eleitoral - Cavalete': '11661',
 'Propaganda Política - Propaganda Eleitoral - Comício/Showmício': '11662',
 'Propaganda Política - Propaganda Eleitoral - Conduta Vedada a Emissora de Rádio/Televisão na Programação Normal': '11663',
 'Propaganda Política - Propaganda Eleitoral - Confecção, Utilização ou Distribuição de Brinde': '11664',
 'Propaganda Política - Propaganda Eleitoral - Contrariedade à Lei de Postura Municipal': '11665',
 'Propaganda Política - Propaganda Eleitoral - Debate Político': '11666',
 'Propaganda Política - Propaganda Eleitoral - Extemporânea/Antecipada': '11667',
 'Propaganda Política - Propaganda Eleitoral - Folhetos/Volantes/Santinhos/Impressos': '11668',
 'Propaganda Política - Propaganda Eleitoral - Horário Eleitoral Gratuito': '11669',
 'Propaganda Política - Propaganda Eleitoral - Distribuição de Tempo de Propaganda': '11670',
 'Propaganda Política - Propaganda Eleitoral - Horário Eleitoral Gratuito/Inserções de Propaganda': '11671',
 'Propaganda Política - Propaganda Eleitoral - Horário Eleitoral Gratuito/Programa em Bloco': '11672',
 'Propaganda Política - Propaganda Eleitoral - Invasão de Horário Destinado a Outro Cargo/Partido/Coligação': '11676',
 'Propaganda Política - Propaganda Eleitoral - Rádio': '11673',
 'Propaganda Política - Propaganda Eleitoral - Rádio Comunitária': '11674',
 'Propaganda Política - Propaganda Eleitoral - Televisão': '11675',
 'Propaganda Política - Propaganda Eleitoral - Imprensa Escrita - Jornal/Revista/Tabloide': '11677',
 'Propaganda Política - Propaganda Eleitoral - Inobservância do Limite Legal': '11678',
 'Propaganda Política - Propaganda Eleitoral - Internet': '11679',
 'Propaganda Política - Propaganda Eleitoral - Omissão de Informações Obrigatórias': '11680',
 'Propaganda Política - Propaganda Eleitoral - Outdoors': '11681',
 'Propaganda Política - Propaganda Eleitoral - Pintura em Muro': '11682',
 'Propaganda Política - Propaganda Eleitoral - Truncagem, Montagem, Utilização de Gravação Externa, Computação Gráfica, Desenho Animado ou Efeito Especial': '11683',
 'Recursos Financeiros de Campanha Eleitoral': '11684',
 'Captação ou Gasto Ilícito de Recursos Financeiros de Campanha Eleitoral': '11685',
 'Comitê Financeiro': '11686',
 'Doação de Recursos Acima do Limite Legal': '11699',
 'Doação de Recursos Acima do Limite Legal - Pessoa Física': '11700',
 'Doação de Recursos Acima do Limite Legal - Pessoa Jurídica': '11701',
 'Registro de Candidatura - DRAP - Partido/Coligação': '11712',
 'Resultados': '11713',
 'Apuração/Totalização de Votos': '11714',
 'Quociente Eleitoral/Partidário': '11715',
 'Transgressões Eleitorais': '11716',
 'Abuso': '11717',
 'Abuso - De Poder Econômico': '11718',
 'Abuso - De Poder Político/Autoridade': '11719',
 'Abuso - Uso Indevido de Meio de Comunicação Social': '11720',
 'Captação Ilícita de Sufrágio': '11721',
 'Corrupção ou Fraude': '11722',
 'Propaganda Política - Propaganda Institucional': '11723',
 'Execução': '11729',
 'Execução - De Astreintes': '11730',
 'Execução - De Multa Eleitoral': '11731',
 'Execução de Julgado': '11732',
 'Garantias Processuais': '11733',
 'Cautelar Inominada': '11734',
 'Cautelar Inominada - De Busca e Apreensão': '11735',
 'Cautelar Inominada - De Produção Antecipada de Provas': '11736',
 'Cautelar Inominada - Incidental': '11737',
 'Cautelar Inominada - Preparatória': '11738',
 'Exceção': '11739',
 'Exceção - De Coisa Julgada': '11740',
 'Exceção - De Ilegitimidade de Parte': '11741',
 'Exceção - De Impedimento': '11742',
 'Exceção - De Incompetência': '11743',
 'Exceção - De Litispendência': '11744',
 'Exceção - De Pré-Executividade': '11745',
 'Exceção - De Suspeição': '11746',
 'Meios Processuais': '12064',
 'Partidos Políticos': '11747',
 'Coligação Partidária': '11749',
 'Coligação Partidária - Majoritária': '11750',
 'Coligação Partidária - Majoritária e Proporcional': '11751',
 'Coligação Partidária - Proporcional': '11752',
 'Convenção Partidária': '11753',
 'Filiação/Desfiliação': '11754',
 'Filiação Partidária': '11755',
 'Filiação Partidária - Cancelamento': '11756',
 'Filiação Partidária - Duplicidade/Pluralidade': '11757',
 'Filiação Partidária - Nulidade': '11758',
 'Órgão de Direção Partidária': '11764',
 'Partido Político - Órgão de Direção Estadual': '11766',
 'Partido Político - Órgão de Direção Municipal': '11767',
 'Partido Político - Órgão de Direção Nacional': '11768',
 'Partido Político - Comissão Provisória': '11769',
 'Prestação de Contas - De Exercício Financeiro': '12048',
 'Propaganda Política': '11770',
 'Propaganda Política - Propaganda Intrapartidária': '11771',
 'Propaganda Política Partidária': '11772',
 'Propaganda Política - Propaganda Partidária': '11773',
 'Requerimento': '11778',
 'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
 'Revisão de Tutela Antecipada Antecedente': '12152'}