just_est_tur_rec = {'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO': '9985',
                    'Atos Administrativos': '9997',
                    'Abuso de Poder': '10894',
                    'Serviços': '10028',
                    'Saúde': '10064',
                    'Fornecimento de Medicamentos': '11884',
                    'Tratamento Médico-Hospitalar': '11883',
                    'Unidade de terapia intensiva (UTI) ou unidade de cuidados intensivos (UCI)': '11885',
                    'Tratamento Médico-Hospitalar e/ou Fornecimento de Medicamentos': '10069',
                    'DIREITO CIVIL': '899',
                    'Coisas': '10432',
                    'Anticrese': '10495',
                    'Enfiteuse': '10482',
                    'Habitação': '10487',
                    'Hipoteca': '10494',
                    'Penhor': '10488',
                    'Direitos e Títulos de Crédito': '10491',
                    'Industrial / Mercantil': '10490',
                    'Legal': '10493',
                    'Rural - Agrícola/Pecuário': '10489',
                    'Veículos': '10492',
                    'Posse': '10444',
                    'Aquisição': '10455',
                    'Esbulho / Turbação / Ameaça': '10445',
                    'Imissão': '10446',
                    'Promessa de Compra e Venda': '10496',
                    'Propriedade': '10448',
                    'Adjudicação Compulsória': '10450',
                    'Alienação Judicial': '10454',
                    'Acessão': '10456',
                    'Usucapião da L 6.969/1981': '10500',
                    'Usucapião Especial (Constitucional)': '10457',
                    'Usucapião Especial Coletiva': '10460',
                    'Usucapião Extraordinária': '10458',
                    'Usucapião Ordinária': '10459',
                    'Condomínio': '10462',
                    'Condomínio em Edifício': '10463',
                    'Administração': '10464',
                    'Alteração de Coisa Comum': '10465',
                    'Assembléia': '4907',
                    'Despesas Condominiais': '10467',
                    'Direitos / Deveres do Condômino': '10468',
                    'Multa': '10595',
                    'Vaga de garagem': '10469',
                    'Direito de Vizinhança': '10461',
                    'Divisão e Demarcação': '10451',
                    'Incorporação Imobiliária': '10470',
                    'Perda da Propriedade': '10449',
                    'Propriedade Fiduciária': '10481',
                    'Propriedade Intelectual / Industrial': '4654',
                    'Desenho Industrial': '4670',
                    'Direito Autoral': '4656',
                    'Marca': '4680',
                    'Patente': '4660',
                    'Programa de Computador': '10499',
                    'Propriedade Resolúvel': '10480',
                    'Reivindicação': '10452',
                    'Retificação de Área de Imóvel': '10453',
                    'Servidão': '10483',
                    'Superfície': '10485',
                    'Uso': '10486',
                    'Usufruto': '10484',
                    'Empresas': '9616',
                    'Espécies de Sociedades': '9617',
                    'Anônima': '9623',
                    'Cooperativa': '9625',
                    'Recuperação judicial e Falência': '4993',
                    'Liquidação': '5001',
                    'Família': '5626',
                    'Bem de Família': '7661',
                    'Violência Doméstica Contra a Mulher': '10949',
                    'Fatos Jurídicos': '7947',
                    'Ato / Negócio Jurídico': '4701',
                    'Defeito, nulidade ou anulação': '4703',
                    'Evicção ou Vicio Redibitório': '4706',
                    'Prescrição e Decadência': '5632',
                    'Obrigações': '7681',
                    'Adimplemento e Extinção': '7690',
                    'Compensação': '7709',
                    'Confusão': '7710',
                    'Dação em Pagamento': '7707',
                    'Desconto em folha de pagamento': '10592',
                    'Imputação do Pagamento': '7706',
                    'Novação': '7708',
                    'Pagamento': '7703',
                    'Pagamento com Sub-rogação': '7705',
                    'Pagamento em Consignação': '7704',
                    'Remissão das Dívidas': '7711',
                    'Atos Unilaterais': '7694',
                    'Enriquecimento sem Causa': '7715',
                    'Gestão de Negócios': '7713',
                    'Pagamento Indevido': '7714',
                    'Promessa de Recompensa': '7712',
                    'Espécies de Contratos': '9580',
                    'Agêncie e Distribuição': '9581',
                    'Alienação Fiduciária': '9582',
                    'Arrendamento Mercantil': '9584',
                    'Arrendamento Rural': '9583',
                    'Câmbio': '4728',
                    'Cartão de Crédito': '7772',
                    'Comissão': '9586',
                    'Comodato': '9602',
                    'Compra e Venda': '9587',
                    'Compromisso': '9606',
                    'Constituição de Renda': '9604',
                    'Contratos Bancários': '9607',
                    'Corretagem': '9588',
                    'Crédito Rural': '10501',
                    'Depósito': '9589',
                    'Doação': '9590',
                    'Edição': '5680',
                    'Empreitada': '9591',
                    'Estimatório': '9601',
                    'Fiança': '4310',
                    'Franquia': '9608',
                    'Jogo e Aposta': '9605',
                    'Locação de Imóvel': '9593',
                    'Benfeitorias': '9614',
                    'Despejo para Uso de Ascendentes e Descendentes': '9611',
                    'Despejo para Uso Próprio': '9610',
                    'Despejo por Denúncia Vazia': '9612',
                    'Direito de Preferência': '9615',
                    'Locação de Móvel': '9609',
                    'Mandato': '9594',
                    'Mútuo': '9603',
                    'Parceria Agrícola e/ou pecuária': '4794',
                    'Prestação de Serviços': '9596',
                    'Previdência privada': '4805',
                    'Representação comercial': '4813',
                    'Seguro': '7621',
                    'Sistema Financeiro da Habitação': '4839',
                    'Equivalência salarial': '4840',
                    'Quitação': '4841',
                    'Reajuste de Prestações': '4842',
                    'Revisão do Saldo Devedor': '4854',
                    'Sustação/Alteração de Leilão': '4846',
                    'Transferência de Financiamento (contrato de gaveta)': '4843',
                    'Vícios de Construção': '10588',
                    'Transação': '10630',
                    'Transporte de Coisas': '9599',
                    'Transporte de Pessoas': '9600',
                    'Troca ou Permuta': '9595',
                    'Espécies de Títulos de Crédito': '7717',
                    'Cédula de Crédito à Exportação': '4961',
                    'Cédula de Crédito Bancário': '4960',
                    'Cédula de Crédito Comercial': '4962',
                    'Cédula de Crédito Industrial': '4963',
                    'Cédula de Crédito Rural': '4964',
                    'Cédula de Produto Rural': '4968',
                    'Cédula Hipotecária': '4969',
                    'Cheque': '4970',
                    'Debêntures': '4971',
                    'Duplicata': '4972',
                    'Letra de Câmbio': '4973',
                    'Nota de Crédito Comercial': '4974',
                    'Nota de Crédito Industrial': '4975',
                    'Nota de Crédito Rural': '4976',
                    'Nota Promissória': '4980',
                    'Warrant': '4981',
                    'Inadimplemento': '7691',
                    'Arras ou Sinal': '7701',
                    'Cláusula Penal': '7700',
                    'Correção Monetária': '10685',
                    'Juros de Mora - Legais / Contratuais': '7699',
                    'Capitalização / Anatocismo': '10585',
                    'Limitação de Juros': '10586',
                    'Perdas e Danos': '7698',
                    'Rescisão / Resolução': '10582',
                    'Preferências e Privilégios Creditórios': '7696',
                    'Títulos de Crédito': '4949',
                    'Anulação': '4951',
                    'Requisitos': '4957',
                    'Sustação de Protesto': '9575',
                    'Transmissão': '7688',
                    'Assunção de Dívida': '7689',
                    'Cessão de Crédito': '4718',
                    'Pessoas Jurídicas': '9981',
                    'Associação': '4897',
                    'Eleição': '4909',
                    'Exclusão de associado': '9546',
                    'Extinção': '4910',
                    'Inclusão de associado': '9545',
                    'Fundação de Direito Privado': '4905',
                    'Fiscalização': '9547',
                    'Organizações Religiosas': '7952',
                    'Responsabilidade Civil': '10431',
                    'Dano Ambiental': '10438',
                    'Indenização por Dano Material': '8808',
                    'Acidente de Trânsito': '10435',
                    'Direito de Imagem': '10437',
                    'Erro Médico': '10434',
                    'Lei de Imprensa': '10436',
                    'Indenização por Dano Moral': '7779',
                    'DIREITO DA CRIANÇA E DO ADOLESCENTE': '9633',
                    'Ato Infracional': '9634',
                    'Contra a dignidade sexual': '9740',
                    'Assédio Sexual': '5851',
                    'Atentado ao Pudor Mediante Fraude': '3467',
                    'Atentado Violento ao Pudor': '3466',
                    'Casa de Prostituição': '5853',
                    'Corrupção de Menores': '3468',
                    'Estupro': '3465',
                    'Favorecimento da Prostituição': '5852',
                    'Mediação para Servir a Lascívia de Outrem': '3471',
                    'Posse Sexual Mediante Fraude': '5850',
                    'Rufianismo': '5854',
                    'Ultraje Público ao Pudor (Ato/Escrito Obsceno)': '3469',
                    'DIREITO DO CONSUMIDOR': '1156',
                    'Cláusulas Abusivas': '11974',
                    'Contratos de Consumo': '7771',
                    'Bancários': '7752',
                    'Expurgos Inflacionários / Planos Econômicos': '10945',
                    'Consórcio': '7619',
                    'Estabelecimentos de Ensino': '7620',
                    'Financiamento de Produto': '7773',
                    'Fornecimento de Água': '7761',
                    'Fornecimento de Energia Elétrica': '7760',
                    'Planos de Saúde': '6233',
                    'Fornecimento de medicamentos': '12222',
                    'Reajuste contratual': '12225',
                    'Tratamento médico-hospitalar': '12223',
                    'Unidade de terapia intensiva (UTI) ou Unidade de cuidados intensivos (UCI)': '12224',
                    'Serviços Hospitalares': '7775',
                    'Serviços Profissionais': '7774',
                    'Telefonia': '7617',
                    'Assinatura Básica Mensal': '7626',
                    'Cobrança indevida de ligações': '10598',
                    'Pulsos Excedentes': '7627',
                    'Transporte Aéreo': '4862',
                    'Acidente Aéreo': '7748',
                    'Atraso de vôo': '4829',
                    'Cancelamento de vôo': '4830',
                    'Extravio de bagagem': '4832',
                    'Overbooking': '4831',
                    'Transporte Terrestre': '7776',
                    'Turismo': '7618',
                    'Responsabilidade do Fornecedor': '6220',
                    'Abatimento proporcional do preço': '7769',
                    'Inclusão Indevida em Cadastro de Inadimplentes': '6226',
                    'Protesto Indevido de Título': '7781',
                    'Interpretação / Revisão de Contrato': '7770',
                    'Rescisão do contrato e devolução do dinheiro': '7768',
                    'Substituição do Produto': '7767',
                    'DIREITO DO TRABALHO': '864',
                    'Responsabilidade Civil do Empregador': '2567',
                    'Acidente de Trabalho': '8809',
                    'Indenizaçao por Dano Moral': '1855',
                    'DIREITO PENAL': '287',
                    'Contravenções Penais': '3692',
                    'Fabrico, comércio ou detenção de arma branca ou munição': '12343',
                    'Jogo de azar': '12350',
                    'Jogo do bicho': '12352',
                    'Loteria não autorizada': '12351',
                    'Omissão de cautela na guarda ou condução de animal': '12346',
                    'Omissão de comunicação de crime': '12355',
                    'Perturbação da tranquilidade': '12354',
                    'Perturbação do trabalho ou do sossego alheios': '12347',
                    'Porte de arma (branca)': '12344',
                    'Provocação de tumulto ou conduta inconveniente': '12340',
                    'Recusa de dados sobre a própria identificação ou qualificação': '12356',
                    'Servir bebidas alcóolicas a vulneráveis': '12353',
                    'Simulação de Qualidade de Funcionário': '12348',
                    'Uso ilegítimo de uniforme ou distintivo': '12349',
                    'Vias de fato': '12345',
                    'Crime / Contravenção contra Criança / Adolescente': '10950',
                    'Crime / Contravenção contra Idoso': '10951',
                    'Crime Culposo': '5865',
                    'Crime Tentado': '5555',
                    'Crime/contravenção decorrente de conflito fundiário coletivo': '11414',
                    'Crimes Contra a Administração da Justiça': '5874',
                    'Auto-acusação falsa': '3578',
                    'Comunicação falsa de crime ou de contravenção': '3577',
                    'Evasão mediante violência contra a pessoa': '3587',
                    'Exercício arbitrário das próprias razões': '3581',
                    'Exercício arbitrário ou abuso de poder': '3585',
                    'Favorecimento pessoal': '3583',
                    'Favorecimento real': '3584',
                    'Fraude processual': '3582',
                    'Fuga de pessoa presa ou submetida a medida de segurança': '3586',
                    'Motim de presos': '3589',
                    'Patrocínio infiel': '3590',
                    'Violência ou fraude em arrematação judicial': '3594',
                    'Crimes contra a Dignidade Sexual': '3463',
                    'Crimes contra a Família': '3472',
                    'Crime contra o Pátrio-Poder e Tutela': '3488',
                    'Induzimento a Fuga, Entrega Arbitrária ou Sonegação de Incapazes': '3489',
                    'Subtração de Incapazes': '3490',
                    'Crimes Contra a Assistência Familiar': '3473',
                    'Abandono Intelectual': '3475',
                    'Crimes contra o Casamento': '3477',
                    'Conhecimento Prévio de Impedimento': '3480',
                    'Induzimento a erro essencial e ocultação de impedimento': '3481',
                    'Crimes contra a Fé Pública': '3523',
                    'Adulteração de Sinal Identificador de Veículo Automotor': '3546',
                    'Certidão ou atestado ideologicamente falso': '3535',
                    'Emissão de título ao portador sem permissão legal': '3528',
                    'Falsa identidade': '3542',
                    'Falsidade de atestado médico': '3537',
                    'Falsidade ideológica': '3533',
                    'Falsidade material de atestado ou certidão': '3536',
                    'Falsificação de documento particular': '3532',
                    'Falsificação de documento público': '3531',
                    'Falsificação de papéis públicos': '3529',
                    'Falsificação do selo ou sinal público': '3530',
                    'Falsificação do sinal empregado no contraste de metal precioso ou na fiscalização alfandegária, ou para outros fins': '3541',
                    'Falso reconhecimento de firma ou letra': '3534',
                    'Fraude de lei sobre estrangeiros': '3543',
                    'Moeda Falsa / Assimilados': '3524',
                    'Petrechos de Falsificação de Papéis Públicos': '3545',
                    'Petrechos para falsificação de moeda': '3527',
                    'Reprodução ou adulteração de selo ou peça filatélica': '3538',
                    'Supressão de documento': '3540',
                    'Uso de documento falso': '3539',
                    'Crimes contra a Honra': '3394',
                    'Calúnia': '3395',
                    'Difamação': '3396',
                    'Injúria': '3397',
                    'Crimes contra a Incolumidade Pública': '3491',
                    'Arremesso de projétil': '3502',
                    'Atentado contra a segurança de serviços de utilidade pública': '3503',
                    'Atentado contra a segurança de transporte público': '3501',
                    'Charlatanismo': '3510',
                    'Corrupção ou Poluição de Água Potável': '3511',
                    'Curandeirismo': '3512',
                    'Desabamento ou desmoronamento': '3496',
                    'Desabamento ou desmoronamento culposo': '11969',
                    'Desastre ferroviário / Perigo de Desastre Ferroviário': '3500',
                    'Desastre ferroviário culposo': '11972',
                    'Difusão culposa de doença ou praga': '11958',
                    'Difusão de doença ou praga': '3498',
                    'Emprego de Processo Proibido/Substância não permitida': '3506',
                    'Envenenamento de Água Potável / Substância Alimentícia ou Medicinal': '3513',
                    'Epidemia': '3505',
                    'Exercício Ilegal da Medicina, Arte Dentária ou Farmacêutica': '3509',
                    'Explosão': '3493',
                    'Explosão culposa': '11963',
                    'Fabrico / Fornecimento / Aquisição / Posse ou Transporte de Explosivos ou Gás Tóxico ou Asfixiante': '5862',
                    'Falsificação / Corrupção / Adulteração / Alteração de produto destinado a fins terapêuticos ou medicinais': '3508',
                    'Falsificação / Corrupção / Adulteração / Alteração de Substância ou Produtos Alimentícios': '3514',
                    'Incêndio': '3492',
                    'Incêndio culposo': '11961',
                    'Infração de Medida Sanitária Preventiva': '3515',
                    'Interrupção /perturbação de serviços telegráficos/telefônicos': '3504',
                    'Inundação / Perigo de Inundação': '3495',
                    'Inundação culposa': '11967',
                    'Invólucro ou recipiente com falsa indicação': '3507',
                    'Medicamento em Desacordo com Receita Médica': '5867',
                    'Omissão de Notificação de Doença': '3516',
                    'Outras Substâncias Nocivas a Saúde Pública': '3517',
                    'Substância Destinada à Falsificação': '3519',
                    'Subtração, ocultação ou inutilização de material de salvamento': '3497',
                    'Uso culposo de gás tóxico ou asfixiante': '11966',
                    'Uso de gás tóxico ou asfixiante': '3494',
                    'Venda de Produtos ou Substância nas Condições dos Artigos 274 e 275': '5866',
                    'Crimes contra a inviolabilidade de correspondência': '3407',
                    'Sonegação ou destruição de correspondência': '3409',
                    'Violação de comunicação telegráfica, radioelétrica ou telefônica': '3410',
                    'Violação de correspondência': '3408',
                    'Violação de Correspondência comercial': '3411',
                    'Crimes contra a inviolabilidade de domicílio': '3405',
                    'Violação de domicílio': '3406',
                    'Crimes contra a inviolabilidade de segredo': '3412',
                    'Divulgação de segredo': '3413',
                    'Invasão de Dispositivo Informático': '11978',
                    'Violação do segredo profissional': '3414',
                    'Crimes contra a liberdade pessoal': '3400',
                    'Ameaça': '3402',
                    'Constrangimento ilegal': '3401',
                    'Redução a condição análoga à de escravo': '3404',
                    'Crimes contra a Organização do Trabalho': '3445',
                    'Atentado contra a liberdade de associação': '3448',
                    'Atentado contra a liberdade de contrato de trabalho e boicotagem violenta': '3447',
                    'Atentado contra a liberdade de trabalho': '3446',
                    'Exercício de atividade com infração de decisão administrativa': '3453',
                    'Frustração de direitos assegurados por lei trabalhista': '3452',
                    'Paralisação de trabalho de interesse coletivo': '3450',
                    'Paralisação de trabalho, seguida de violência ou perturbação da ordem': '3449',
                    'Crimes contra a Paz Pública': '3520',
                    'Apologia de Crime ou Criminoso': '5870',
                    'Incitação ao Crime': '5869',
                    'Crimes contra a Propriedade Intelectual': '3442',
                    'Violação de direito autoral': '3443',
                    'Crimes contra a vida': '3369',
                    'Crimes Contra as Finanças Públicas': '5875',
                    'Contratação de Operação de Crédito': '5903',
                    'Inscrição de Despesas Não Empenhadas': '5904',
                    'Não Cancelamento de Restos a Pagar': '5908',
                    'Prestação de Garantia Graciosa': '5907',
                    'Crimes contra o Patrimônio': '3415',
                    'Alteração de limites': '3423',
                    'Alteração de local especialmente protegido': '3429',
                    'Apropriação de Coisa Achada': '5573',
                    'Apropriação de Coisa Havida por Erro, Caso Fortuito ou Força da Natureza': '3437',
                    'Apropriação de Tesouro': '5572',
                    'Dano': '3426',
                    'Dano em coisa de valor artístico, arqueológico ou histórico': '3428',
                    'Dano Qualificado': '5571',
                    'Esbulho possessório': '3425',
                    'Fraude à execução': '3434',
                    'Fraude no Comércio': '5844',
                    'Furto de coisa comum': '3418',
                    'Furto Privilegiado': '5564',
                    'Introdução ou abandono de animais em propriedade alheia': '3427',
                    'Outras fraudes': '3433',
                    'Receptação': '3435',
                    'Usurpação de águas': '3424',
                    'Crimes contra o sentimento religioso e contra o respeito aos mortos': '3457',
                    'Impedimento ou Perturbação de Cerimônia Funerária': '3459',
                    'Ultraje / Impedimento ou Perturbação de Culto Religioso': '3462',
                    'Crimes Praticados por Funcionários Públicos Contra a Administração em Geral': '3547',
                    'Abandono de função': '3561',
                    'Advocacia administrativa': '3559',
                    'Condescendência criminosa': '3558',
                    'Emprego irregular de verbas ou rendas públicas': '3552',
                    'Exercício funcional ilegalmente antecipado ou prolongado': '3562',
                    'Modificação ou alteração não autorizada de sistema de informações': '3597',
                    'Prevaricação': '3557',
                    'Violação do sigilo de proposta de concorrência': '3564',
                    'Violação do sigilo funcional': '3563',
                    'Crimes Praticados por Particular Contra a Administração em Geral': '5872',
                    'Corrupção ativa': '3568',
                    'Desacato': '3573',
                    'Desobediência': '3572',
                    'Impedimento, perturbação ou fraude de concorrência': '3569',
                    'Inutilização de edital ou de sinal': '3570',
                    'Resistência': '3566',
                    'Sonegação de contribuição previdenciária': '3598',
                    'Subtração ou inutilização de livro ou documento': '3571',
                    'Tráfico de influência': '3567',
                    'Usurpação de função pública': '3565',
                    'Crimes Praticados por Particular Contra a Administração Pública Estrangeira': '5873',
                    'Crimes Previstos na Legislação Extravagante': '3603',
                    'Crime Contra a Administração da Justiça - Lei da Ação de Alimentos': '5893',
                    'Crime de Quebra de Sigilo Financeiro': '3655',
                    'Crimes Agrários': '3651',
                    'Crimes contra a Economia Popular': '3605',
                    'Crimes contra a Propriedade Industrial': '3438',
                    'Crimes Cometidos por Meio de Marca, Título de Estabelecimento e Sinal de Propaganda': '5881',
                    'Crimes contra as Marcas': '5880',
                    'Crimes contra Indicações Geeográficas e Demais Indicações': '5882',
                    'Crimes contra os Desenhos Industriais': '5879',
                    'Crimes contra Patente de Invenção': '5878',
                    'Crimes de Concorrência Desleal': '5883',
                    'Crimes contra as Relações de Consumo': '3616',
                    'Crimes contra as Telecomunicações': '3629',
                    'Crimes contra o Meio Ambiente e o Patrimônio Genético': '3618',
                    'Agrotóxicos': '3622',
                    'Crime contra a administração ambiental': '10986',
                    'Crimes contra a Fauna': '3619',
                    'Crimes contra a Flora': '3620',
                    'Crimes contra o Ordenamento Urbano e o Patrimônio Cultural': '11780',
                    'Da Poluição': '3621',
                    'Pesca': '3627',
                    'Crimes contra o mercado de capitais': '3638',
                    'Crimes da Lei de licitações': '3642',
                    'Crimes da Lei de remoção de órgãos e tecidos': '3643',
                    'Crimes de "Lavagem" ou Ocultação de Bens, Direitos ou Valores': '3628',
                    'Crimes de Abuso de Autoridade': '3606',
                    'Crimes de genocídio': '3640',
                    'Crimes de Imprensa': '3634',
                    'Crimes de Responsabilidade': '3604',
                    'Crimes de Tortura': '3631',
                    'Crimes de Tráfico Ilícito e Uso Indevido de Drogas': '3607',
                    'Associação para a Produção e Tráfico e Condutas Afins': '5897',
                    'Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas': '5899',
                    'Condução de Embarcação ou Aeronave sob Efeito de Drogas': '5901',
                    'Fabricação de Objeto Destinado a Produção de Drogas e Condutas Afins': '5894',
                    'Financiamento ou Custeio de Produção ou Tráfico de Drogas': '5898',
                    'Indução, Instigação ou Auxílio ao Uso de Drogas': '5895',
                    'Oferecimento de Drogas para Consumo Conjunto': '5896',
                    'Posse de Drogas para Consumo Pessoal': '5885',
                    'Prescrição Culposa de Drogas': '5900',
                    'Tráfico de Drogas e Condutas Afins': '3608',
                    'Crimes de Trânsito': '3632',
                    'Crimes do Código Brasileiro de Telecomunicações': '3656',
                    'Crimes do Sistema Nacional de Armas': '3633',
                    'Crimes Falimentares': '3661',
                    'Crimes praticados contra os índios e a cultura indígena': '3647',
                    'Crimes Previstos na Lei de Estrangeiros': '3630',
                    'Crimes Previstos no Estatuto da criança e do adolescente': '3637',
                    'Crimes Previstos no Estatuto do Idoso': '3659',
                    'Crimes relacionados à Comissão Parlamentar de Inquérito': '3653',
                    'Recusa, retardamento ou omissão de dados técnicos indispensáveis à propositura de Ação Civil Pública': '3650',
                    'Representação caluniosa': '3617',
                    'Sigilo Telefônico': '3641',
                    'Fato Atípico': '10952',
                    'Lesão Corporal': '3385',
                    'Decorrente de Violência Doméstica': '5560',
                    'Gravíssima': '5557',
                    'Leve': '3386',
                    'Privilegiada': '5558',
                    'Parte Geral': '10620',
                    'Aplicação da Pena': '10621',
                    'Regime inicial': '10633',
                    'Substituição da Pena': '10628',
                    'Efeitos da Condenação': '10642',
                    'Perda da Função Pública': '10643',
                    'Perda de Bens e Valores': '7786',
                    'Excludentes': '10613',
                    'Estado de Necessidade': '10617',
                    'Estrito Cumprimento do Dever Legal': '10618',
                    'Inexigibilidade de Conduta Diversa': '10619',
                    'Legítima Defesa': '10616',
                    'Extinção da Punibilidade': '10622',
                    'Anistia': '10625',
                    'Indulto': '10626',
                    'Pagamento ou Parcelamento do Crédito Tributário': '10627',
                    'Perdão': '10624',
                    'Prescrição': '10623',
                    'Suspensão condicional da pena': '10634',
                    'Tipicidade': '10612',
                    'Abolitio Criminis': '10614',
                    'Princípio da Insignificância': '10615',
                    'Periclitação da Vida e da Saúde e Rixa': '3388',
                    'Abandono de incapaz': '3391',
                    'Maus Tratos': '10508',
                    'Omissão de socorro': '3392',
                    'Perigo de Contágio Venéreo': '5911',
                    'Perigo para a vida ou saúde de outrem': '3390',
                    'Rixa': '3393',
                    'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                    'Partes e Procuradores': '8842',
                    'Substituição Processual': '8867',
                    'Assistência Judiciária Gratuita': '8843',
                    'Capacidade Processual': '9493',
                    'Litigância de Má-Fé': '8865',
                    'Litisconsórcio e Assistência': '8866',
                    'Procuração / Mandato': '8868',
                    'Representação em Juízo': '8873',
                    'Substituição da Parte': '9494',
                    'Sucumbência': '8874',
                    'Custas': '10658',
                    'Honorários Advocatícios': '10655',
                    'Atos Processuais': '8893',
                    'Prazo': '8928',
                    'Citação': '11783',
                    'Intimação / Notificação': '10939',
                    'Nulidade': '4264',
                    'Valor da Causa': '8934',
                    'Formação, Suspensão e Extinção do Processo': '8938',
                    'Suspensão do Processo': '8939',
                    'Extinção do Processo Sem Resolução de Mérito': '8942',
                    'Modificação ou Alteração do Pedido': '8941',
                    'Jurisdição e Competência': '4291',
                    'Competência': '8829',
                    'Liquidação / Cumprimento / Execução': '9148',
                    'Ato Atentatório à Dignidade da Justiça': '9520',
                    'Benefício de Ordem': '9519',
                    'Causas Supervenientes à Sentença': '9517',
                    'Concurso de Credores': '9418',
                    'Constrição / Penhora / Avaliação / Indisponibilidade de Bens': '9163',
                    'Efeito Suspensivo / Impugnação / Embargos à Execução': '9518',
                    'Expropriação de Bens': '9180',
                    'Extinção da Execução': '9414',
                    'Fraude à Execução': '9450',
                    'Imunidade de Execução': '9453',
                    'Levantamento de Valor': '9160',
                    'Multa Cominatória / Astreintes': '10686',
                    'Multa de 10%': '9166',
                    'Nulidade / Inexigibilidade do Título': '9178',
                    'Obrigação de Entregar': '10670',
                    'Busca e Apreensão': '10677',
                    'Imissão na Posse': '10676',
                    'Requerimento de Apreensão de Veículo': '12161',
                    'Requerimento de Reintegração de Posse': '12160',
                    'Obrigação de Fazer / Não Fazer': '10671',
                    'Remição': '9189',
                    'Sucessão': '9484',
                    'Valor da Execução / Cálculo / Atualização': '9149',
                    'Juros': '10684',
                    'Taxa SELIC': '10687',
                    'Medida Cautelar': '9192',
                    'Caução / Contracautela': '9532',
                    'Indenização do Prejuízo': '9524',
                    'Liminar': '9196',
                    'Ministério Público': '8875',
                    'Objetos de cartas precatórias/de ordem': '11781',
                    'Atos executórios': '11786',
                    'Diligências': '11785',
                    'Intimação': '11782',
                    'Oitiva': '11784',
                    'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                    'Do Juiz': '8884',
                    'Impedimento': '10600',
                    'Suspeição': '10601',
                    'Dos Auxiliares da Justiça': '8888',
                    'Processo e Procedimento': '8960',
                    'Antecipação de Tutela / Tutela Específica': '8961',
                    'Erro de Procedimento': '8986',
                    'Provas': '10925',
                    'Depoimento': '10940',
                    'Revelia': '9024',
                    'Vícios Formais da Sentença': '9026',
                    'Recurso': '4305',
                    'Cabimento': '9098',
                    'Efeitos': '9047',
                    'Preparo / Deserção': '9050',
                    'Regularidade Formal': '10666',
                    'Tempestividade': '9060',
                    'Revisão de Tutela Antecipada Antecedente': '12152',
                    'DIREITO PROCESSUAL PENAL': '1209',
                    'Ação Penal': '4263',
                    'Ausência de Fundamentação': '10867',
                    'Ausência de Publicidade': '10866',
                    'Cerceamento de Defesa': '10865',
                    'Quesitos': '10599',
                    'Vício Formal do Julgamento': '10890',
                    'Perempção': '7935',
                    'Prisão Decorrente de Sentença Condenatória': '10640',
                    'Prova Ilícita': '10926',
                    'Suspensão': '4271',
                    'Condicional do processo': '10602',
                    'Parcelamento de crédito tributário': '10603',
                    'Questão Prejudicial': '10691',
                    'Trancamento': '4272',
                    'Denúncia/Queixa': '4368',
                    'Desclassificação': '10935',
                    'Recebimento': '4370',
                    'Rejeição': '4371',
                    'Execução Penal': '7942',
                    'Medidas de Segurança': '7793',
                    'Internação': '7795',
                    'Tratamento Ambulatorial': '7794',
                    'Pena de Multa': '7792',
                    'Pena Privativa de Liberdade': '7791',
                    'Pena Restritiva de Direitos': '7790',
                    'Interdição Temporária de Direitos': '7788',
                    'Limitação de Fim de Semana': '7789',
                    'Prestação de Serviços à Comunidade': '7787',
                    'Prestação Pecuniária': '7785',
                    'Falsidade': '7945',
                    'Desaforamento': '10631',
                    'Imunidade em razão de função, ofício ou profissão': '10909',
                    'Liberdade Provisória': '7928',
                    'Prisão em flagrante': '7929',
                    'Prisão Preventiva': '4355',
                    'Denegação': '7941',
                    'Deserção': '7940',
                    'Registro de Ocorrência pela PM': '12159'}
