just_fed_2_grau = {'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO': '9985',
                   'Agentes Políticos': '10186',
                   'Magistratura': '10187',
                   'Afastamento': '10196',
                   'Aposentadoria': '10254',
                   'Processo Disciplinar / Sindicância': '10197',
                   'Promoção': '10334',
                   'Quinto Constitucional': '10675',
                   'Remoção': '10229',
                   'Remuneração': '10203',
                   'Ministério Público': '8875',
                   'Parlamentares': '10213',
                   'Afastamento do Cargo': '10202',
                   'Indisponibilidade de Bens': '10206',
                   'Prestação de Contas': '10205',
                   'Recondução': '10224',
                   'Verba de Representação': '10732',
                   'Prefeito': '10201',
                   'Atos Administrativos': '9997',
                   'Ato Lesivo ao Patrimônio Artístico, Estético, Histórico ou Turístico': '10010',
                   'Fiscalização': '10015',
                   'Exportação/Vedações': '10017',
                   'Inspeção Fitossanitária': '10016',
                   'Inspeção Sanitária de Origem Animal': '10018',
                   'Segurança e Medicina do Trabalho': '10019',
                   'Improbidade Administrativa': '10011',
                   'Dano ao Erário': '10012',
                   'Enriquecimento ilícito': '10013',
                   'Violação aos Princípios Administrativos': '10014',
                   'Infração Administrativa': '10022',
                   'Apreensão': '10025',
                   'Interdição': '10024',
                   'Multas e demais Sanções': '10168',
                   'Inquérito / Processo / Recurso Administrativo': '10009',
                   'Licenças': '10350',
                   'Comercialização e/ou Utilização sem Restrições de Medicamentos': '10003',
                   'Comercialização sem Restrições de Gêneros Alimentícios': '10002',
                   'Comercialização sem Restrições de Produtos Industrializados': '10001',
                   'Declaração de Bagagem': '9999',
                   'Declaração de Trânsito Aduaneiro': '10000',
                   'Funcionamento de Comércio de Derivados de Petróleo': '10004',
                   'Funcionamento de Estabelecimentos Empresariais': '10006',
                   'Jogos de Bingo e/ou Caça-níqueis': '10084',
                   'Loterias/Sorteio': '10079',
                   'Registro / Porte de arma de fogo': '10007',
                   'Registro de Aeronave': '10008',
                   'Registro de Empresa': '10005',
                   'Registro de Direito Autoral': '10026',
                   'Registro de Marcas, Patentes ou Invenções': '10021',
                   'Registro de Programa de Computador': '10027',
                   'Registro de Trabalho Portuário/Órgão de Gestão de Mão-de-Obra': '10020',
                   'Comissão Parlamentar de Inquérito - CPI': '10412',
                   'Criação / Instalação / Prosseguimento / Encerramento': '10414',
                   'Limites do Objeto': '10416',
                   'Limites dos Poderes de Investigação': '10415',
                   'Quebra de Sigilo Bancário / Fiscal / Telefônico': '10413',
                   'Concurso Público / Edital': '10370',
                   'Anulação': '4951',
                   'Anulação e Correção de Provas / Questões': '10379',
                   'Classificação e/ou Preterição': '10381',
                   'Condições Especiais para Prestação de Prova': '10384',
                   'Curso de Formação': '10327',
                   'Escolaridade': '10380',
                   'Exame de Saúde e/ou Aptidão Física': '10376',
                   'Exame Psicotécnico / Psiquiátrico': '10378',
                   'Exigência de Prática Forense': '10374',
                   'Inscrição / Documentação': '10372',
                   'Limite de Idade': '10373',
                   'Prazo de Validade': '10383',
                   'Prova de Títulos': '10375',
                   'Reserva de Vagas para Deficientes': '10371',
                   'CONSELHOS': '11803',
                   'Conselho da Comunidade': '11833',
                   'Conselho de Direitos da Criança e Adolescente': '11835',
                   'Conselho do Idoso': '11832',
                   'Conselho sobre Drogas': '11834',
                   'Contratos Administrativos': '10421',
                   'Equilíbrio Financeiro': '10430',
                   'Execução Contratual': '10429',
                   'Pagamento Atrasado / Correção Monetária': '10422',
                   'Penalidades': '10428',
                   'Prorrogação': '10426',
                   'Rescisão': '10425',
                   'Suspensão': '10546',
                   'Termo Aditivo': '10427',
                   'Controle Externo da atividade policial': '11831',
                   'Dívida Ativa não-tributária': '10394',
                   'Cessão de créditos não-tributários': '10402',
                   'Ambiental': '10396',
                   'Metrológica': '10398',
                   'Profissional': '10399',
                   'Sanitárias': '10397',
                   'Segurança e/ou Medicina do Trabalho': '10400',
                   'Taxa de Ocupação / Laudêmio / Foro': '10401',
                   'Dívida Pública Mobiliária': '10182',
                   'Apólices da Dívida Pública': '10183',
                   'Títulos da Dívida Agrária': '10185',
                   'Títulos da Dívida Pública': '10184',
                   'Domínio Público': '10088',
                   'Bens Públicos': '10089',
                   'Águas Públicas': '10095',
                   'Bloqueio de Valores de Contas Públicas': '10096',
                   'Foro / Laudêmio': '10093',
                   'Locação / Permissão / Concessão / Autorização / Cessão de Uso': '10090',
                   'Taxa de Ocupação': '10101',
                   'Terras Devolutas': '10094',
                   'Terreno de Marinha': '10091',
                   'Utilização de bens públicos': '11870',
                   'Espaço Aéreo': '10107',
                   'Imóvel Funcional': '10097',
                   'Alienação': '10098',
                   'Ocupação': '10099',
                   'Reintegração de Posse': '10100',
                   'Patrimônio Histórico / Tombamento': '10108',
                   'Privatização': '10131',
                   'Recursos Minerais': '10106',
                   'Terras Indígenas': '10102',
                   'Demarcação': '10105',
                   'Restituição de área - FUNAI': '10104',
                   'Terreno Aldeado': '10103',
                   'Empregado Público / Temporário': '10409',
                   'Admissão / Permanência / Despedida': '10411',
                   'Contrato Temporário de Mão de Obra L 8.745/1993': '10410',
                   'Garantias Constitucionais': '9986',
                   'Alimentação': '11848',
                   'Anistia Política': '10330',
                   'Assistência Social': '11847',
                   'Comunicação Social': '11845',
                   'Direitos Indígenas': '9989',
                   'Intervenção em Estado / Município': '9990',
                   'Minorias Étnicas': '11844',
                   'Moradia': '11846',
                   'Não Discriminação': '11849',
                   'Pessoa Idosa': '11842',
                   'Pessoas com deficiência': '11843',
                   'Proteção da Intimidade e Sigilo de Dados': '10587',
                   'Intervenção do Estado na Propriedade': '10120',
                   'Desapropriação': '10121',
                   'Desapropriação de Imóvel Urbano': '10134',
                   'Desapropriação Indireta': '10125',
                   'Desapropriação por Interesse Social Comum / L 4.132/1962': '10123',
                   'Desapropriação por Interesse Social para Reforma Agrária': '10124',
                   'Desapropriação por Utilidade Pública / DL 3.365/1941': '10122',
                   'Direito de Preempção': '10133',
                   'Limitação Administrativa': '10130',
                   'Ocupação Temporária': '10129',
                   'Requisição de Bem Particular': '10135',
                   'Restituição de área': '10132',
                   'Retrocessão': '10126',
                   'Servidão Administrativa': '10128',
                   'Vistoria': '10127',
                   'Intervenção no Domínio Econômico': '10136',
                   'Agências/órgãos de regulação': '11871',
                   'Controle de Abastecimento': '10139',
                   'Controle de Preços': '10138',
                   'Expurgos Inflacionários / Planos Econômicos': '10945',
                   'Cruzados Novos / Bloqueio': '10155',
                   'Poupança': '10156',
                   'Importações': '10140',
                   'Desembaraço Aduaneiro': '10141',
                   'Regime ou Certificado de Origem MERCOSUL': '10142',
                   'Veículo de Turista Comunitário MERCOSUL': '10143',
                   'Incentivo': '10144',
                   'PROAGRO': '10145',
                   'Moeda Estrangeira': '10153',
                   'Política de Preço Mínimo': '10137',
                   'Proteção à Livre Concorrência': '10146',
                   'Acordo de Exclusividade': '10149',
                   'Atos de Concentração': '10151',
                   'Cartel': '10150',
                   'Preços Predatórios': '10148',
                   'Venda Casada': '10147',
                   'Licitações': '10385',
                   'Adjudicação': '10393',
                   'Convênio': '10392',
                   'Edital': '10388',
                   'Habilitação / Registro Cadastral / Julgamento / Homologação': '10387',
                   'Modalidade / Limite / Dispensa / Inexigibilidade': '10386',
                   'Recursos Administrativos': '10391',
                   'Revogação': '10389',
                   'Sanções Administrativas': '10390',
                   'Meio Ambiente': '10110',
                   'Agrotóxicos': '3622',
                   'Área de Preservação Permanente': '11828',
                   'Fauna': '10114',
                   'Flora': '10113',
                   'Gestão de Florestas Públicas': '10119',
                   'Mineração': '11822',
                   'Patrimônio Cultural': '11830',
                   'Poluição': '11825',
                   'Produtos Controlados / Perigosos': '11829',
                   'Recursos Hídricos': '11824',
                   'Reserva legal': '11823',
                   'Revogação/Anulação de multa ambiental': '10112',
                   'Revogação/Concessão de Licença Ambiental': '10111',
                   'Saneamento': '11862',
                   'Transgênicos': '10115',
                   'Unidade de Conservação da Natureza': '10118',
                   'Zona Costeira': '11827',
                   'Zoneamento Ecológico e Econômico': '11826',
                   'Militar': '10324',
                   'Pensão': '10250',
                   'Concessão': '6177',
                   'Provisória': '10251',
                   'Restabelecimento': '6178',
                   'Processo Administrativo Disciplinar / Sindicância': '10363',
                   'Advertência / Repreensão': '10364',
                   'Impedimento / Detenção / Prisão': '10365',
                   'Licenciamento / Exclusão': '10366',
                   'Responsabilidade Civil do Militar - Indenização ao Erário': '10512',
                   'Reajuste de Remuneração, Soldo, Proventos ou Pensão': '10342',
                   'Índice da URP abril e maio/1988 DL 2.425/1988': '10347',
                   'Índice da URV Lei 8.880/1994': '10318',
                   'Índice de 28,86% LL 8.622/1993 e 8.627/1993': '10343',
                   'Índice de 84,32% IPC março/1990': '10346',
                   'Índice do IPC junho/1987': '10320',
                   'Regime': '10325',
                   'Adidos, Agregados e Adjuntos': '10331',
                   'Corpo Feminino': '10336',
                   'Estabilidade': '10222',
                   'Ex-combatentes': '6116',
                   'Ingresso e Concurso': '10326',
                   'Reintegração': '10226',
                   'Serviço Militar dos Profissionais da Saúde': '10335',
                   'Serviço Militar Obrigatório': '10332',
                   'Sistema Remuneratório e Benefícios': '10288',
                   'Agregação': '10351',
                   'Assistência Médico-Hospitalar': '10356',
                   'Auxílio-invalidez': '10596',
                   'Férias': '10301',
                   'Gratificações e Adicionais': '10338',
                   'Inclusão de Dependente': '6171',
                   'Indenizações Regulares': '10340',
                   'Isonomia': '10341',
                   'Licença Prêmio': '10357',
                   'Licenciamento': '10358',
                   'Reforma': '10349',
                   'Remuneração Mínima': '10593',
                   'Reserva Remunerada': '10352',
                   'Tempo de Serviço': '10276',
                   'Transferência ex-officio para reserva': '10353',
                   'Transferência para reserva': '10355',
                   'Orçamento': '10954',
                   'Crédito Suplementar': '10958',
                   'Criação de Dotação Orçamentária': '10955',
                   'Repasse de Duodécimos': '10956',
                   'Repasse de Verbas Públicas': '10957',
                   'Ordem Urbanística': '11802',
                   'Comércio Ambulante': '11837',
                   'Operações Urbanas Consorciadas': '11838',
                   'Parcelamento do Solo': '11836',
                   'Posturas Municipais': '11839',
                   'Segurança em Edificações': '11840',
                   'Organização Político-administrativa / Administração Pública': '10157',
                   'Conselhos Regionais de Fiscalização Profissional e Afins': '10166',
                   'Anuidades OAB': '10172',
                   'Eleições': '10171',
                   'Exame da Ordem OAB': '10170',
                   'Exercício Profissional': '10173',
                   'Questões Funcionais': '10169',
                   'Registro Profissional': '10167',
                   'FGTS/Fundo de Garantia por Tempo de Serviço': '10158',
                   'Atualização de Conta': '10164',
                   'Juros Progressivos': '10161',
                   'Liberação de Conta': '10165',
                   'Localização de Contas': '10162',
                   'Fundo de Participação dos Municípios': '10180',
                   'Instituições Financeiras': '10174',
                   'Cooperativas de Crédito': '10178',
                   'Liberação de Depósitos de Instituição Liquidanda': '10175',
                   'Liquidação extrajudicial': '10179',
                   'Normatizações': '10176',
                   'Remuneração de Ativos Retidos': '10177',
                   'PIS/PASEP': '10163',
                   'Seguro desemprego': '10181',
                   'Organização Sindical': '10403',
                   'Contribuição Sindical': '6047',
                   'Dilação e Extensão de Base Territorial': '10407',
                   'Eleições Sindicais': '10405',
                   'Filiação': '10408',
                   'Registro Sindical': '10406',
                   'Política Agrícola': '11841',
                   'Política fundiária e da reforma agrária': '11873',
                   'Responsabilidade da Administração': '9991',
                   'Indenização por Dano Ambiental': '9994',
                   'Indenização por Dano Material': '7780',
                   'Acidente de Trânsito': '10435',
                   'Erro Médico': '10434',
                   'Variação Cambial': '10505',
                   'Indenização por Dano Moral': '7779',
                   'Responsabilidade Fiscal': '11863',
                   'Responsabilidade fiscal': '11874',
                   'Serviços': '10028',
                   'Concessão / Permissão / Autorização': '10073',
                   'Energia Elétrica': '5977',
                   'Fornecimento de Gás': '10074',
                   'Radiodifusão': '10078',
                   'Serviço Postal': '10082',
                   'Telefonia': '7617',
                   'Transporte Aéreo - Aeroporto': '10077',
                   'Transporte Aquaviário': '11809',
                   'Transporte Terrestre': '7776',
                   'Defensoria Pública': '10087',
                   'Ensino Fundamental e Médio': '10051',
                   'Educação Pré-escolar': '10062',
                   'Educação Profissionalizante': '10063',
                   'Ensino Especial': '10058',
                   'Exame Nacional de Ensino Médio / ENEM': '10055',
                   'Exame Supletivo': '10059',
                   'Material Didático': '10054',
                   'Matrícula': '10030',
                   'Mensalidade': '10052',
                   'Merenda': '10060',
                   'Penalidades Disciplinares': '10036',
                   'Transferência': '10228',
                   'Transporte': '10061',
                   'Ensino Superior': '10029',
                   'Colação de Grau': '10032',
                   'Colisão de Horário': '10037',
                   'Criação e/ou Autorização para funcionamento de Curso Superior': '10043',
                   'Currículo Escolar': '10040',
                   'Diplomas/Certificado de Conclusão do Curso': '10045',
                   'Exigência de Estágio Profissionalizante': '10033',
                   'Financiamento Privado da Educação e/ou Pesquisa': '10046',
                   'Financiamento Público da Educação e/ou Pesquisa': '10031',
                   'Freqüência às Aulas': '10035',
                   'Ingresso no Curso Superior': '10041',
                   'Jubilamento de Aluno': '10042',
                   'Mensalidades': '10039',
                   'Omissão de Entrega de Notas': '10044',
                   'Pós-Graduação': '10050',
                   'Provão - Avaliação da Educação Superior': '10048',
                   'Residência Médica': '10047',
                   'Sistemas de cotas - Lei 10.558/2002': '10049',
                   'Transferência de Estudante': '10034',
                   'Vestibular': '10038',
                   'Saúde': '10064',
                   'Controle Social e Conselhos de Saúde': '11855',
                   'Convênio Médico com o SUS': '10067',
                   'Doação e Transplante de Órgãos; Tecidos e Partes do Corpo Humano': '11857',
                   'Financiamento do SUS': '11852',
                   'Fornecimento de Medicamentos': '11884',
                   'Genética / Células Tronco': '10071',
                   'Hospitais e Outras Unidades de Saúde': '11856',
                   'Reajuste da Tabela do SUS': '10066',
                   'Repasse de Verbas do SUS': '10065',
                   'Ressarcimento ao SUS': '10070',
                   'Saúde Mental': '11854',
                   'Terceirização do SUS': '11851',
                   'Tratamento Médico-Hospitalar': '11883',
                   'Unidade de terapia intensiva (UTI) ou unidade de cuidados intensivos (UCI)': '11885',
                   'Tratamento Médico-Hospitalar e/ou Fornecimento de Medicamentos': '10069',
                   'Vigilância Sanitária e Epidemiológica': '11853',
                   'Sistema Nacional do Desporto': '10072',
                   'Servidor Público Civil': '10219',
                   'Compulsória': '10256',
                   'Invalidez Permanente': '10255',
                   'Voluntária': '10257',
                   'Jornada de Trabalho': '10287',
                   'Licenças / Afastamentos': '10258',
                   'Acompanhamento de Cônjuge ou Companheiro': '10273',
                   'Alistamento / Serviço Eleitoral': '10272',
                   'Amamentação': '10270',
                   'Atividade Política': '10267',
                   'Casamento': '10268',
                   'Dirigente Sindical': '10259',
                   'Doação de Sangue': '10271',
                   'Doença em Pessoa da Família': '10262',
                   'Exercício em Outro Município': '10274',
                   'Gestante / Adotante / Paternidade': '10264',
                   'Interesse Particular': '10265',
                   'Licença Capacitação (Aperfeiçoamento Profissional)': '10260',
                   'Licença por Acidente em Serviço': '10275',
                   'Licença-Prêmio': '10261',
                   'Luto': '10269',
                   'Serviço Militar': '10266',
                   'Tratamento da Própria Saúde': '10263',
                   'Processo Administrativo Disciplinar ou Sindicância': '10279',
                   'Advertência': '10281',
                   'Demissão ou Exoneração': '10280',
                   'Responsabilidade Civil do Servidor Público / Indenização ao Erário': '10283',
                   'Programa de Desligamento Voluntário (PDV)': '10286',
                   'Reajustes de Remuneração, Proventos ou Pensão': '10313',
                   'Correção Monetária de Diferenças Pagas em Atraso': '10946',
                   'Índice da URV fev/1989': '10314',
                   'Índice de 10,87% Lei 10.192/2001': '10321',
                   'Índice de 28,86% Lei 8.622/1993 e 8.627/1993': '10317',
                   'Índice de 45% Lei 8.237/1991': '10316',
                   'Índice de 47,94% Lei 8.676/1993': '10322',
                   'Índice de 84,32% março/1990': '10315',
                   'Reajuste da Lei 8.270/1991': '10319',
                   'Regime Estatutário': '10220',
                   'Acumulação de Cargos': '10225',
                   'Anistia Administrativa': '10231',
                   'Direito de Greve': '10227',
                   'Disponibilidade / Aproveitamento': '10234',
                   'Enquadramento': '10223',
                   'Estágio Probatório': '10238',
                   'Exoneração': '10241',
                   'Lotação': '10235',
                   'Nomeação': '10239',
                   'Posse e Exercício': '10240',
                   'Promoção / Ascensão': '10236',
                   'Readaptação': '10237',
                   'Redistribuição': '10233',
                   'Regime Previdenciário': '10230',
                   'Reversão': '10232',
                   'Abono de Permanência': '10662',
                   'Abono Pecuniário (Art. 78 Lei 8.112/1990)': '10294',
                   'Acumulação de Proventos': '10638',
                   'Adicional de Fronteira': '10293',
                   'Adicional de Horas Extras': '10303',
                   'Adicional de Insalubridade': '10291',
                   'Adicional de Periculosidade': '10292',
                   'Adicional de Produtividade': '10309',
                   'Adicional de Serviço Noturno': '10308',
                   'Adicional por Tempo de Serviço': '10302',
                   'Assistência à Saúde': '10244',
                   'Assistência Pré-escolar': '10245',
                   'Auxílio-Alimentação': '6063',
                   'Auxílio-Funeral': '10248',
                   'Auxílio-Natalidade': '10246',
                   'Auxílio-Reclusão': '10247',
                   'Auxílio-transporte': '10306',
                   'Complementação de Benefício/Ferroviário': '10243',
                   'Data Base': '10300',
                   'Descontos Indevidos': '10296',
                   'Diárias e Outras Indenizações': '10298',
                   'Gratificação de Incentivo': '10290',
                   'Gratificação Incorporada / Quintos e Décimos / VPNI': '10295',
                   'Gratificação Natalina/13º salário': '10310',
                   'Gratificações da Lei 8.112/1990': '10289',
                   'Gratificações de Atividade': '10305',
                   'Irredutibilidade de Vencimentos': '10311',
                   'Isonomia/Equivalência Salarial': '10221',
                   'Piso Salarial': '10312',
                   'Plano de Classificação de Cargos': '10299',
                   'Recebimento de bolsa de estudos': '11858',
                   'Revisão Geral Anual (Mora do Executivo - inciso X, art. 37, CF 1988)': '10307',
                   'Salário-Família': '10249',
                   'Subsídios': '10497',
                   'Teto Salarial': '10297',
                   'Averbação / Contagem de Tempo Especial': '10277',
                   'Averbação / Contagem Recíproca': '10278',
                   'Sistema de proteção especial a vítimas e a testemunhas': '11872',
                   'Sistema Nacional de Trânsito': '10417',
                   'CNH - Carteira Nacional de Habilitação': '10418',
                   'Liberação de Veículo Apreendido': '6028',
                   'Licenciamento de Veículo': '10420',
                   'DIREITO CIVIL': '899',
                   'Coisas': '10432',
                   'Conflito fundiário coletivo rural': '11412',
                   'Conflito fundiário coletivo urbano': '11413',
                   'Hipoteca': '10494',
                   'Penhor': '10488',
                   'Direitos e Títulos de Crédito': '10491',
                   'Industrial / Mercantil': '10490',
                   'Rural - Agrícola/Pecuário': '10489',
                   'Veículos': '10492',
                   'Posse': '10444',
                   'Aquisição': '6193',
                   'Esbulho / Turbação / Ameaça': '10445',
                   'Imissão': '10446',
                   'Propriedade': '10448',
                   'Acessão': '10456',
                   'Usucapião da L 6.969/1981': '10500',
                   'Usucapião Especial (Constitucional)': '10457',
                   'Usucapião Especial Coletiva': '10460',
                   'Usucapião Extraordinária': '10458',
                   'Usucapião Ordinária': '10459',
                   'Condomínio': '10462',
                   'Condomínio em Edifício': '10463',
                   'Multa': '10595',
                   'Perda da Propriedade': '10449',
                   'Propriedade Intelectual / Industrial': '4654',
                   'Desenho Industrial': '4670',
                   'Direito Autoral': '4656',
                   'Marca': '4680',
                   'Patente': '4660',
                   'Programa de Computador': '10499',
                   'Família': '5626',
                   'Bem de Família': '7661',
                   'Fatos Jurídicos': '7947',
                   'Prescrição e Decadência': '5632',
                   'Obrigações': '7681',
                   'Adimplemento e Extinção': '7690',
                   'Compensação': '5994',
                   'Confusão': '7710',
                   'Dação em Pagamento': '7707',
                   'Desconto em folha de pagamento': '10592',
                   'Imputação do Pagamento': '7706',
                   'Novação': '7708',
                   'Pagamento': '7703',
                   'Pagamento com Sub-rogação': '7705',
                   'Pagamento em Consignação': '7704',
                   'Remissão das Dívidas': '7711',
                   'Atos Unilaterais': '7694',
                   'Enriquecimento sem Causa': '7715',
                   'Gestão de Negócios': '7713',
                   'Pagamento Indevido': '7714',
                   'Promessa de Recompensa': '7712',
                   'Espécies de Contratos': '9580',
                   'Agêncie e Distribuição': '9581',
                   'Alienação Fiduciária': '9582',
                   'Arrendamento Mercantil': '9584',
                   'Arrendamento Rural': '9583',
                   'Câmbio': '4728',
                   'Cartão de Crédito': '7772',
                   'Comissão': '9586',
                   'Comodato': '9602',
                   'Compra e Venda': '9587',
                   'Compromisso': '9606',
                   'Constituição de Renda': '9604',
                   'Contratos Bancários': '9607',
                   'Corretagem': '9588',
                   'Crédito Rural': '10501',
                   'Depósito': '9589',
                   'Doação': '9590',
                   'Edição': '5680',
                   'Empreitada': '9591',
                   'Estimatório': '9601',
                   'Fiança': '4310',
                   'Franquia': '9608',
                   'Jogo e Aposta': '9605',
                   'Locação de Imóvel': '9593',
                   'Benfeitorias': '9614',
                   'Despejo para Uso de Ascendentes e Descendentes': '9611',
                   'Despejo para Uso Próprio': '9610',
                   'Despejo por Denúncia Vazia': '9612',
                   'Direito de Preferência': '9615',
                   'Locação de Móvel': '9609',
                   'Mandato': '9594',
                   'Mútuo': '9603',
                   'Parceria Agrícola e/ou pecuária': '4794',
                   'Prestação de Serviços': '9596',
                   'Previdência privada': '4805',
                   'Resgate de Contribuição': '10590',
                   'Representação comercial': '4813',
                   'Seguro': '7621',
                   'Sistema Financeiro da Habitação': '4839',
                   'Equivalência salarial': '4840',
                   'Programas de Arrendamento Residencial PAR': '11804',
                   'Quitação': '4841',
                   'Reajuste de Prestações': '4842',
                   'Revisão do Saldo Devedor': '4854',
                   'Sustação/Alteração de Leilão': '4846',
                   'Tabela Price': '11805',
                   'Transferência de Financiamento (contrato de gaveta)': '4843',
                   'Vícios de Construção': '10588',
                   'Transação': '10630',
                   'Transporte de Coisas': '9599',
                   'Transporte de Pessoas': '9600',
                   'Troca ou Permuta': '9595',
                   'Espécies de Títulos de Crédito': '7717',
                   'Cédula de Crédito à Exportação': '4961',
                   'Cédula de Crédito Bancário': '4960',
                   'Cédula de Crédito Comercial': '4962',
                   'Cédula de Crédito Industrial': '4963',
                   'Cédula de Crédito Rural': '4964',
                   'Cédula de Produto Rural': '4968',
                   'Cédula Hipotecária': '4969',
                   'Cheque': '4970',
                   'Debêntures': '4971',
                   'Duplicata': '4972',
                   'Letra de Câmbio': '4973',
                   'Nota de Crédito Comercial': '4974',
                   'Nota de Crédito Industrial': '4975',
                   'Nota de Crédito Rural': '4976',
                   'Nota Promissória': '4980',
                   'Warrant': '4981',
                   'Inadimplemento': '7691',
                   'Arras ou Sinal': '7701',
                   'Cláusula Penal': '7700',
                   'Correção Monetária': '10685',
                   'Juros de Mora - Legais / Contratuais': '7699',
                   'Capitalização / Anatocismo': '10585',
                   'Limitação de Juros': '10586',
                   'Perdas e Danos': '7698',
                   'Rescisão / Resolução': '10582',
                   'Preferências e Privilégios Creditórios': '7696',
                   'Títulos de Crédito': '4949',
                   'Requisitos': '4957',
                   'Sustação de Protesto': '9575',
                   'Transmissão': '7688',
                   'Assunção de Dívida': '7689',
                   'Cessão de Crédito': '4718',
                   'Responsabilidade Civil': '10431',
                   'Dano Ambiental': '10438',
                   'Acidente de Trabalho - Ressarcimento ao Erário': '11954',
                   'Direito de Imagem': '10437',
                   'Lei de Imprensa': '10436',
                   'DIREITO DA CRIANÇA E DO ADOLESCENTE': '9633',
                   'Seção Cível': '9964',
                   'Classificação indicativa': '11819',
                   'Conselhos tutelares': '11821',
                   'Entidades de atendimento': '11820',
                   'Fundos': '11817',
                   'Infrações administrativas': '11816',
                   'Medidas de proteção': '11818',
                   'Perda ou Modificação de Guarda': '12090',
                   'DIREITO DO CONSUMIDOR': '1156',
                   'Cláusulas Abusivas': '11974',
                   'Combustíveis e derivados': '11861',
                   'Contratos de Consumo': '7771',
                   'Bancários': '7752',
                   'Empréstimo consignado': '11806',
                   'Tarifas': '11807',
                   'Capitalização e Previdência Privada': '11808',
                   'Consórcio': '7619',
                   'Estabelecimentos de Ensino': '7620',
                   'Financiamento de Produto': '7773',
                   'Fornecimento de Água': '7761',
                   'Fornecimento de Energia Elétrica': '7760',
                   'Planos de Saúde': '6233',
                   'Fornecimento de medicamentos': '12222',
                   'Reajuste contratual': '12225',
                   'Tratamento médico-hospitalar': '12223',
                   'Unidade de terapia intensiva (UTI) ou Unidade de cuidados intensivos (UCI)': '12224',
                   'Produto Impróprio': '11867',
                   'Serviços Hospitalares': '7775',
                   'Serviços Profissionais': '7774',
                   'Assinatura Básica Mensal': '7626',
                   'Cobrança indevida de ligações': '10598',
                   'Pulsos Excedentes': '7627',
                   'Transporte Aéreo': '4862',
                   'Acidente Aéreo': '7748',
                   'Atraso de vôo': '4829',
                   'Cancelamento de vôo': '4830',
                   'Extravio de bagagem': '4832',
                   'Overbooking': '4831',
                   'Transporte Ferroviário': '11814',
                   'Transporte Rodoviário': '11815',
                   'Turismo': '7618',
                   'Dever de Informação': '11810',
                   'Irregularidade no atendimento': '11864',
                   'Jogos / Sorteios / Promoções comerciais': '11866',
                   'Oferta e Publicidade': '11812',
                   'Práticas Abusivas': '11811',
                   'Responsabilidade do Fornecedor': '6220',
                   'Abatimento proporcional do preço': '7769',
                   'Inclusão Indevida em Cadastro de Inadimplentes': '6226',
                   'Protesto Indevido de Título': '7781',
                   'Interpretação / Revisão de Contrato': '7770',
                   'Rescisão do contrato e devolução do dinheiro': '7768',
                   'Substituição do Produto': '7767',
                   'Vendas casadas': '11865',
                   'DIREITO INTERNACIONAL': '6191',
                   'Contratos Internacionais': '6219',
                   'Cooperação Internacional': '6203',
                   'Auxílio Direto': '6206',
                   'Mercosul': '6207',
                   'Repatriação de Criança ou Adolescente': '10921',
                   'Estrangeiro': '6197',
                   'Admissão / Entrada / Permanência / Saída': '6198',
                   'Asilo': '6199',
                   'Livre Trânsito MERCOSUL': '6200',
                   'Trabalhador Migrante ou Fronteiriço do MERCOSUL': '6201',
                   'Funcionamento de Empresa Estrangeira': '6217',
                   'Laudo Arbitral Internacional': '9565',
                   'Nacionalidade': '6192',
                   'Cancelamento de Naturalização': '6196',
                   'Concessão de Naturalização': '6195',
                   'Perda': '6194',
                   'Normas do Mercosul': '6213',
                   'Pessoa Jurídica Estrangeira': '6218',
                   'Prestação de Alimentos': '6216',
                   'Proteção Internacional a Direitos Humanos': '6202',
                   'Tratado Internacional': '6212',
                   'DIREITO MARÍTIMO': '1146',
                   'Inscrição / Registro da Embarcação': '5603',
                   'Registro / Cadastro do Armador': '5585',
                   'Responsabilidade Contratual': '7783',
                   'Aluguel de Embarcações (Fretamento E Carta Partida)': '5196',
                   'Créditos / Privilégios Marítimos': '5612',
                   'Engajamento e Profissionais Marítimos': '5193',
                   'Hipoteca Marítima': '5609',
                   'Quanto à Carga': '7798',
                   'Quanto à Embarcação': '7797',
                   'Seguros Marítimos': '5194',
                   'Responsabilidade do Comandante ou Capitão': '5595',
                   'Responsabilidade Extracontratual': '7784',
                   'Abandono': '5575',
                   'Acidentes da Navegação': '5577',
                   'Arresto de Embarcação': '5589',
                   'Assistência / Salvamento': '5591',
                   'Avaria': '5592',
                   'Clandestinos': '7799',
                   'Serviços Auxiliares da Navegação': '5621',
                   'Agenciamento': '5622',
                   'Corretagem de Embarcação': '5623',
                   'Praticagem': '5624',
                   'DIREITO PENAL': '287',
                   'Contravenções Penais': '3692',
                   'Fabrico, comércio ou detenção de arma branca ou munição': '12343',
                   'Jogo de azar': '12350',
                   'Jogo do bicho': '12352',
                   'Loteria não autorizada': '12351',
                   'Omissão de cautela na guarda ou condução de animal': '12346',
                   'Omissão de comunicação de crime': '12355',
                   'Perturbação da tranquilidade': '12354',
                   'Perturbação do trabalho ou do sossego alheios': '12347',
                   'Porte de arma (branca)': '12344',
                   'Provocação de tumulto ou conduta inconveniente': '12340',
                   'Recusa de dados sobre a própria identificação ou qualificação': '12356',
                   'Servir bebidas alcóolicas a vulneráveis': '12353',
                   'Simulação de Qualidade de Funcionário': '12348',
                   'Uso ilegítimo de uniforme ou distintivo': '12349',
                   'Vias de fato': '12345',
                   'Crime / Contravenção contra Criança / Adolescente': '10950',
                   'Crime / Contravenção contra Idoso': '10951',
                   'Crime Culposo': '5865',
                   'Crime Tentado': '5555',
                   'Crime/contravenção decorrente de conflito fundiário coletivo': '11414',
                   'Crimes cometidos contra autoridade ou agente descrito nos arts. 142 e 143 da Constituição Federal, integrantes do sistema prisional e da Força Nacional de Segurança Pública': '12342',
                   'Crimes Contra a Administração da Justiça': '5874',
                   'Arrebatamento de preso': '3588',
                   'Auto-acusação falsa': '3578',
                   'Coação no curso do processo': '3580',
                   'Comunicação falsa de crime ou de contravenção': '3577',
                   'Denunciação caluniosa': '3576',
                   'Desobediência a decisão judicial sobre perda ou suspensão de direitos': '3595',
                   'Evasão mediante violência contra a pessoa': '3587',
                   'Exercício arbitrário das próprias razões': '3581',
                   'Exercício arbitrário ou abuso de poder': '3585',
                   'Exploração de prestígio': '3593',
                   'Falso testemunho ou falsa perícia': '3579',
                   'Favorecimento pessoal': '3583',
                   'Favorecimento real': '3584',
                   'Fraude processual': '3582',
                   'Fuga de pessoa presa ou submetida a medida de segurança': '3586',
                   'Motim de presos': '3589',
                   'Patrocínio infiel': '3590',
                   'Patrocínio simultâneo ou tergiversação': '3591',
                   'Reingresso de estrangeiro expulso': '3575',
                   'Sonegação de papel ou objeto de valor probatório': '3592',
                   'Violência ou fraude em arrematação judicial': '3594',
                   'Crimes contra a Dignidade Sexual': '3463',
                   'Assédio Sexual': '5851',
                   'Atentado ao Pudor Mediante Fraude': '3467',
                   'Atentado Violento ao Pudor': '3466',
                   'Casa de Prostituição': '5853',
                   'Corrupção de Menores': '3468',
                   'Estupro': '3465',
                   'Estupro de vulnerável': '11417',
                   'Favorecimento da Prostituição': '5852',
                   'Favorecimento da prostituição ou outra forma de exploração sexual': '11420',
                   'Favorecimento da prostituição ou outra forma de exploração sexual de vulnerável': '11419',
                   'Mediação para Servir a Lascívia de Outrem': '3471',
                   'Posse Sexual Mediante Fraude': '5850',
                   'Rufianismo': '5854',
                   'Satisfação de lascívia mediante presença de criança ou adolescente': '11418',
                   'Tráfico internacional de pessoa para fim de exploração sexual': '11421',
                   'Tráfico Internacional de Pessoas': '5855',
                   'Tráfico interno de pessoa para fim de exploração sexual': '11422',
                   'Tráfico Interno de Pessoas': '5856',
                   'Ultraje Público ao Pudor (Ato/Escrito Obsceno)': '3469',
                   'Violação sexual mediante fraude': '11416',
                   'Crimes contra a Família': '3472',
                   'Crime contra o Pátrio-Poder e Tutela': '3488',
                   'Induzimento a Fuga, Entrega Arbitrária ou Sonegação de Incapazes': '3489',
                   'Subtração de Incapazes': '3490',
                   'Crimes Contra a Assistência Familiar': '3473',
                   'Abandono Intelectual': '3475',
                   'Abandono Material': '3474',
                   'Entrega de Filho Menor a Pessoa Inidônea': '3476',
                   'Crimes contra o Casamento': '3477',
                   'Bigamia': '3479',
                   'Conhecimento Prévio de Impedimento': '3480',
                   'Induzimento a erro essencial e ocultação de impedimento': '3481',
                   'Simulação de Autoridade para Celebração de Casamento': '3483',
                   'Simulação de Casamento': '3482',
                   'Crimes Contra o Estado de Filiação': '3484',
                   'Parto Suposto': '3485',
                   'Registro de Nascimento Inexistente': '3486',
                   'Sonegação do Estado de Filiação': '3487',
                   'Crimes contra a Fé Pública': '3523',
                   'Adulteração de Sinal Identificador de Veículo Automotor': '3546',
                   'Adulteração de Sinal Identificador de Veículo Automotor por Funcionário Público': '10992',
                   'Certidão ou atestado ideologicamente falso': '3535',
                   'Crime de Desvio e/ou Circulação de Moeda Não Autorizada': '11006',
                   'Crime de Moeda Falsa Praticado por Funcionário Público': '11007',
                   'Emissão de título ao portador sem permissão legal': '3528',
                   'Falsa identidade': '3542',
                   'Falsidade de atestado médico': '3537',
                   'Falsidade ideológica': '3533',
                   'Falsidade ideológica praticada por Funcionário Público': '10995',
                   'Falsidade material de atestado ou certidão': '3536',
                   'Falsificação de documento particular': '3532',
                   'Falsificação de documento público': '3531',
                   'Falsificação de documento Público praticada por Funcionário Público': '10998',
                   'Falsificação de papéis públicos': '3529',
                   'Falsificação de Papéis Públicos Praticado por Funcionário Público': '11005',
                   'Falsificação do selo ou sinal público': '3530',
                   'Falsificação do Selo ou Sinal Público Praticado por Funcionário Público': '11004',
                   'Falsificação do sinal empregado no contraste de metal precioso ou na fiscalização alfandegária, ou para outros fins': '3541',
                   'Falso reconhecimento de firma ou letra': '3534',
                   'Fraude de lei sobre estrangeiros': '3543',
                   'Moeda Falsa / Assimilados': '3524',
                   'Petrechos de Falsificação de Papéis Públicos': '3545',
                   'Petrechos de Falsificação de Papéis Públicos por Funcionário Público': '10993',
                   'Petrechos para falsificação de moeda': '3527',
                   'Petrechos para falsificação de moeda por Funcionário Público': '10994',
                   'Reprodução ou adulteração de selo ou peça filatélica': '3538',
                   'Supressão de documento': '3540',
                   'Uso de documento falso': '3539',
                   'Crimes contra a Honra': '3394',
                   'Calúnia': '3395',
                   'Difamação': '3396',
                   'Injúria': '3397',
                   'Crimes contra a Incolumidade Pública': '3491',
                   'Arremesso de projétil': '3502',
                   'Atentado contra a segurança de serviços de utilidade pública': '3503',
                   'Atentado contra a segurança de transporte público': '3501',
                   'Charlatanismo': '3510',
                   'Corrupção ou Poluição de Água Potável': '3511',
                   'Curandeirismo': '3512',
                   'Desabamento ou desmoronamento': '3496',
                   'Desabamento ou desmoronamento culposo': '11969',
                   'Desastre ferroviário / Perigo de Desastre Ferroviário': '3500',
                   'Desastre ferroviário culposo': '11972',
                   'Difusão de doença ou praga': '3498',
                   'Emprego de Processo Proibido/Substância não permitida': '3506',
                   'Envenenamento de Água Potável / Substância Alimentícia ou Medicinal': '3513',
                   'Epidemia': '3505',
                   'Exercício Ilegal da Medicina, Arte Dentária ou Farmacêutica': '3509',
                   'Explosão': '3493',
                   'Explosão culposa': '11963',
                   'Fabrico / Fornecimento / Aquisição / Posse ou Transporte de Explosivos ou Gás Tóxico ou Asfixiante': '5862',
                   'Falsificação / Corrupção / Adulteração / Alteração de produto destinado a fins terapêuticos ou medicinais': '3508',
                   'Falsificação / Corrupção / Adulteração / Alteração de Substância ou Produtos Alimentícios': '3514',
                   'Incêndio': '3492',
                   'Incêndio culposo': '11961',
                   'Infração de Medida Sanitária Preventiva': '3515',
                   'Interrupção /perturbação de serviços telegráficos/telefônicos': '3504',
                   'Inundação / Perigo de Inundação': '3495',
                   'Inundação culposa': '11967',
                   'Invólucro ou recipiente com falsa indicação': '3507',
                   'Medicamento em Desacordo com Receita Médica': '5867',
                   'Omissão de Notificação de Doença': '3516',
                   'Outras Substâncias Nocivas a Saúde Pública': '3517',
                   'Substância Destinada à Falsificação': '3519',
                   'Subtração, ocultação ou inutilização de material de salvamento': '3497',
                   'Uso culposo de gás tóxico ou asfixiante': '11966',
                   'Uso de gás tóxico ou asfixiante': '3494',
                   'Venda de Produtos ou Substância nas Condições dos Artigos 274 e 275': '5866',
                   'Crimes contra a inviolabilidade de correspondência': '3407',
                   'Sonegação ou destruição de correspondência': '3409',
                   'Violação de comunicação telegráfica, radioelétrica ou telefônica': '3410',
                   'Violação de correspondência': '3408',
                   'Violação de Correspondência comercial': '3411',
                   'Crimes contra a inviolabilidade de domicílio': '3405',
                   'Violação de domicílio': '3406',
                   'Crimes contra a inviolabilidade de segredo': '3412',
                   'Divulgação de segredo': '3413',
                   'Invasão de Dispositivo Informático': '11978',
                   'Violação do segredo profissional': '3414',
                   'Crimes contra a liberdade pessoal': '3400',
                   'Ameaça': '3402',
                   'Constrangimento ilegal': '3401',
                   'Redução a condição análoga à de escravo': '3404',
                   'Seqüestro e cárcere privado': '3403',
                   'Crimes contra a Organização do Trabalho': '3445',
                   'Aliciamento de trabalhadores de um local para outro do território nacional': '3455',
                   'Aliciamento para fins de emigração': '3454',
                   'Atentado contra a liberdade de associação': '3448',
                   'Atentado contra a liberdade de contrato de trabalho e boicotagem violenta': '3447',
                   'Atentado contra a liberdade de trabalho': '3446',
                   'Exercício de atividade com infração de decisão administrativa': '3453',
                   'Frustração de direitos assegurados por lei trabalhista': '3452',
                   'Frustração de lei sobre a nacionalização do trabalho': '3456',
                   'Invasão de estabelecimento industrial, comercial ou agrícola. Sabotagem': '3451',
                   'Paralisação de trabalho de interesse coletivo': '3450',
                   'Paralisação de trabalho, seguida de violência ou perturbação da ordem': '3449',
                   'Crimes contra a Paz Pública': '3520',
                   'Apologia de Crime ou Criminoso': '5870',
                   'Incitação ao Crime': '5869',
                   'Quadrilha ou Bando': '3521',
                   'Crimes contra a Propriedade Intelectual': '3442',
                   'Violação de direito autoral': '3443',
                   'Crimes contra a vida': '3369',
                   'Aborto': '10915',
                   'Aborto provocado pela gestante ou com o seu consentimento': '10917',
                   'Aborto provocado por terceiro': '10918',
                   'Aborto qualificado': '10919',
                   'Homicídio Agravado pela Prática de Extermínio de Seres Humanos': '12130',
                   'Homicídio Privilegiado': '3371',
                   'Homicídio Qualificado': '3372',
                   'Homicídio Simples': '3370',
                   'Induzimento, Instigação ou Auxílio a Suicídio': '3373',
                   'Infanticídio': '3375',
                   'Crimes Contra as Finanças Públicas': '5875',
                   'Assunção de Obrigação no Último Ano do Mandato ou Legislatura': '5905',
                   'Aumento de Despesa com Pessoal no Último Ano do Mandato ou Legislatura': '5909',
                   'Contratação de Operação de Crédito': '5903',
                   'Corrupção Praticada por Prefeitos e Vereadores': '10991',
                   'Inscrição de Despesas Não Empenhadas': '5904',
                   'Má-gestão praticada por Prefeitos e Vereadores': '10990',
                   'Não Cancelamento de Restos a Pagar': '5908',
                   'Oferta Pública ou Colocação de Títulos no Mercado': '5910',
                   'Ordenação de Despesa Não Autorizada': '5906',
                   'Prestação de Garantia Graciosa': '5907',
                   'Crimes contra o Patrimônio': '3415',
                   'Abuso de Incapazes': '5842',
                   'Alienação ou Oneração Fraudulenta de Coisa Própria': '5836',
                   'Alteração de limites': '3423',
                   'Alteração de local especialmente protegido': '3429',
                   'Apropriação de Coisa Achada': '5573',
                   'Apropriação de Coisa Havida por Erro, Caso Fortuito ou Força da Natureza': '3437',
                   'Apropriação de Tesouro': '5572',
                   'Apropriação indébita': '3436',
                   'Apropriação indébita Previdenciária': '3430',
                   'Dano': '3426',
                   'Dano em coisa de valor artístico, arqueológico ou histórico': '3428',
                   'Dano Qualificado': '5571',
                   'Defraudação de Penhor': '5837',
                   'Disposição de coisa alheia como própria': '5835',
                   'Duplicata Simulada': '5841',
                   'Emissão Irregular de Conhecimento de Depósito ou "Warrant"': '5846',
                   'Esbulho possessório': '3425',
                   'Estelionato': '3431',
                   'Estelionato Majorado': '3432',
                   'Extorsão': '3420',
                   'Extorsão indireta': '3422',
                   'Extorsão mediante Sequestro Seguida de Lesão Corporal Grave': '5569',
                   'Extorsão mediante seqüestro': '3421',
                   'Extorsão mediante Seqüestro Seguida de Morte': '5568',
                   'Fraude à execução': '3434',
                   'Fraude na Entrega de Coisa': '5838',
                   'Fraude no Comércio': '5844',
                   'Fraude no Pagamento por Meio de Cheque': '5840',
                   'Fraude para Recebimento de Indenização ou Valor de Seguro': '5839',
                   'Fraudes e Abusos na Fundação ou Administração de Sociedade por Ações': '5845',
                   'Furto': '3416',
                   'Furto de coisa comum': '3418',
                   'Furto de Veículo Automotor a ser Transportado para outro Estado ou Exterior': '5565',
                   'Furto Privilegiado': '5564',
                   'Furto Qualificado': '3417',
                   'Induzimento à Especulação': '5843',
                   'Introdução ou abandono de animais em propriedade alheia': '3427',
                   'Latrocínio': '5567',
                   'Outras fraudes': '3433',
                   'Receptação': '3435',
                   'Receptação culposa': '11959',
                   'Receptação Qualificada': '5847',
                   'Roubo': '3419',
                   'Roubo Majorado': '5566',
                   'Supressão ou Alteração de Marca em Animais': '5570',
                   'Usurpação de águas': '3424',
                   'Crimes contra o sentimento religioso e contra o respeito aos mortos': '3457',
                   'Destruição / Subração / Ocultação de Cadáver': '3458',
                   'Impedimento ou Perturbação de Cerimônia Funerária': '3459',
                   'Ultraje / Impedimento ou Perturbação de Culto Religioso': '3462',
                   'Vilipêndio a Cadáver': '3460',
                   'Violação a Sepultura': '3461',
                   'Crimes Praticados por Funcionários Públicos Contra a Administração em Geral': '3547',
                   '"Lavagem" ou Ocultação de Bens, Direitos ou Valores Oriundos de Corrupção': '10984',
                   'Abandono de função': '3561',
                   'Advocacia administrativa': '3559',
                   'Concussão': '3553',
                   'Condescendência criminosa': '3558',
                   'Corrupção passiva': '3555',
                   'Emprego irregular de verbas ou rendas públicas': '3552',
                   'Excesso de exação': '3554',
                   'Exercício funcional ilegalmente antecipado ou prolongado': '3562',
                   'Extravio, sonegação ou inutilização de livro ou documento': '3551',
                   'Facilitação de contrabando ou descaminho': '3556',
                   'Inserção de dados falsos em sistema de informações': '3596',
                   'Modificação ou alteração não autorizada de sistema de informações': '3597',
                   'Peculato': '3548',
                   'Peculato mediante erro de outrem': '3550',
                   'Prevaricação': '3557',
                   'Violação do sigilo de proposta de concorrência': '3564',
                   'Violação do sigilo funcional': '3563',
                   'Violência arbitrária': '3560',
                   'Crimes Praticados por Particular Contra a Administração em Geral': '5872',
                   'Contrabando ou descaminho': '3574',
                   'Corrupção ativa': '3568',
                   'Desacato': '3573',
                   'Desobediência': '3572',
                   'Impedimento, perturbação ou fraude de concorrência': '3569',
                   'Inutilização de edital ou de sinal': '3570',
                   'Resistência': '3566',
                   'Sonegação de contribuição previdenciária': '3598',
                   'Subtração ou inutilização de livro ou documento': '3571',
                   'Tráfico de influência': '3567',
                   'Usurpação de função pública': '3565',
                   'Crimes Praticados por Particular Contra a Administração Pública Estrangeira': '5873',
                   'Corrupção Ativa em Transação Comercial Internacional': '5876',
                   'Tráfico de Influência em Transação Comercial Internacional': '5877',
                   'Crimes Previstos na Legislação Extravagante': '3603',
                   'Crime Contra a Administração da Justiça - Lei da Ação de Alimentos': '5893',
                   'Crime de Quebra de Sigilo Financeiro': '3655',
                   'Crimes Agrários': '3651',
                   'Crimes contra a Economia Popular': '3605',
                   'Crimes contra a Ordem Econômica': '3615',
                   'Crimes contra a Ordem Tributária': '3614',
                   'Crimes contra a Ordem Tributária praticado por Funcionário Público': '10985',
                   'Crimes contra a Propriedade Industrial': '3438',
                   'Crimes Cometidos por Meio de Marca, Título de Estabelecimento e Sinal de Propaganda': '5881',
                   'Crimes contra as Marcas': '5880',
                   'Crimes contra Indicações Geeográficas e Demais Indicações': '5882',
                   'Crimes contra os Desenhos Industriais': '5879',
                   'Crimes contra Patente de Invenção': '5878',
                   'Crimes de Concorrência Desleal': '5883',
                   'Crimes contra a Segurança Nacional, a Ordem Política e Social': '3611',
                   'Crimes contra as Relações de Consumo': '3616',
                   'Crimes contra as Telecomunicações': '3629',
                   'Crimes contra o Meio Ambiente e o Patrimônio Genético': '3618',
                   'Atividades Nucleares': '3623',
                   'Caça': '3624',
                   'Clonagem Humana': '10516',
                   'Crime contra a administração ambiental': '10986',
                   'Crimes contra a Fauna': '3619',
                   'Crimes contra a Flora': '3620',
                   'Crimes contra o Ordenamento Urbano e o Patrimônio Cultural': '11780',
                   'Da Poluição': '3621',
                   'Liberação ou Descarte de OGM (Organismo Geneticamente Modificado)': '3626',
                   'Pesca': '3627',
                   'Prática de engenharia genética em célula germinal, zigoto ou embrião humanos': '10515',
                   'Utilização de Embrião Humano em Desacordo com a Legislação': '10514',
                   'Crimes contra o mercado de capitais': '3638',
                   'Crimes contra o Serviço Postal e o Serviço de Telegrama': '3610',
                   'Crimes contra o Sistema Financeiro Nacional': '3612',
                   'Crimes da Lei de licitações': '3642',
                   'Crimes da Lei de remoção de órgãos e tecidos': '3643',
                   'Crimes de "Lavagem" ou Ocultação de Bens, Direitos ou Valores': '3628',
                   'Crimes de Abuso de Autoridade': '3606',
                   'Crimes de genocídio': '3640',
                   'Crimes de Imprensa': '3634',
                   'Crimes de Responsabilidade': '3604',
                   'Crimes de Tortura': '3631',
                   'Crimes de Tráfico Ilícito e Uso Indevido de Drogas': '3607',
                   'Associação para a Produção e Tráfico e Condutas Afins': '5897',
                   'Colaboração com Grupo, Organização ou Associação Destinados à Produção ou Tráfico de Drogas': '5899',
                   'Condução de Embarcação ou Aeronave sob Efeito de Drogas': '5901',
                   'Fabricação de Objeto Destinado a Produção de Drogas e Condutas Afins': '5894',
                   'Financiamento ou Custeio de Produção ou Tráfico de Drogas': '5898',
                   'Indução, Instigação ou Auxílio ao Uso de Drogas': '5895',
                   'Oferecimento de Drogas para Consumo Conjunto': '5896',
                   'Posse de Drogas para Consumo Pessoal': '5885',
                   'Prescrição Culposa de Drogas': '5900',
                   'Tráfico de Drogas e Condutas Afins': '3608',
                   'Tráfico Ilícito de Drogas praticado por Funcionário Público': '10987',
                   'Crimes de Trânsito': '3632',
                   'Crimes do Código Brasileiro de Telecomunicações': '3656',
                   'Crimes do Sistema Nacional de Armas': '3633',
                   'Crimes Falimentares': '3661',
                   'Crimes Militares': '3664',
                   'Crimes praticados contra os índios e a cultura indígena': '3647',
                   'Crimes Previstos na Lei de Estrangeiros': '3630',
                   'Crimes Previstos no Estatuto da criança e do adolescente': '3637',
                   'Crimes Previstos no Estatuto do Idoso': '3659',
                   'Crimes relacionados à Comissão Parlamentar de Inquérito': '3653',
                   'Crimes Resultante de Preconceito de Raça ou de Cor': '3613',
                   'Parcelamento do solo urbano': '3660',
                   'Recusa, retardamento ou omissão de dados técnicos indispensáveis à propositura de Ação Civil Pública': '3650',
                   'Representação caluniosa': '3617',
                   'Responsabilidade Criminal por Danos Nucleares': '3609',
                   'Sigilo Telefônico': '3641',
                   'Crimes previstos na Lei da Organização Criminosa': '12333',
                   'Crimes ocorridos na investigação da prova': '12335',
                   'Descumprimento de determinação de sigilo': '12338',
                   'Imputação falsa de prática de infração penal ou revelação inverídica sobre estrutura de organização criminal': '12337',
                   'Recusa ou omissão de dados cadastrais, registros, documentos e informações': '12339',
                   'Revelação de identidade, fotografia ou filmagem do colaborador': '12336',
                   'Promoção, constituição, financiamento ou integração de Organização Criminosa': '12334',
                   'Fato Atípico': '10952',
                   'Lesão Corporal': '3385',
                   'Grave': '5556',
                   'Gravíssima': '5557',
                   'Leve': '3386',
                   'Privilegiada': '5558',
                   'Seguida de Morte': '3387',
                   'Parte Geral': '10620',
                   'Aplicação da Pena': '10621',
                   'Regime inicial': '10633',
                   'Substituição da Pena': '10628',
                   'Efeitos da Condenação': '10642',
                   'Perda da Função Pública': '10643',
                   'Perda de Bens e Valores': '7786',
                   'Excludentes': '10613',
                   'Estado de Necessidade': '10617',
                   'Estrito Cumprimento do Dever Legal': '10618',
                   'Inexigibilidade de Conduta Diversa': '10619',
                   'Legítima Defesa': '10616',
                   'Extinção da Punibilidade': '10622',
                   'Anistia': '5996',
                   'Indulto': '10626',
                   'Pagamento ou Parcelamento do Crédito Tributário': '10627',
                   'Perdão': '10624',
                   'Prescrição': '5992',
                   'Suspensão condicional da pena': '10634',
                   'Tipicidade': '10612',
                   'Abolitio Criminis': '10614',
                   'Princípio da Insignificância': '10615',
                   'Periclitação da Vida e da Saúde e Rixa': '3388',
                   'Abandono de incapaz': '3391',
                   'Exposição ou Abandono de Recém Nascido': '10509',
                   'Maus Tratos': '10508',
                   'Omissão de socorro': '3392',
                   'Perigo de contágio de moléstia grave': '3389',
                   'Perigo de Contágio Venéreo': '5911',
                   'Perigo para a vida ou saúde de outrem': '3390',
                   'Rixa': '3393',
                   'Terrorismo': '12217',
                   'Atos de Terrorismo': '12218',
                   'Manutenção ou financiamento do terrorismo': '12221',
                   'Organização Terrorista': '12219',
                   'Preparação de ato terrorista': '12220',
                   'Violência Doméstica Contra a Mulher': '10949',
                   'DIREITO PREVIDENCIÁRIO': '195',
                   'Benefícios em Espécie': '6094',
                   'Abono de Permanência em Serviço (Art. 87)': '6113',
                   'Aposentadoria Especial (Art. 57/8)': '6100',
                   'Aposentadoria por Idade (Art. 48/51)': '6096',
                   'Rural (Art. 48/51)': '6098',
                   'Urbana (Art. 48/51)': '6097',
                   'Aposentadoria por Invalidez': '6095',
                   'Aposentadoria por Invalidez Acidentária': '10567',
                   'Aposentadoria por Tempo de Contribuição (Art. 55/6)': '6118',
                   'Aposentadoria por Tempo de Serviço (Art. 52/4)': '6099',
                   'Auxílio-Acidente (Art. 86)': '6107',
                   'Incapacidade Laborativa Parcial': '6108',
                   'Incapacidade Laborativa Permanente': '6109',
                   'Incapacidade Laborativa Temporária': '6110',
                   'Movimentos Repetitivos/Tenossinovite/LER/DORT': '6111',
                   'Redução da Capacidade Auditiva': '6112',
                   'Auxílio-Doença Acidentário': '7757',
                   'Auxílio-Doença Previdenciário': '6101',
                   'Auxílio-Reclusão (Art. 80)': '6105',
                   'Benefício Assistencial (Art. 203,V CF/88)': '6114',
                   'Deficiente': '11946',
                   'Ferroviário': '6115',
                   'Pecúlios (Art. 81/5)': '6106',
                   'Pensão por Morte (Art. 74/9)': '6104',
                   'Renda Mensal Vitalícia': '6117',
                   'Salário-Família (Art. 65/70)': '6102',
                   'Salário-Maternidade (Art. 71/73)': '6103',
                   'Seguro-defeso ao pescado artesanal profissional': '12216',
                   'Disposições Diversas Relativas às Prestações': '6160',
                   'Atividade concomitante': '6165',
                   'Decadência/Prescrição': '6162',
                   'Declaração de Ausência': '6164',
                   'Demonstrativo das importâncias pagas': '6167',
                   'Habilitação e Reabilitação Profissional': '6161',
                   'Limite Mínimo de Idade': '6169',
                   'Perda da qualidade de segurado': '6170',
                   'Períodos de Carência': '6168',
                   'Regra de Transição para Aposentadoria - "Pedágio"': '6172',
                   'Renúncia ao benefício': '6166',
                   'Pedidos Genéricos Relativos aos Benefícios em Espécie': '6173',
                   'Conversão': '6179',
                   'Cumulação': '6175',
                   'Data de Início de Benefício (DIB)': '6174',
                   'Parcelas de benefício não pagas': '6176',
                   'RMI - Renda Mensal Inicial, Reajustes e Revisões Específicas': '6119',
                   'Reajustes e Revisões Específicos': '6138',
                   'Abono da Lei 8.178/91': '6153',
                   'Aplicação de coeficiente de cálculo diverso do fixado na Lei n.º 8.213/91': '6147',
                   'Art. 144 da Lei 8.213/91 e/ou diferenças decorrentes': '6151',
                   'Art. 58 ADCT da CF/88': '6140',
                   'Correção Monetária de Benefício pago com atraso': '6158',
                   'Correção Monetária pela Súmula 71 TFR': '6157',
                   'Desconto do DL 1.910/81': '6155',
                   'Descontos dos benefícios': '6156',
                   'Expurgos inflacionários sobre os benefícios': '6143',
                   'Gratificação Natalina a partir da CF/88 (Art. 201, § 6º CF/88)': '6152',
                   'Índice de 4,02% da Lei 8.222/91': '6154',
                   'Manutenção do Benefício pela equivalência salarial': '6142',
                   'Reajustamento pelo IGP-DI': '6146',
                   'Reajustamento pelo INPC': '6150',
                   'Reajuste aplicado ao salário mínimo em setembro/94': '6148',
                   'Reajuste conforme Portaria MPAS 714/1993': '6159',
                   'Reajuste de 147%': '6145',
                   'Reajuste pela Súmula 260 do TFR': '6139',
                   'Salário Mínimo de Ncz$ 120,00 para junho/89': '6144',
                   'Sistemática de conversão dos benefícios previdenciários em URVs': '6149',
                   'Revisão do valor do benefício no primeiro reajuste após a concessão (Art. 21, § 3º, da Lei 8.880/1994)': '11945',
                   'Utilização do PNS no Reajuste de Benefícios': '6141',
                   'RMI - Renda Mensal Inicial': '6120',
                   'Alteração do coeficiente de cálculo de pensão': '6134',
                   'Alteração do coeficiente de cálculo do benefício': '6135',
                   'Alteração do teto máximo para o valor do benefício previdenciário do RGPS (EC 20 e 41)': '11944',
                   'Art. 26 da Lei 8.870/1994': '11941',
                   'Art. 29, II, da Lei 8.213/1991': '11943',
                   'Art. 29, § 5º, da Lei 8.213/1991': '11942',
                   'Benefício mínimo a partir da CF/88 (art. 201, § 2º CF/88)': '6126',
                   'Cálculo do Benefício de acordo com a Sistemática anterior à Lei 9.876/99': '6132',
                   'Cálculo do benefício de segurado especial de acordo com a Lei 9.876/99': '6136',
                   'Cálculo do fator previdenciário - Lei 9.876/99': '6137',
                   'Contribuição sobre vinte salários mínimos': '6131',
                   'Escala de Salário-Base': '6130',
                   'IRSM de Fevereiro de 1994(39,67%)': '6133',
                   'Limitação do salário-de-benefício e da renda mensal inicial': '6128',
                   'Parcelas e índices de correção do salário-de-contribuição': '6127',
                   'Inclusão do 13º salário (gratificação natalina) no PBC': '11940',
                   'RMI cuja salário-de-benefício supera menor valor teto': '6129',
                   'RMI da pensão de dependente de ex-combatente': '6125',
                   'RMI pela equivalência entre Salário-de-Benefício e Salário-de-Contribuição': '6123',
                   'RMI pelo art. 1º da Lei 6.423/77 - índices de atualização dos 24 1ºs salários-de-contribuição, anteriores aos 12 últimos)': '6122',
                   'RMI pelo art. 202 CF/88 (média dos 36 últimos salários-de-contribuição)': '6121',
                   'RMI sem incidência de Teto Limitador': '6124',
                   'Tempo de serviço': '6181',
                   'Averbação/Cômputo de tempo de serviço rural (empregado/empregador)': '6184',
                   'Averbação/Cômputo de tempo de serviço de empregado doméstico': '6187',
                   'Averbação/Cômputo de tempo de serviço de segurado especial (regime de economia familiar)': '6183',
                   'Averbação/Cômputo de tempo de serviço urbano': '6188',
                   'Averbação/Cômputo do tempo de serviço como aluno aprendiz': '6185',
                   'Averbação/Cômputo do tempo de serviço militar': '6186',
                   'Averbação/Cômputo/Conversão de tempo de serviço especial': '6182',
                   'Certidão de Tempo de Serviço': '6189',
                   'Contagem Recíproca de Tempo de Serviço': '6190',
                   'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                   'Partes e Procuradores': '8842',
                   'Substituição Processual': '8867',
                   'Assistência Judiciária Gratuita': '8843',
                   'Capacidade Processual': '9493',
                   'Honorários Periciais': '9258',
                   'Intervenção de Terceiros': '8859',
                   'Litigância de Má-Fé': '8865',
                   'Litisconsórcio e Assistência': '8866',
                   'Procuração / Mandato': '8868',
                   'Representação em Juízo': '8873',
                   'Substituição da Parte': '9494',
                   'Sucumbência': '8874',
                   'Custas': '10658',
                   'Honorários Advocatícios': '10655',
                   'Honorários Advocatícios em Execução Contra a Fazenda Pública': '10656',
                   'Honorários Advocatícios em FGTS': '10657',
                   'Atos Processuais': '8893',
                   'Prazo': '8928',
                   'Citação': '11783',
                   'Intimação / Notificação': '10939',
                   'Nulidade': '4264',
                   'Valor da Causa': '8934',
                   'Formação, Suspensão e Extinção do Processo': '8938',
                   'Suspensão do Processo': '8939',
                   'Extinção do Processo Sem Resolução de Mérito': '8942',
                   'Modificação ou Alteração do Pedido': '8941',
                   'Jurisdição e Competência': '4291',
                   'Competência': '8829',
                   'Imunidade de Jurisdição': '8838',
                   'Liquidação / Cumprimento / Execução': '9148',
                   'Ato Atentatório à Dignidade da Justiça': '9520',
                   'Benefício de Ordem': '9519',
                   'Causas Supervenientes à Sentença': '9517',
                   'Concurso de Credores': '9418',
                   'Constrição / Penhora / Avaliação / Indisponibilidade de Bens': '9163',
                   'Efeito Suspensivo / Impugnação / Embargos à Execução': '9518',
                   'Exceção de Pré-executividade': '10683',
                   'Execução Previdenciária': '9419',
                   'Expropriação de Bens': '9180',
                   'Extinção da Execução': '9414',
                   'Fraude à Execução': '9450',
                   'Imunidade de Execução': '9453',
                   'Levantamento de Valor': '9160',
                   'Multa Cominatória / Astreintes': '10686',
                   'Multa de 10%': '9166',
                   'Nulidade / Inexigibilidade do Título': '9178',
                   'Obrigação de Entregar': '10670',
                   'Busca e Apreensão': '10677',
                   'Imissão na Posse': '10676',
                   'Requerimento de Apreensão de Veículo': '12161',
                   'Requerimento de Reintegração de Posse': '12160',
                   'Obrigação de Fazer / Não Fazer': '10671',
                   'Precatório': '10672',
                   'Crédito Complementar': '10680',
                   'Fracionamento': '10679',
                   'Sequestro de Verbas Públicas': '10678',
                   'Prisão Civil': '10573',
                   'Remição': '10637',
                   'Requisição de Pequeno Valor - RPV': '10673',
                   'Sucessão': '9484',
                   'Valor da Execução / Cálculo / Atualização': '9149',
                   'Juros': '10684',
                   'Taxa SELIC': '10687',
                   'Medida Cautelar': '9192',
                   'Caução / Contracautela': '9532',
                   'Indenização do Prejuízo': '9524',
                   'Liminar': '9196',
                   'Objetos de cartas precatórias/de ordem': '11781',
                   'Atos executórios': '11786',
                   'Diligências': '11785',
                   'Intimação': '11782',
                   'Oitiva': '11784',
                   'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                   'Do Juiz': '8884',
                   'Impedimento': '10600',
                   'Suspeição': '10601',
                   'Dos Auxiliares da Justiça': '8888',
                   'Processo e Procedimento': '8960',
                   'Antecipação de Tutela / Tutela Específica': '8961',
                   'Erro de Procedimento': '8986',
                   'Provas': '10925',
                   'Depoimento': '10940',
                   'Revelia': '9024',
                   'Vícios Formais da Sentença': '9026',
                   'Recurso': '4305',
                   'Cabimento': '9098',
                   'Conversão em Agravo Retido': '10999',
                   'Efeitos': '9047',
                   'Preparo / Deserção': '9050',
                   'Regularidade Formal': '10666',
                   'Tempestividade': '9060',
                   'Revisão de Tutela Antecipada Antecedente': '12152',
                   'DIREITO PROCESSUAL PENAL': '1209',
                   'Ação Penal': '4263',
                   'Excesso de prazo para instrução / julgamento': '10902',
                   'Ausência de Fundamentação': '10867',
                   'Ausência de Publicidade': '10866',
                   'Cerceamento de Defesa': '10865',
                   'Quesitos': '10599',
                   'Vício Formal do Julgamento': '10890',
                   'Perempção': '7935',
                   'Prisão Decorrente de Sentença Condenatória': '10640',
                   'Prova Ilícita': '10926',
                   'Condicional do processo': '10602',
                   'Parcelamento de crédito tributário': '10603',
                   'Questão Prejudicial': '10691',
                   'Trancamento': '4272',
                   'Denúncia/Queixa': '4368',
                   'Desclassificação': '10935',
                   'Recebimento': '4370',
                   'Rejeição': '4371',
                   'Execução Penal': '7942',
                   'Medidas de Segurança': '7793',
                   'Internação': '7795',
                   'Tratamento Ambulatorial': '7794',
                   'Pena de Multa': '7792',
                   'Pena Privativa de Liberdade': '7791',
                   'Livramento condicional': '10636',
                   'Progressão de Regime': '10635',
                   'Crimes Hediondos': '10864',
                   'Regressão de Regime': '10906',
                   'Transferência de Preso': '10907',
                   'Pena Restritiva de Direitos': '7790',
                   'Interdição Temporária de Direitos': '7788',
                   'Limitação de Fim de Semana': '7789',
                   'Prestação de Serviços à Comunidade': '7787',
                   'Prestação Pecuniária': '7785',
                   'Falsidade': '7945',
                   'Inclusão/exclusão de Jurado': '7937',
                   'Desaforamento': '10631',
                   'Imunidade em razão de função, ofício ou profissão': '10909',
                   'Liberdade Provisória': '7928',
                   'Medidas Assecuratórias': '10912',
                   'Busca e Apreensão de Bens': '10914',
                   'Indisponibilidade / Seqüestro de Bens': '10913',
                   'Prisão em flagrante': '7929',
                   'Prisão Preventiva': '4355',
                   'Prisão Temporária': '10632',
                   'Denegação': '7941',
                   'Deserção': '7940',
                   'Registro de Ocorrência pela PM': '12159',
                   'DIREITO TRIBUTÁRIO': '14',
                   'Contribuições': '6031',
                   'Contribuições Corporativas': '6044',
                   'Conselhos Regionais e Afins (Anuidade)': '6046',
                   'Contribuição Sindical Rural': '10565',
                   'Contribuições para o SEBRAE, SESC, SENAC, SENAI e outros': '6045',
                   'Contribuições de Melhoria': '6032',
                   'Contribuições Especiais': '6071',
                   'Adicional de Tarifa Aeroportuária': '6075',
                   'AFRMM/Adicional ao Frete para Renovação da Marinha Mercante': '6076',
                   'AITP/Adicional de Indenização do Trabalhador Portuário Avulso': '6074',
                   'ATP/Adicional de Tarifa Portuária': '6073',
                   'Contribuição de Iluminação Pública': '6083',
                   'Contribuição de Intervenção no Domínio Econômico (CIDE)': '6080',
                   'Contribuição sobre Açúcar e Álcool': '6086',
                   'Contribuição sobre licença de uso ou transferência de tecnologia': '6079',
                   'CPMF/Contribuição Provisória sobre Movimentação Financeira': '6087',
                   'FGTS/Fundo de Garantia Por Tempo de Serviço': '6085',
                   'FNT/Fundo Nacional de Telecomunicações': '6072',
                   'FUNDAF/Fundo Especial de Desenvolvimento e Aperfeiçoamento das Atividades de Fiscalização': '6081',
                   'FUNDEF/Fundo de Manutenção e Desenvolvimento do Ensino Fundamental e de Valorização do Magistério': '6077',
                   'FUSEX/FUNSA/FUSMA/Fundo de Saúde das Forças Armadas': '6082',
                   'IUEE/Imposto Único sobre Energia Elétrica': '6084',
                   'Seguro Apagão (Lei 10.438/02)': '6078',
                   'Contribuições Previdenciárias': '6048',
                   '1/3 de férias': '6062',
                   'Aposentadoria/Retorno aoTrabalho': '6052',
                   'Cargo em Comissão': '6053',
                   'Contribuição de Autônomos, Empresários (Pró-labore) e Facultativos': '6070',
                   'Contribuição sobre a folha de salários': '6060',
                   'Contribuição sobre Nota Fiscal de Execução de Serviços': '6069',
                   'Custeio de Assistência Médica': '6064',
                   'Devolução de contribuições previdenciárias pagas além do teto': '6061',
                   'Gratificação Natalina/13º Salário': '6056',
                   'Hora Extra': '6065',
                   'Indenização Trabalhista': '6058',
                   'Mandato Eletivo/Lei 9.506/97': '6051',
                   'Massa Falida- Recolhimento': '6066',
                   'Nota Fiscal ou Fatura': '6067',
                   'Produção Agropecuária': '6057',
                   'Reembolso auxílio-creche': '6059',
                   'Salário-Maternidade': '6068',
                   'Servidores Ativos': '6049',
                   'Servidores Inativos': '6050',
                   'Tempo de Serviço Rural/Contribuições não Recolhidas': '6055',
                   'Tempo de Serviço Urbano/Contribuições não Recolhidas': '6054',
                   'Contribuições Sociais': '6033',
                   'Cofins': '6035',
                   'COFINS - Importação': '10562',
                   'Construção Civil': '6043',
                   'Contribuição INCRA': '6041',
                   'Contribuição Social sobre o Lucro Líquido': '6036',
                   'Compensação de Prejuízo': '10563',
                   'Finsocial': '6034',
                   'Funrural': '6040',
                   'PASEP': '6042',
                   'PIS': '6039',
                   'PIS - Importação': '10561',
                   'Salário-Educação': '6037',
                   'Seguro Acidentes do Trabalho': '6038',
                   'Crédito Tributário': '5986',
                   'Alíquota': '6012',
                   'Alíquota Progressiva': '6014',
                   'Alíquota Zero': '6013',
                   'Índice da Alíquota': '6015',
                   'Anulação de Débito Fiscal': '6004',
                   'Base de Cálculo': '6008',
                   'Cálculo de ICMS "por dentro"': '10559',
                   'Exclusão - ICMS': '10556',
                   'Exclusão - IPI': '10557',
                   'Exclusão - Receitas Provenientes de Exportação': '10558',
                   'Exclusão - Receitas Transferidas a outras Pessoas Jurídicas': '10959',
                   'CND/Certidão Negativa de Débito': '5999',
                   'Certificado de Regularidade - FGTS': '6002',
                   'Expedição de Certidão Positiva de Débito com Efeito de Negativa': '6001',
                   'Expedição de CND': '6000',
                   'Creditamento': '6016',
                   'Crédito Prêmio': '6009',
                   'Crédito Presumido': '6010',
                   'Denúncia espontânea': '5997',
                   'Extinção do Crédito Tributário': '5990',
                   'Compensação com Apólices da Dívida Pública': '5991',
                   'Decadência': '5993',
                   'Constitucionalidade do artigo 45 da Lei 8212/91': '10551',
                   'Constitucionalidade do artigo 46 da Lei 8212/91': '10545',
                   'Constitucionalidade do artigo 4º da LC 118/05': '10544',
                   'Decretação de Ofício': '10548',
                   'Interrupção': '10547',
                   'Despacho de Citação': '10550',
                   'Arquivamento Administrativo - Crédito de Pequeno Valor': '10549',
                   'TDA/Títulos da Dívida Agrária': '5995',
                   'Fato Gerador/Incidência': '6011',
                   'Incentivos fiscais': '6003',
                   'Juros/Correção Monetária': '6005',
                   'Lançamento': '5998',
                   'Prazo de Recolhimento': '6006',
                   'Repetição de indébito': '6007',
                   'Suspensão da Exigibilidade': '5987',
                   'Carta de fiança': '5988',
                   'Depósito Judicial': '10543',
                   'Parcelamento': '5989',
                   'Discriminação Tributária MERCOSUL': '6088',
                   'Dívida Ativa': '6017',
                   'Empréstimos Compulsórios': '5973',
                   'Aquisição de combustíveis': '5975',
                   'Aquisição de passagens e moedas - Viagem Exterior': '5976',
                   'Aquisição de veículos automotores': '5974',
                   'GATT - "Acordo Geral sobre Tarifas e Comércio"': '6030',
                   'Impostos': '5916',
                   'ICMS/ Imposto sobre Circulação de Mercadorias': '5946',
                   'ICMS/Importação': '5947',
                   'IE/ Imposto sobre Exportação': '5944',
                   'II/ Imposto sobre Importação': '5941',
                   'Drawback': '5943',
                   'Importação de bens usados': '5942',
                   'IOC/IOF Imposto sobre operações de crédito, câmbio e seguro, ou relativas a títulos ou valores mobiliários': '5948',
                   'Incidência sobre Ações de Companhias Abertas': '5949',
                   'IPI/ Imposto sobre Produtos Industrializados': '5945',
                   'Princípio da Seletividade': '10947',
                   'IPMF - Imposto Provisório sobre Movimentação Financeira': '10690',
                   'IPTU/ Imposto Predial e Territorial Urbano': '5952',
                   'IPVA - Imposto Sobre Propriedade de Veículos Automotores': '5953',
                   'IRPF/Imposto de Renda de Pessoa Física': '5917',
                   'Correção da Tabela': '10689',
                   'Incidência decorrente de Desligamento de Plano de Previdência Privada': '5931',
                   'Incidência decorrente de Liquidação de Entidade de Previdência Privada': '5932',
                   'Incidência sobre 1/3 de férias (art. 7º, XVII da CF)': '5927',
                   'Incidência sobre 13° Salário': '5928',
                   'Incidência sobre Abono de Permanência': '10661',
                   'Incidência sobre Aplicações Financeiras': '5936',
                   'Incidência sobre Aposentadoria': '5919',
                   'Incidência sobre Auxílio-condução': '10532',
                   'Incidência sobre Auxílio-creche': '10533',
                   'Incidência sobre Férias Compensadas': '5923',
                   'Incidência sobre Função Comissionada': '5929',
                   'Incidência sobre Hora Extra': '5930',
                   'Incidência sobre Licença-Prêmio/Abono/Indenização': '5921',
                   'Incidência sobre Lucro Imobiliário': '5926',
                   'Incidência sobre Participação nos Lucros': '5925',
                   'Incidência sobre PDV': '5918',
                   'Incidência sobre Proventos de Previdência Privada': '5924',
                   'Retido na fonte': '5937',
                   'IRPJ/Imposto de Renda de Pessoa Jurídica': '5933',
                   'Compensação de Prejuízos': '5940',
                   'Cooperativa': '5939',
                   'Demonstrações Financeiras (DCTF)': '5935',
                   'Incidência sobre Lucro': '5938',
                   'Microempresa': '5934',
                   'ISS/ Imposto sobre Serviços': '5951',
                   'ITBI - Imposto de Transmissão Intervivos de Bens Móveis e Imóveis': '5954',
                   'ITCD - Imposto de Transmissão Causa Mortis': '5955',
                   'ITR/ Imposto Territorial Rural': '5950',
                   'Limitações ao Poder de Tributar': '5913',
                   'Competência Tributária': '10540',
                   'Imunidade': '5914',
                   'Entidades Sem Fins Lucrativos': '10528',
                   'Imunidade Recíproca': '10530',
                   'Livros / Jornais / Periódicos': '10527',
                   'Partidos Políticos': '10529',
                   'Isenção': '5915',
                   'Obrigação Tributária': '5978',
                   'Capacidade Tributária': '10539',
                   'CNPJ/Cadastro Nacional de Pessoas Jurídicas': '5983',
                   'CPF/Cadastro de Pessoas Físicas': '5984',
                   'DIMOB/Declaração de Informações sobre Atividades Imobilíárias': '5982',
                   'Obrigação Acessória': '5985',
                   'Responsabilidade tributária': '5979',
                   'Responsabilidade Tributária do Sócio-Gerente / Diretor / Representante': '5980',
                   'Substituição Tributária': '5981',
                   'Procedimentos Fiscais': '6021',
                   'Autorização para Impressão de Documentos Fiscais - AIDF': '6027',
                   'Cadastro de Inadimplentes - CADIN': '6026',
                   'Levantamento de depósito': '6025',
                   'Liberação de mercadorias': '6024',
                   'Perdimento de Bens': '6029',
                   'Quebra de Sigilo Bancário': '10560',
                   'Sigilo Fiscal': '6022',
                   'Utilização de Dados Relativos à CPMF para Fins de Fiscalização': '6023',
                   'Processo Administrativo Fiscal': '6018',
                   'Arrolamento de Bens': '6020',
                   'Depósito Prévio ao Recurso Administrativo': '6019',
                   'Regimes Especiais de Tributação': '6089',
                   'PAES/Parcelamento Especial': '6091',
                   'REFIS/Programa de Recuperação Fiscal': '6090',
                   'SIMPLES': '6092',
                   'Super SIMPLES': '6093',
                   'Taxas': '5956',
                   'Estaduais': '5971',
                   'Federais': '5957',
                   'Taxa Anual por Hectare': '5958',
                   'Taxa de Aferição de Equipamentos de Metrologia': '5970',
                   'Taxa de Armazenamento': '5959',
                   'Taxa de Despacho Aduaneiro': '5960',
                   'Taxa de Exploração Mineral': '5961',
                   'Taxa de Fiscalização Ambiental': '5962',
                   'Taxa de Fiscalização da Comissão de Valores Mobiliários': '5968',
                   'Taxa de Guia de Importação': '5963',
                   'Taxa de Licença de Importação': '5964',
                   'Taxa de Melhoramento de Portos': '5965',
                   'Taxa de Permanência': '5966',
                   'Taxa de Saúde Suplementar': '5967',
                   'Taxa Judiciária': '5969',
                   'Municipais': '5972',
                   'Taxa de Coleta de Lixo': '10536',
                   'Taxa de Iluminação Pública': '10535',
                   'Taxa de Licenciamento de Estabelecimento': '10538',
                   'Taxa de Limpeza Pública': '10534',
                   'Taxa de Prevenção e Combate a Incêndio': '10537'}
