just_trab_1_grau = {'DIREITO DO TRABALHO': '864',
                    'Acordo e Convenção Coletivos de Trabalho': '1695',
                    'Anulação': '4438',
                    'Aplicabilidade': '7649',
                    'Aposentadoria e Pensão': '2622',
                    'Complementação de Aposentadoria / Pensão': '2624',
                    'Categoria Profissional Especial': '7644',
                    'Advogados': '5276',
                    'Aeronautas': '5277',
                    'Aeroviários': '7645',
                    'Artistas': '5278',
                    'Atleta Profissional': '5279',
                    'Bancários': '5280',
                    'Cabineiros de Elevador': '5281',
                    'Digitadores / Mecanógrafos / Datilógrafos': '5288',
                    'Doméstico': '5282',
                    'Engenheiro, Arquiteto e Engenheiro Agrônomo': '5284',
                    'Jornalistas': '5286',
                    'Marítimos': '5287',
                    'Médicos': '5289',
                    'Mineiros de Subsolos': '5290',
                    'Músicos Profissionais': '5291',
                    'Operadores Cinematográficos': '5293',
                    'Operadores de Carga e Descarga (Estiva e Capatazia)': '5292',
                    'Professores': '5294',
                    'Químicos': '5295',
                    'Radialistas': '5296',
                    'Rural': '7646',
                    'Serviços de Telefonia ou Telegrafia': '5297',
                    'Trabalhadores em Petróleo': '5299',
                    'Vigia e Vigilantes': '5301',
                    'Direito de Greve / Lockout': '7639',
                    'Interdito Proibitório': '7640',
                    'Direito Sindical e Questões Análogas': '1697',
                    'Contribuição / Taxa Assistencial': '1690',
                    'Contribuição Confederativa': '1691',
                    'Eleição': '1703',
                    'Registro de Entidade Sindical': '1705',
                    'Contribuição Sindical': '1773',
                    'Contribuição Sindical Rural': '10564',
                    'Representação Sindical': '4452',
                    'Férias': '2662',
                    'Abono Pecuniário': '2663',
                    'Fruição / Gozo': '2019',
                    'Indenização / Terço Constitucional': '2021',
                    'Outras Relações de Trabalho': '7628',
                    'Contrato de Aprendizagem': '2557',
                    'Contrato de Estágio': '2559',
                    'Cooperativa de Trabalho': '2558',
                    'Empreitada': '7629',
                    'Honorários Profissionais': '7631',
                    'Representante Comercial Autônomo': '7630',
                    'Trabalhador Avulso': '7633',
                    'Trabalhador Eventual': '7632',
                    'Remuneração, Verbas Indenizatórias e Benefícios': '2581',
                    'Abono': '2583',
                    'Adicional': '2594',
                    'Adicional de Transferência': '2604',
                    'Periculosidade': '1681',
                    'Ajuda de Custo': '2606',
                    'Cesta Básica': '1767',
                    'Comissão': '1783',
                    'Complemento Temporário Variável de Ajuste ao Piso de Mercado': '1789',
                    'Contribuição de Previdência Privada - Resgate': '2349',
                    'Décimo Terceiro Salário': '2666',
                    'Descontos Salariais - Devolução': '1888',
                    'Diárias': '1920',
                    'Gorjeta': '2450',
                    'Gratificação': '2055',
                    'Gratificação de Função': '8818',
                    'Gratificação por Tempo de Serviço': '8817',
                    'Licenças e Folgas - Conversão em Pecúnia': '8813',
                    'Multa Prevista em Norma Coletiva': '2215',
                    'PIS - Indenização': '2273',
                    'Plano de Saúde': '2364',
                    'Prêmio': '2331',
                    'Restituição / Indenização de Despesa': '4442',
                    'Salário / Diferença Salarial': '2458',
                    'Mínimo': '5269',
                    'Piso Salarial da Categoria / Salário Mínimo Profissional': '2275',
                    'Reajuste Salarial': '2449',
                    'Salário Família': '2461',
                    'Salário In Natura': '1721',
                    'Salário Maternidade': '8812',
                    'Salário Paternidade': '2463',
                    'Salário por Acúmulo de Cargo / Função': '8810',
                    'Salário por Equiparação / Isonomia': '2697',
                    'Salário Por Fora - Integração': '2466',
                    'Salário Por Safra': '2468',
                    'Salário Substituição': '8816',
                    'Salário Vencido / Retido': '2452',
                    'Seguro de Vida': '2477',
                    'Supressão de Horas Extras Habituais - Indenização': '2117',
                    'Tarefa': '2493',
                    'Tíquete Alimentação': '2506',
                    'Vale Transporte': '2540',
                    'Rescisão do Contrato de Trabalho': '2620',
                    'Culpa Recíproca': '1849',
                    'Despedida / Dispensa Imotivada': '1904',
                    'Indenização do artigo 478 da CLT': '8824',
                    'Justa Causa / Falta Grave': '1907',
                    'Plano de Demissão Voluntária': '2243',
                    'Reintegração / Readmissão ou Indenização': '2656',
                    'Empregado Público': '1965',
                    'Gestante': '1978',
                    'Membro da Cipa': '1981',
                    'Portador de HIV': '1966',
                    'Anistia': '2657',
                    'Contrato Suspenso': '1976',
                    'Dirigente Sindical': '1929',
                    'Estabilidade Acidentária': '2661',
                    'Estabilidade decorrente de Norma Coletiva': '1977',
                    'Rescisão Indireta': '2435',
                    'Seguro Desemprego': '2478',
                    'Indenização': '2479',
                    'Liberação das Guias': '2480',
                    'Verbas Rescisórias': '2546',
                    'AVISO PRÉVIO': '2641',
                    'Décimo Terceiro Salário Proporcional': '8820',
                    'Férias Proporcionais': '8821',
                    'Indenização Adicional': '8822',
                    'Multa de 40% do FGTS': '1998',
                    'Multa do Artigo 467 da CLT': '2210',
                    'Multa do Artigo 477 da CLT': '2212',
                    'Saldo de Salário': '8823',
                    'Responsabilidade Civil do Empregador': '2567',
                    'Indenização por Dano Material': '8808',
                    'Acidente de Trabalho': '8809',
                    'Indenizaçao por Dano Moral': '1855',
                    'Assédio Moral': '1723',
                    'Assédio Sexual': '1724',
                    'Desconfiguração de Justa Causa': '9051',
                    'Responsabilidade Solidária / Subsidiária': '1937',
                    'Grupo Econômico': '5356',
                    'Sócio / Acionista': '8807',
                    'Subempreitada': '8806',
                    'Sucessão de Empregadores': '8805',
                    'Tomador de Serviços / Terceirização': '2704',
                    'Sentença Normativa': '2135',
                    'Revisão': '4437',
                    'DIREITO INTERNACIONAL': '6191',
                    'Estrangeiro': '6197',
                    'Trabalhador Migrante ou Fronteiriço do MERCOSUL': '6201',
                    'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                    'Partes e Procuradores': '8842',
                    'Substituição Processual': '8867',
                    'Assistência Judiciária Gratuita': '8843',
                    'Capacidade Processual': '9493',
                    'Honorários Periciais': '9258',
                    'Intervenção de Terceiros': '8859',
                    'Litigância de Má-Fé': '8865',
                    'Litisconsórcio e Assistência': '8866',
                    'Procuração / Mandato': '8868',
                    'Representação em Juízo': '8873',
                    'Substituição da Parte': '9494',
                    'Sucumbência': '8874',
                    'Atos Processuais': '8893',
                    'Prazo': '8928',
                    'Citação': '11783',
                    'Nulidade': '8919',
                    'Valor da Causa': '8934',
                    'Formação, Suspensão e Extinção do Processo': '8938',
                    'Suspensão do Processo': '8939',
                    'Extinção do Processo Sem Resolução de Mérito': '8942',
                    'Modificação ou Alteração do Pedido': '8941',
                    'Jurisdição e Competência': '8828',
                    'Competência': '8829',
                    'Imunidade de Jurisdição': '8838',
                    'Liquidação / Cumprimento / Execução': '9148',
                    'Ato Atentatório à Dignidade da Justiça': '9520',
                    'Benefício de Ordem': '9519',
                    'Causas Supervenientes à Sentença': '9517',
                    'Concurso de Credores': '9418',
                    'Constrição / Penhora / Avaliação / Indisponibilidade de Bens': '9163',
                    'Efeito Suspensivo / Impugnação / Embargos à Execução': '9518',
                    'Execução Previdenciária': '9419',
                    'Expropriação de Bens': '9180',
                    'Extinção da Execução': '9414',
                    'Fraude à Execução': '9450',
                    'Imunidade de Execução': '9453',
                    'Levantamento de Valor': '9160',
                    'Multa Cominatória / Astreintes': '10686',
                    'Multa de 10%': '9166',
                    'Nulidade / Inexigibilidade do Título': '9178',
                    'Obrigação de Entregar': '10670',
                    'Busca e Apreensão': '10677',
                    'Imissão na Posse': '10676',
                    'Obrigação de Fazer / Não Fazer': '10671',
                    'Remição': '9189',
                    'Sucessão': '9484',
                    'Valor da Execução / Cálculo / Atualização': '9149',
                    'Correção Monetária': '10685',
                    'Juros': '10684',
                    'Taxa SELIC': '10687',
                    'Medida Cautelar': '9192',
                    'Caução / Contracautela': '9532',
                    'Indenização do Prejuízo': '9524',
                    'Liminar': '9196',
                    'Ministério Público': '8875',
                    'Objetos de cartas precatórias/de ordem': '11781',
                    'Atos executórios': '11786',
                    'Diligências': '11785',
                    'Intimação': '11782',
                    'Oitiva': '11784',
                    'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                    'Do Juiz': '8884',
                    'Dos Auxiliares da Justiça': '8888',
                    'Processo e Procedimento': '8960',
                    'Antecipação de Tutela / Tutela Específica': '8961',
                    'Erro de Procedimento': '8986',
                    'Provas': '8990',
                    'Depoimento': '10940',
                    'Revelia': '9024',
                    'Vícios Formais da Sentença': '9026',
                    'Recurso': '9045',
                    'Cabimento': '9098',
                    'Efeitos': '9047',
                    'Preparo / Deserção': '9050',
                    'Tempestividade': '9060',
                    'Revisão de Tutela Antecipada Antecedente': '12152'}
