just_mil_uniao_STM = {'DIREITO DO TRABALHO': '864',
                      'Responsabilidade Civil do Empregador': '2567',
                      'Indenização por Dano Material': '8808',
                      'Acidente de Trabalho': '8809',
                      'Indenizaçao por Dano Moral': '1855',
                      'DIREITO PENAL': '287',
                      'Contravenções Penais': '3692',
                      'Omissão de comunicação de crime': '12355',
                      'Recusa de dados sobre a própria identificação ou qualificação': '12356',
                      'Simulação de Qualidade de Funcionário': '12348',
                      'Uso ilegítimo de uniforme ou distintivo': '12349',
                      'Crimes contra a vida': '3369',
                      'Feminicídio': '12091',
                      'Homicídio Agravado pela Prática de Extermínio de Seres Humanos': '12130',
                      'Fato Atípico': '10952',
                      'DIREITO PENAL MILITAR': '11068',
                      'Crime Culposo': '11069',
                      'Crime em tempo de guerra': '11070',
                      'Crime Tentado': '11071',
                      'Crimes contra a Administração da Justiça Militar': '11072',
                      'Auto-acusação falsa': '11358',
                      'Coação': '11359',
                      'Comunicação falsa de crime': '11360',
                      'Corrupção ativa de testemunha, perito ou intérprete': '11361',
                      'Denunciação caluniosa': '11362',
                      'Desacato': '11363',
                      'Desobediência a decisão judicial': '11364',
                      'Desobediência a decisão sobre perda ou suspensão de atividade ou direito': '11365',
                      'Exploração de prestígio': '11366',
                      'Falso testemunho ou falsa perícia': '11367',
                      'Favorecimento pessoal': '11368',
                      'Favorecimento real': '11369',
                      'Inutilização,sonegação ou descaminho de material probante': '11370',
                      'Publicidade opressiva': '11371',
                      'Recusa de função na Justiça Militar': '11372',
                      'Crimes contra a Administração Militar': '11073',
                      'Concussão, Excesso de Exação e Desvio': '11308',
                      'Concussão': '11355',
                      'Desvio': '11356',
                      'Excesso de exação': '11357',
                      'Corrupção': '11309',
                      'Corrupção ativa': '11352',
                      'Corrupção passiva': '11353',
                      'Participação ilícita': '11354',
                      'Crimes contra o dever funcional': '11310',
                      'Abandono de cargo': '11336',
                      'Abuso de confiança ou boa fé': '11337',
                      'Aplicação ilegal de verba ou dinheiro': '11338',
                      'Condescendência criminosa': '11339',
                      'Exercício funcional ilegal': '11340',
                      'Extravio, sonegação ou inutilização de livro ou documento': '11341',
                      'Inobservancia de lei, regulamento ou instrução': '11342',
                      'Não inclusão de nome em lista': '11343',
                      'Obstáculo à hasta pública, concorrência ou tomada de preços': '11344',
                      'Patrocínio indébito': '11345',
                      'Prevaricação': '11346',
                      'Violação de sigilo de proposta de concorrência': '11347',
                      'Violação de sigilo funcional': '11348',
                      'Violação do dever funcional com o fim de lucro': '11349',
                      'Violação ou divulgação indevida de correspondência ou comunicação': '11350',
                      'Violência arbitrária': '11351',
                      'Crimes praticados por particular contra a Administração Militar': '11311',
                      'Impedimento, perturbação ou fraude de concorrencia': '11331',
                      'Inutilização de edital ou de sinal oficial': '11332',
                      'Subtração ou inutilização de livro, processo ou documento': '11333',
                      'Tráfico de influência': '11334',
                      'Usurpação de função': '11335',
                      'Desacato e da Desobediência': '11312',
                      'Desacato a assemelhado ou funcionário': '11326',
                      'Desacato a militar': '11327',
                      'Desacato a superior': '11328',
                      'Desobediência': '11329',
                      'Ingresso clandestino': '11330',
                      'Falsidade': '7945',
                      'Certidão ou atestado ideologicamente falso': '11318',
                      'Cheques sem fundos': '11319',
                      'Falsa identidade': '11320',
                      'Falsidade ideológica': '11321',
                      'Falsificação de documento': '11322',
                      'Supressão de documento': '11323',
                      'Uso de documento falso': '11324',
                      'Uso de documento pessoal alheio': '11325',
                      'Peculato': '11315',
                      'Peculato mediante aproveitamento ou erro de outrem': '11316',
                      'Peculato-furto': '11317',
                      'Crimes contra a Autoridade ou Disciplina Militar': '11074',
                      'Aliciação e incitamento': '11268',
                      'Aliciação para motim ou revolta': '11301',
                      'Apologia de fato criminoso ou do seu autor': '11302',
                      'Incitamento': '11303',
                      'Desrespeito a superior e a símbolo nacional ou farda': '11267',
                      'Despojamento desprezível': '11304',
                      'Desrespeito a comandante, oficial-general ou oficial de serviço': '11305',
                      'Desrespeito a símbolo nacional': '11306',
                      'Desrespeito a superior': '11307',
                      'Fuga, evasão, arrebatamento e amotinamento de presos': '11269',
                      'Amotinamento': '11297',
                      'Arrebatamento de preso ou internado': '11298',
                      'Evasão de preso ou internado': '11299',
                      'Fuga de preso ou internado': '11300',
                      'Insubordinação': '11270',
                      'Oposição a ordem de sentinela': '11293',
                      'Publicação ou crítica indevida': '11294',
                      'Recusa a obediência': '11295',
                      'Reunião ilícita': '11296',
                      'Motim e Revolta': '11271',
                      'Conspiração': '11288',
                      'Motim': '11289',
                      'Omissão de lealdade militar': '11290',
                      'Organização de grupo para prática de violência': '11291',
                      'Revolta': '11292',
                      'Resistência': '11272',
                      'Resistência mediante ameaça ou violência': '11287',
                      'Usurpação e excesso ou abuso de autoridade': '11273',
                      'Abuso de requisição militar': '11277',
                      'Assunção de comando sem ordem ou autorização': '11278',
                      'Conservação ilegal de comando': '11279',
                      'Ofensa aviltante a inferior': '11280',
                      'Operação militar sem ordem superior': '11281',
                      'Ordem arbitrária de invasão': '11282',
                      'Rigor excessivo': '11283',
                      'Uso indevido de uniforme, distintivo ou insígnia militar por qualquer pessoa': '11284',
                      'Uso indevido por militar de uniforme, distintivo ou insígnia': '11285',
                      'Violência contra inferior': '11286',
                      'Violência contra superior ou militar de serviço': '11274',
                      'Violência contra militar de serviço': '11275',
                      'Violência contra superior': '11276',
                      'Crimes contra a Pessoa': '11075',
                      'Crimes contra a Honra': '11223',
                      'Calúnia': '11262',
                      'Difamação': '11263',
                      'Injúria': '11264',
                      'Injuria real': '11265',
                      'Ofensa às forças armadas': '11266',
                      'Crimes contra a Liberdade': '11224',
                      'Ameaça': '11253',
                      'Constragimento ilegal': '11254',
                      'Desafio para duelo': '11255',
                      'Divulgação de segredo': '11256',
                      'Sequestro ou cárcere privado': '11257',
                      'Violação de correspondência': '11258',
                      'Violação de domicílio': '11259',
                      'Violação de recato': '11260',
                      'Violação de segredo profissional': '11261',
                      'Crimes Sexuais': '11225',
                      'Atentado violento ao pudor': '11249',
                      'Corrupção de menores': '11250',
                      'Estupro': '11251',
                      'Pederastia ou outro ato de libidinagem': '11252',
                      'Genocídio': '11248',
                      'Homicídio': '11243',
                      'Homicidio qualificado': '11244',
                      'Homicido privilegiado': '11245',
                      'Provocação direta ou auxílio a suicídio': '11246',
                      'Provocação indireta ao suicídio': '11247',
                      'Lesão Corporal e Rixa': '11228',
                      'Lesão grave': '11237',
                      'Lesão leve': '11238',
                      'Lesão levíssima': '11239',
                      'Lesão privilegiada': '11240',
                      'Lesão seguida de morte': '11241',
                      'Participação em rixa': '11242',
                      'Periclitação da Vida ou da Saúde': '11229',
                      'Abandono de pessoa': '11233',
                      'Abandono de pessoa seguida de morte ou lesão grave': '11234',
                      'Maus tratos': '11235',
                      'Maus tratos seguido de morte ou lesão grave': '11236',
                      'Ultraje Público ao Pudor': '11230',
                      'Ato obsceno': '11231',
                      'Escrito ou objeto obsceno': '11232',
                      'Crimes contra a Segurança Externa do País': '11076',
                      'Atos de jurisdição indevida': '11208',
                      'Consecução de notícia, informação ou documento para fim de espionagem': '11209',
                      'Desenho ou levantamento de plano ou planta de local militar': '11210',
                      'Entendimento para empenhar o Brasil à neutralidade ou à guerra': '11211',
                      'Entendimento para gerar conflito ou divergência com o Brasil': '11212',
                      'Hostilidade contra país estrangeiro': '11213',
                      'Hostilidade qualificada pelo resultado': '11214',
                      'Penetração com o fim de espionagem': '11215',
                      'Provocação a país estrangeiro': '11216',
                      'Revelação de notícia, informação ou documento': '11217',
                      'Revelação de notícia, informação ou documento, com o fim de espionagem militar': '11218',
                      'Sobrevôo em local interdito': '11219',
                      'Tentativa contra a soberania do Brasil': '11220',
                      'Turbação de objeto ou documento': '11221',
                      'Violação de território estrangeiro': '11222',
                      'Crimes contra Incolumidade Pública': '11077',
                      'Contra a Saúde': '11178',
                      'Corrupção ou poluição de água potável': '11200',
                      'Envenenamento com perigo extensivo': '11201',
                      'Epidemia': '11202',
                      'Fornecimento de substância alterada': '11203',
                      'Fornecimento de substancia nociva': '11204',
                      'Omissão de notificação de doença': '11205',
                      'Receita Ilegal': '11206',
                      'Tráfico, posse ou uso de entorpecente ou substância de efeito similar': '11207',
                      'Crimes contra os Meios de Transporte e de Comunicação': '11179',
                      'Arremesso de projétil': '11194',
                      'Atentado contra serviço de utilidade militar': '11195',
                      'Atentado contra transporte': '11196',
                      'Atentado contra viatura ou outro meio de transporte': '11197',
                      'Interrupção ou perturbação de serviço ou meio de comunicação': '11198',
                      'Perigo de desastre ferroviário': '11199',
                      'Crimes de Perigo Comum': '11180',
                      'Abuso de radiação': '11181',
                      'Desabamento ou desmoronamento': '11182',
                      'Difusão de epizootia ou praga vegetal': '11183',
                      'Embriaguez ao volante': '11184',
                      'Emprego de gás tóxico ou asfixiante': '11185',
                      'Explosão': '11186',
                      'Fatos que expõem a perigo aparelhamento militar': '11187',
                      'Fuga após acidente de trânsito': '11188',
                      'Incêndio': '11189',
                      'Inundação': '11190',
                      'Perigo de inundação': '11191',
                      'Perigo resultante de violação de regra de trânsito': '11192',
                      'Subtração, ocultação ou inutilização de material de socorro': '11193',
                      'Crimes contra o Patrimônio': '11078',
                      'Apropriação Indébita': '11144',
                      'Apropriação de coisa achada': '11175',
                      'Apropriação de coisa havida acidentalmente': '11176',
                      'Apropriação indébita': '11177',
                      'Dano': '11145',
                      'Dano atenuado': '11168',
                      'Dano em aparelhos e instalações': '11169',
                      'Dano em navio de guerra ou mercante em serviço militar': '11170',
                      'Dano material ou aparelhamento de guerra': '11171',
                      'Dano qualificado': '11172',
                      'Dano simples': '11173',
                      'Desaparecimento,consunção ou extravio': '11174',
                      'Estelionato e outras fraudes': '11146',
                      'Abuso de pessoa': '11166',
                      'Estelionato': '11167',
                      'Furto': '11163',
                      'Furto de uso': '11164',
                      'Furto qualificado': '11165',
                      'Receptação': '11162',
                      'Roubo e Extorsão': '11149',
                      'Chantagem': '11155',
                      'Extorsão': '11156',
                      'Extorsão indireta': '11157',
                      'Extorsão mediante sequestro': '11158',
                      'Latrocínio': '11159',
                      'Roubo': '11160',
                      'Roubo qualificado': '11161',
                      'Usura': '11150',
                      'Usura pecuniária': '11154',
                      'Usurpação': '11151',
                      'Alteração de Limites': '11152',
                      'Aposição, supressão ou alteração de marca': '11153',
                      'Crimes contra o Serviço Militar e o Dever Militar': '11079',
                      'Abandono de posto e de outros crimes em serviço': '11116',
                      'Abandono de posto': '11135',
                      'Descumprimento de missão': '11136',
                      'Dormir em serviço': '11137',
                      'Embriaguez em serviço': '11138',
                      'Omissão de eficiência da força': '11139',
                      'Omissão de providências para evitar danos': '11140',
                      'Omissão de providências para salvar comandados': '11141',
                      'Omissão de socorro': '11142',
                      'Retenção indevida': '11143',
                      'Deserção': '7940',
                      'Concerto para deserção': '11126',
                      'Deserção - casos assimilados': '11128',
                      'Deserção especial': '11129',
                      'Deserção por evasão ou fuga': '11130',
                      'Deserção privilegiada': '11131',
                      'Deserção qualificada': '11132',
                      'Favorecimento a desertor': '11133',
                      'Omissão de Oficial': '11134',
                      'Exercício de comércio': '11118',
                      'Exercício de comércio por oficial': '11125',
                      'Insubmissão': '11122',
                      'Criação ou simulação de incapacidade física': '11120',
                      'Favorecimento a convocado': '11121',
                      'Insubmissão privilegiada': '11123',
                      'Substituição de convocado': '11124',
                      'Parte Geral': '11080',
                      'Aplicação da Pena': '11081',
                      'Conversão da Pena': '11114',
                      'Substituição da Pena': '11115',
                      'Efeitos da Condenação': '11082',
                      'Perda em favor da Fazenda Pública': '11112',
                      'Reparação do Dano': '11113',
                      'Excludentes': '11083',
                      'Estado de Necessidade': '11106',
                      'Estado de Necessidade exculpante': '11107',
                      'Estrito Cumprimento do Dever Legal': '11108',
                      'Legítima Defesa': '11111',
                      'Extinção da punibilidade': '11084',
                      'Anistia': '11100',
                      'Indulto': '11101',
                      'Morte do Agente': '11102',
                      'Prescrição': '11103',
                      'Reabilitação': '11104',
                      'Ressarcimento do Dano': '11105',
                      'Livramento Condicional': '11085',
                      'Penas Acessórias': '11086',
                      'Exclusão das Forças Armadas': '11091',
                      'Inabilitação para o exercício de Função Pública': '11092',
                      'Incompatibilidade para o Oficialato': '11093',
                      'Indignidade para o Oficialato': '11094',
                      'Perda da Função Pública': '11095',
                      'Perda do Posto e da Patente': '11097',
                      'Suspensão do pátrio poder, tutela ou curatela': '11098',
                      'Suspensão dos direitos políticos': '11099',
                      'Suspensão Condicional da Pena': '11087',
                      'Tipicidade': '11088',
                      'Abolitio criminis': '11089',
                      'Princípio da Insignificância': '11090',
                      'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                      'Partes e Procuradores': '8842',
                      'Assistência Judiciária Gratuita': '8843',
                      'Capacidade Processual': '9493',
                      'Honorários Periciais': '9258',
                      'Intervenção de Terceiros': '8859',
                      'Litigância de Má-Fé': '8865',
                      'Litisconsórcio e Assistência': '8866',
                      'Procuração / Mandato': '8868',
                      'Representação em Juízo': '8873',
                      'Sucumbência': '8874',
                      'Honorários Advocatícios': '10655',
                      'Atos Processuais': '8893',
                      'Prazo': '8928',
                      'Citação': '10938',
                      'Intimação / Notificação': '10939',
                      'Nulidade': '11066',
                      'Reserva de Plenário': '10734',
                      'Formação, Suspensão e Extinção do Processo': '8938',
                      'Suspensão do Processo': '8939',
                      'Extinção do Processo Sem Resolução de Mérito': '8942',
                      'Adequação da Ação / Procedimento': '10737',
                      'Interesse Processual': '10735',
                      'Jurisdição e Competência': '11053',
                      'Competência': '8829',
                      'Competência da Justiça Estadual': '10899',
                      'Competência da Justiça Federal': '10898',
                      'Competência da Justiça Militar da União': '11055',
                      'Competência da Justiça Militar dos Estados': '11048',
                      'Competência por Prerrogativa de Função': '10900',
                      'Imunidade de Jurisdição': '8838',
                      'Liquidação / Cumprimento / Execução': '9148',
                      'Ato Atentatório à Dignidade da Justiça': '9520',
                      'Medida Cautelar': '9192',
                      'Ministério Público': '8875',
                      'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                      'Do Juiz': '8884',
                      'Impedimento': '10600',
                      'Suspeição': '10601',
                      'Dos Auxiliares da Justiça': '8888',
                      'Processo e Procedimento': '8960',
                      'Erro de Procedimento': '8986',
                      'Provas': '10925',
                      'Depoimento': '10940',
                      'Revelia': '9024',
                      'Vícios Formais da Sentença': '9026',
                      'Recurso': '4305',
                      'Cabimento': '9098',
                      'Efeitos': '9047',
                      'Regularidade Formal': '10666',
                      'Sobrestamento': '10738',
                      'Tempestividade': '9060',
                      'Fac-símile': '10668',
                      'DIREITO PROCESSUAL PENAL': '1209',
                      'Ação Penal': '4263',
                      'Excesso de prazo para instrução / julgamento': '10902',
                      'Ausência de Fundamentação': '10867',
                      'Ausência de Publicidade': '10866',
                      'Cerceamento de Defesa': '10606',
                      'Vício Formal do Julgamento': '10890',
                      'Prisão Decorrente de Sentença Condenatória': '10640',
                      'Prova Ilícita': '10926',
                      'Suspensão': '4271',
                      'Questão Prejudicial': '10691',
                      'Trancamento': '10610',
                      'Denúncia/Queixa': '4368',
                      'Desclassificação': '10935',
                      'Recebimento': '4370',
                      'Rejeição': '4371',
                      'Execução Penal': '11052',
                      'Execução Penal Provisória - Cabimento': '10908',
                      'Medidas de Segurança': '7793',
                      'Internação': '7795',
                      'Tratamento Ambulatorial': '7794',
                      'Pena Privativa de Liberdade': '7791',
                      'Livramento condicional': '10636',
                      'Transferência de Preso': '10907',
                      'Habeas Corpus - Cabimento': '10891',
                      'Investigação Penal': '10604',
                      'Quebra do Sigilo Bancário': '10607',
                      'Quebra do Sigilo Fiscal': '10608',
                      'Quebra do Sigilo Telefônico': '10609',
                      'Competência dos Juizados Especiais': '10897',
                      'Desaforamento': '10631',
                      'Imunidade em razão de função, ofício ou profissão': '10909',
                      'Liberdade Provisória': '7928',
                      'Medidas Assecuratórias': '10912',
                      'Busca e Apreensão de Bens': '10914',
                      'Indisponibilidade / Seqüestro de Bens': '10913',
                      'Prisão Domiciliar / Especial': '10904',
                      'Prisão em flagrante': '7929',
                      'Prisão Preventiva': '4355',
                      'Denegação': '7941',
                      'DIREITO PROCESSUAL PENAL MILITAR': '11049',
                      'Ação Penal Militar': '11050',
                      'Irregularidade na composição do Conselho': '11067',
                      'Correição Parcial': '11051',
                      'Representação do Corregedor': '11064',
                      'Requerimento da Parte': '11065',
                      'Penas restritivas de direitos': '11057',
                      'Cassação de licença para direção de veículo motorizado': '11058',
                      'Confisco': '11059',
                      'Exílio local': '11060',
                      'Interdição de estabecimento ou associação': '11061',
                      'Proibição de frequentar determinados locais': '11062',
                      'Suspensão do exercício do posto, graduação, cargo ou função': '11063',
                      'Competência da Justiça Militar Estadual': '11056',
                      'Menagem': '11054'}
