just_est_turm_uniform = {'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO': '9985',
                         'Atos Administrativos': '9997',
                         'Fiscalização': '10015',
                         'Inspeção Fitossanitária': '10016',
                         'Inspeção Sanitária de Origem Animal': '10018',
                         'Infração Administrativa': '10022',
                         'Apreensão': '10025',
                         'Interdição': '10024',
                         'Multas e demais Sanções': '10023',
                         'Inquérito / Processo / Recurso Administrativo': '10009',
                         'Licenças': '10350',
                         'Comercialização e/ou Utilização sem Restrições de Medicamentos': '10003',
                         'Comercialização sem Restrições de Gêneros Alimentícios': '10002',
                         'Comercialização sem Restrições de Produtos Industrializados': '10001',
                         'Declaração de Bagagem': '9999',
                         'Declaração de Trânsito Aduaneiro': '10000',
                         'Funcionamento de Comércio de Derivados de Petróleo': '10004',
                         'Funcionamento de Estabelecimentos Empresariais': '10006',
                         'Jogos de Bingo e/ou Caça-níqueis': '10084',
                         'Loterias/Sorteio': '10079',
                         'Registro / Porte de arma de fogo': '10007',
                         'Registro de Aeronave': '10008',
                         'Registro de Empresa': '10005',
                         'Concurso Público / Edital': '10370',
                         'Anulação': '4951',
                         'Anulação e Correção de Provas / Questões': '10379',
                         'Classificação e/ou Preterição': '10381',
                         'Condições Especiais para Prestação de Prova': '10384',
                         'Curso de Formação': '10327',
                         'Escolaridade': '10380',
                         'Exame de Saúde e/ou Aptidão Física': '10376',
                         'Exame Psicotécnico / Psiquiátrico': '10378',
                         'Exigência de Prática Forense': '10374',
                         'Inscrição / Documentação': '10372',
                         'Limite de Idade': '10373',
                         'Prazo de Validade': '10383',
                         'Prova de Títulos': '10375',
                         'Reserva de Vagas para Deficientes': '10371',
                         'Contratos Administrativos': '10421',
                         'Equilíbrio Financeiro': '10430',
                         'Execução Contratual': '10429',
                         'Pagamento Atrasado / Correção Monetária': '10422',
                         'Penalidades': '10428',
                         'Prorrogação': '10426',
                         'Rescisão': '10425',
                         'Suspensão': '10546',
                         'Termo Aditivo': '10427',
                         'Dívida Ativa não-tributária': '10394',
                         'Cessão de créditos não-tributários': '10402',
                         'Taxa de Ocupação / Laudêmio / Foro': '10401',
                         'Dívida Pública Mobiliária': '10182',
                         'Apólices da Dívida Pública': '10183',
                         'Títulos da Dívida Pública': '10184',
                         'Domínio Público': '10088',
                         'Ordenação da Cidade / Plano Diretor': '10109',
                         'Patrimônio Histórico / Tombamento': '10108',
                         'Privatização': '10131',
                         'Recursos Minerais': '10106',
                         'Empregado Público / Temporário': '10409',
                         'Admissão / Permanência / Despedida': '10411',
                         'Contrato Temporário de Mão de Obra L 8.745/1993': '10410',
                         'Garantias Constitucionais': '9986',
                         'Intervenção em Estado / Município': '9990',
                         'Intervenção do Estado na Propriedade': '10120',
                         'Direito de Preempção': '10133',
                         'Limitação Administrativa': '10130',
                         'Ocupação Temporária': '10129',
                         'Requisição de Bem Particular': '10135',
                         'Restituição de área': '10132',
                         'Servidão Administrativa': '10128',
                         'Vistoria': '10127',
                         'Licitações': '10385',
                         'Adjudicação': '10393',
                         'Convênio': '10392',
                         'Edital': '10388',
                         'Habilitação / Registro Cadastral / Julgamento / Homologação': '10387',
                         'Modalidade / Limite / Dispensa / Inexigibilidade': '10386',
                         'Recursos Administrativos': '10391',
                         'Revogação': '10389',
                         'Sanções Administrativas': '10390',
                         'Militar': '10324',
                         'Pensão': '10250',
                         'Concessão': '10252',
                         'Provisória': '10251',
                         'Restabelecimento': '10253',
                         'Regime': '10325',
                         'Adidos, Agregados e Adjuntos': '10331',
                         'Corpo Feminino': '10336',
                         'Estabilidade': '10222',
                         'Ingresso e Concurso': '10326',
                         'Promoção': '10334',
                         'Reintegração': '10226',
                         'Serviço Militar dos Profissionais da Saúde': '10335',
                         'Sistema Remuneratório e Benefícios': '10288',
                         'Agregação': '10351',
                         'Assistência Médico-Hospitalar': '10356',
                         'Férias': '10339',
                         'Gratificações e Adicionais': '10338',
                         'Indenizações Regulares': '10340',
                         'Licença Prêmio': '10357',
                         'Licenciamento': '10358',
                         'Reforma': '10349',
                         'Reserva Remunerada': '10352',
                         'Tempo de Serviço': '10276',
                         'Transferência ex-officio para reserva': '10353',
                         'Transferência para reserva': '10355',
                         'Responsabilidade da Administração': '9991',
                         'Indenização por Dano Ambiental': '9994',
                         'Indenização por Dano Material': '10502',
                         'Acidente de Trânsito': '9996',
                         'Erro Médico': '9995',
                         'Variação Cambial': '10505',
                         'Indenização por Dano Moral': '9992',
                         'Serviços': '10028',
                         'Concessão / Permissão / Autorização': '10073',
                         'Água e/ou Esgoto': '10085',
                         'Energia Elétrica': '10075',
                         'Fornecimento de Gás': '10074',
                         'Recolhimento e Tratamento de Lixo': '10086',
                         'Tabelionatos, Registros, Cartórios': '10083',
                         'Telefonia': '10080',
                         'Transporte Aquaviário': '10081',
                         'Transporte Terrestre': '10076',
                         'Defensoria Pública': '10087',
                         'Saúde': '10064',
                         'Fornecimento de Medicamentos': '11884',
                         'Tratamento Médico-Hospitalar': '11883',
                         'Unidade de terapia intensiva (UTI) ou unidade de cuidados intensivos (UCI)': '11885',
                         'Tratamento Médico-Hospitalar e/ou Fornecimento de Medicamentos': '10069',
                         'Servidor Público Civil': '10219',
                         'Aposentadoria': '10254',
                         'Compulsória': '10256',
                         'Invalidez Permanente': '10255',
                         'Voluntária': '10257',
                         'Jornada de Trabalho': '10287',
                         'Licenças / Afastamentos': '10258',
                         'Acompanhamento de Cônjuge ou Companheiro': '10273',
                         'Alistamento / Serviço Eleitoral': '10272',
                         'Amamentação': '10270',
                         'Atividade Política': '10267',
                         'Casamento': '10268',
                         'Dirigente Sindical': '10259',
                         'Doação de Sangue': '10271',
                         'Doença em Pessoa da Família': '10262',
                         'Exercício em Outro Município': '10274',
                         'Gestante / Adotante / Paternidade': '10264',
                         'Interesse Particular': '10265',
                         'Licença Capacitação (Aperfeiçoamento Profissional)': '10260',
                         'Licença por Acidente em Serviço': '10275',
                         'Luto': '10269',
                         'Serviço Militar': '10266',
                         'Tratamento da Própria Saúde': '10263',
                         'Programa de Desligamento Voluntário (PDV)': '10286',
                         'Regime Estatutário': '10220',
                         'Acumulação de Cargos': '10225',
                         'Anistia Administrativa': '10231',
                         'Direito de Greve': '10227',
                         'Disponibilidade / Aproveitamento': '10234',
                         'Enquadramento': '10223',
                         'Estágio Probatório': '10238',
                         'Exoneração': '10241',
                         'Lotação': '10235',
                         'Posse e Exercício': '10240',
                         'Promoção / Ascensão': '10236',
                         'Readaptação': '10237',
                         'Recondução': '10224',
                         'Redistribuição': '10233',
                         'Regime Previdenciário': '10230',
                         'Remoção': '10229',
                         'Reversão': '10232',
                         'Transferência': '10228',
                         'Abono de Permanência': '10662',
                         'Abono Pecuniário (Art. 78 Lei 8.112/1990)': '10294',
                         'Acumulação de Proventos': '10638',
                         'Adicional de Fronteira': '10293',
                         'Adicional de Horas Extras': '10303',
                         'Adicional de Periculosidade': '10292',
                         'Adicional de Produtividade': '10309',
                         'Adicional de Serviço Noturno': '10308',
                         'Assistência à Saúde': '10244',
                         'Assistência Pré-escolar': '10245',
                         'Auxílio-Alimentação': '6063',
                         'Auxílio-Funeral': '10248',
                         'Auxílio-Natalidade': '10246',
                         'Auxílio-Reclusão': '10247',
                         'Auxílio-transporte': '10306',
                         'Complementação de Benefício/Ferroviário': '10243',
                         'Data Base': '10300',
                         'Descontos Indevidos': '10296',
                         'Diárias e Outras Indenizações': '10298',
                         'Gratificação de Incentivo': '10290',
                         'Gratificação Incorporada / Quintos e Décimos / VPNI': '10295',
                         'Gratificação Natalina/13º salário': '10310',
                         'Gratificações da Lei 8.112/1990': '10289',
                         'Gratificações de Atividade': '10305',
                         'Gratificações Municipais Específicas': '10706',
                         'Inclusão de Dependente': '10323',
                         'Irredutibilidade de Vencimentos': '10311',
                         'Piso Salarial': '10312',
                         'Plano de Classificação de Cargos': '10299',
                         'Revisão Geral Anual (Mora do Executivo - inciso X, art. 37, CF 1988)': '10307',
                         'Salário-Família': '10249',
                         'Subsídios': '10497',
                         'Teto Salarial': '10297',
                         'Averbação / Contagem de Tempo Especial': '10277',
                         'Averbação / Contagem Recíproca': '10278',
                         'Sistema Nacional de Trânsito': '10417',
                         'CNH - Carteira Nacional de Habilitação': '10418',
                         'Liberação de Veículo Apreendido': '6028',
                         'Licenciamento de Veículo': '10420',
                         'DIREITO CIVIL': '899',
                         'Fatos Jurídicos': '7947',
                         'Ato / Negócio Jurídico': '4701',
                         'Defeito, nulidade ou anulação': '4703',
                         'Evicção ou Vicio Redibitório': '4706',
                         'Prescrição e Decadência': '5632',
                         'Obrigações': '7681',
                         'Adimplemento e Extinção': '7690',
                         'Compensação': '5994',
                         'Confusão': '7710',
                         'Dação em Pagamento': '7707',
                         'Desconto em folha de pagamento': '10592',
                         'Imputação do Pagamento': '7706',
                         'Novação': '7708',
                         'Pagamento': '7703',
                         'Pagamento com Sub-rogação': '7705',
                         'Pagamento em Consignação': '7704',
                         'Remissão das Dívidas': '7711',
                         'Atos Unilaterais': '7694',
                         'Enriquecimento sem Causa': '7715',
                         'Gestão de Negócios': '7713',
                         'Pagamento Indevido': '7714',
                         'Promessa de Recompensa': '7712',
                         'Espécies de Contratos': '9580',
                         'Locação de Imóvel': '9593',
                         'Benfeitorias': '9614',
                         'Cobrança de Aluguéis - Sem despejo': '11000',
                         'Despejo para Uso de Ascendentes e Descendentes': '9611',
                         'Despejo para Uso Próprio': '9610',
                         'Despejo por Denúncia Vazia': '9612',
                         'Direito de Preferência': '9615',
                         'Locação de Móvel': '9609',
                         'Sistema Financeiro da Habitação': '4839',
                         'Equivalência salarial': '4840',
                         'Quitação': '4841',
                         'Reajuste de Prestações': '4842',
                         'Revisão do Saldo Devedor': '4854',
                         'Seguro': '4847',
                         'Sustação/Alteração de Leilão': '4846',
                         'Transferência de Financiamento (contrato de gaveta)': '4843',
                         'Vícios de Construção': '10588',
                         'Inadimplemento': '7691',
                         'Arras ou Sinal': '7701',
                         'Cláusula Penal': '7700',
                         'Correção Monetária': '10685',
                         'Juros de Mora - Legais / Contratuais': '7699',
                         'Capitalização / Anatocismo': '10585',
                         'Limitação de Juros': '10586',
                         'Perdas e Danos': '7698',
                         'Rescisão / Resolução': '10582',
                         'Preferências e Privilégios Creditórios': '7696',
                         'Títulos de Crédito': '4949',
                         'Requisitos': '4957',
                         'Sustação de Protesto': '9575',
                         'Transmissão': '7688',
                         'Assunção de Dívida': '7689',
                         'Cessão de Crédito': '4718',
                         'DIREITO DO CONSUMIDOR': '1156',
                         'Contratos de Consumo': '7771',
                         'Bancários': '7752',
                         'Expurgos Inflacionários / Planos Econômicos': '10945',
                         'Fornecimento de Água': '7761',
                         'Fornecimento de Energia Elétrica': '7760',
                         'Planos de Saúde': '6233',
                         'Fornecimento de medicamentos': '12222',
                         'Reajuste contratual': '12225',
                         'Tratamento médico-hospitalar': '12223',
                         'Unidade de terapia intensiva (UTI) ou Unidade de cuidados intensivos (UCI)': '12224',
                         'DIREITO PENAL': '287',
                         'Contravenções Penais': '3692',
                         'Fabrico, comércio ou detenção de arma branca ou munição': '12343',
                         'Jogo de azar': '12350',
                         'Jogo do bicho': '12352',
                         'Loteria não autorizada': '12351',
                         'Omissão de cautela na guarda ou condução de animal': '12346',
                         'Omissão de comunicação de crime': '12355',
                         'Perturbação da tranquilidade': '12354',
                         'Perturbação do trabalho ou do sossego alheios': '12347',
                         'Porte de arma (branca)': '12344',
                         'Provocação de tumulto ou conduta inconveniente': '12340',
                         'Recusa de dados sobre a própria identificação ou qualificação': '12356',
                         'Servir bebidas alcóolicas a vulneráveis': '12353',
                         'Simulação de Qualidade de Funcionário': '12348',
                         'Uso ilegítimo de uniforme ou distintivo': '12349',
                         'Vias de fato': '12345',
                         'Crimes Previstos na Legislação Extravagante': '3603',
                         'Crimes contra o Meio Ambiente e o Patrimônio Genético': '3618',
                         'Crime contra a administração ambiental': '10986',
                         'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                         'Partes e Procuradores': '8842',
                         'Substituição Processual': '8867',
                         'Assistência Judiciária Gratuita': '8843',
                         'Capacidade Processual': '9493',
                         'Honorários Periciais': '9258',
                         'Intervenção de Terceiros': '8859',
                         'Litigância de Má-Fé': '8865',
                         'Litisconsórcio e Assistência': '8866',
                         'Procuração / Mandato': '8868',
                         'Representação em Juízo': '8873',
                         'Substituição da Parte': '9494',
                         'Sucumbência': '8874',
                         'Custas': '10658',
                         'Honorários Advocatícios': '10655',
                         'Honorários Advocatícios em Execução Contra a Fazenda Pública': '10656',
                         'Atos Processuais': '8893',
                         'Prazo': '8928',
                         'Citação': '10938',
                         'Intimação / Notificação': '10939',
                         'Valor da Causa': '8934',
                         'Formação, Suspensão e Extinção do Processo': '8938',
                         'Suspensão do Processo': '8939',
                         'Modificação ou Alteração do Pedido': '8941',
                         'Jurisdição e Competência': '8828',
                         'Imunidade de Jurisdição': '8838',
                         'Liquidação / Cumprimento / Execução': '9148',
                         'Ato Atentatório à Dignidade da Justiça': '9520',
                         'Benefício de Ordem': '9519',
                         'Causas Supervenientes à Sentença': '9517',
                         'Concurso de Credores': '9418',
                         'Constrição / Penhora / Avaliação / Indisponibilidade de Bens': '9163',
                         'Efeito Suspensivo / Impugnação / Embargos à Execução': '9518',
                         'Expropriação de Bens': '9180',
                         'Extinção da Execução': '9414',
                         'Fraude à Execução': '9450',
                         'Imunidade de Execução': '9453',
                         'Levantamento de Valor': '9160',
                         'Multa Cominatória / Astreintes': '10686',
                         'Multa de 10%': '9166',
                         'Nulidade / Inexigibilidade do Título': '9178',
                         'Obrigação de Entregar': '10670',
                         'Busca e Apreensão': '10677',
                         'Imissão na Posse': '10676',
                         'Obrigação de Fazer / Não Fazer': '10671',
                         'Remição': '9189',
                         'Sucessão': '9484',
                         'Valor da Execução / Cálculo / Atualização': '9149',
                         'Juros': '10684',
                         'Taxa SELIC': '10687',
                         'Medida Cautelar': '9192',
                         'Caução / Contracautela': '9532',
                         'Indenização do Prejuízo': '9524',
                         'Liminar': '9196',
                         'Ministério Público': '8875',
                         'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                         'Dos Auxiliares da Justiça': '8888',
                         'Processo e Procedimento': '8960',
                         'Antecipação de Tutela / Tutela Específica': '8961',
                         'Erro de Procedimento': '8986',
                         'Provas': '8990',
                         'Depoimento': '10940',
                         'Revelia': '9024',
                         'Vícios Formais da Sentença': '9026',
                         'Recurso': '9045',
                         'Cabimento': '9098',
                         'Conversão em Agravo Retido': '10999',
                         'Efeitos': '9047',
                         'Preparo / Deserção': '9050',
                         'Regularidade Formal': '10666',
                         'DIREITO TRIBUTÁRIO': '14',
                         'Contribuições': '6031',
                         'Contribuições de Melhoria': '6032',
                         'Contribuições Especiais': '6071',
                         'Contribuição de Iluminação Pública': '6083',
                         'Contribuições Previdenciárias': '6048',
                         '1/3 de férias': '6062',
                         'Aposentadoria/Retorno aoTrabalho': '6052',
                         'Cargo em Comissão': '6053',
                         'Contribuição de Autônomos, Empresários (Pró-labore) e Facultativos': '6070',
                         'Contribuição sobre a folha de salários': '6060',
                         'Contribuição sobre Nota Fiscal de Execução de Serviços': '6069',
                         'Custeio de Assistência Médica': '6064',
                         'Devolução de contribuições previdenciárias pagas além do teto': '6061',
                         'Gratificação Natalina/13º Salário': '6056',
                         'Hora Extra': '6065',
                         'Indenização Trabalhista': '6058',
                         'Mandato Eletivo/Lei 9.506/97': '6051',
                         'Massa Falida- Recolhimento': '6066',
                         'Nota Fiscal ou Fatura': '6067',
                         'Produção Agropecuária': '6057',
                         'Reembolso auxílio-creche': '6059',
                         'Salário-Maternidade': '6068',
                         'Servidores Ativos': '6049',
                         'Servidores Inativos': '6050',
                         'Tempo de Serviço Rural/Contribuições não Recolhidas': '6055',
                         'Tempo de Serviço Urbano/Contribuições não Recolhidas': '6054',
                         'Crédito Tributário': '5986',
                         'Alíquota': '6012',
                         'Alíquota Progressiva': '6014',
                         'Alíquota Zero': '6013',
                         'Índice da Alíquota': '6015',
                         'Anistia': '5996',
                         'Anulação de Débito Fiscal': '6004',
                         'Base de Cálculo': '6008',
                         'Cálculo de ICMS "por dentro"': '10559',
                         'Exclusão - ICMS': '10556',
                         'CND/Certidão Negativa de Débito': '5999',
                         'Expedição de Certidão Positiva de Débito com Efeito de Negativa': '6001',
                         'Expedição de CND': '6000',
                         'Creditamento': '6016',
                         'Crédito Prêmio': '6009',
                         'Crédito Presumido': '6010',
                         'Denúncia espontânea': '5997',
                         'Extinção do Crédito Tributário': '5990',
                         'Compensação com Apólices da Dívida Pública': '5991',
                         'Decadência': '5993',
                         'Constitucionalidade do artigo 45 da Lei 8212/91': '10551',
                         'Prescrição': '5992',
                         'Constitucionalidade do artigo 46 da Lei 8212/91': '10545',
                         'Constitucionalidade do artigo 4º da LC 118/05': '10544',
                         'Decretação de Ofício': '10548',
                         'Interrupção': '10547',
                         'Despacho de Citação': '10550',
                         'Arquivamento Administrativo - Crédito de Pequeno Valor': '10549',
                         'Fato Gerador/Incidência': '6011',
                         'Incentivos fiscais': '6003',
                         'Juros/Correção Monetária': '6005',
                         'Lançamento': '5998',
                         'Prazo de Recolhimento': '6006',
                         'Repetição de indébito': '6007',
                         'Suspensão da Exigibilidade': '5987',
                         'Carta de fiança': '5988',
                         'Depósito Judicial': '10543',
                         'Parcelamento': '5989',
                         'Impostos': '5916',
                         'ICMS/ Imposto sobre Circulação de Mercadorias': '5946',
                         'ICMS / Incidência Sobre o Ativo Fixo': '10531',
                         'ICMS/Importação': '5947',
                         'IPTU/ Imposto Predial e Territorial Urbano': '5952',
                         'IPVA - Imposto Sobre Propriedade de Veículos Automotores': '5953',
                         'ISS/ Imposto sobre Serviços': '5951',
                         'ITBI - Imposto de Transmissão Intervivos de Bens Móveis e Imóveis': '5954',
                         'ITCD - Imposto de Transmissão Causa Mortis': '5955',
                         'Limitações ao Poder de Tributar': '5913',
                         'Competência Tributária': '10540',
                         'Imunidade': '5914',
                         'Entidades Sem Fins Lucrativos': '10528',
                         'Imunidade Recíproca': '10530',
                         'Livros / Jornais / Periódicos': '10527',
                         'Partidos Políticos': '10529',
                         'Isenção': '5915',
                         'Obrigação Tributária': '5978',
                         'Capacidade Tributária': '10539',
                         'CNPJ/Cadastro Nacional de Pessoas Jurídicas': '5983',
                         'CPF/Cadastro de Pessoas Físicas': '5984',
                         'DIMOB/Declaração de Informações sobre Atividades Imobilíárias': '5982',
                         'Obrigação Acessória': '5985',
                         'Responsabilidade tributária': '5979',
                         'Responsabilidade Tributária do Sócio-Gerente / Diretor / Representante': '5980',
                         'Substituição Tributária': '5981',
                         'Procedimentos Fiscais': '6021',
                         'Autorização para Impressão de Documentos Fiscais - AIDF': '6027',
                         'Cadastro de Inadimplentes - CADIN': '6026',
                         'Levantamento de depósito': '6025',
                         'Liberação de mercadorias': '6024',
                         'Perdimento de Bens': '6029',
                         'Quebra de Sigilo Bancário': '10560',
                         'Sigilo Fiscal': '6022',
                         'Utilização de Dados Relativos à CPMF para Fins de Fiscalização': '6023',
                         'Processo Administrativo Fiscal': '6018',
                         'Arrolamento de Bens': '6020',
                         'Depósito Prévio ao Recurso Administrativo': '6019',
                         'Regimes Especiais de Tributação': '6089',
                         'PAES/Parcelamento Especial': '6091',
                         'REFIS/Programa de Recuperação Fiscal': '6090',
                         'SIMPLES': '6092',
                         'Super SIMPLES': '6093',
                         'Taxas': '5956',
                         'Estaduais': '5971',
                         'Municipais': '5972',
                         'Taxa de Coleta de Lixo': '10536',
                         'Taxa de Iluminação Pública': '10535',
                         'Taxa de Licenciamento de Estabelecimento': '10538',
                         'Taxa de Limpeza Pública': '10534',
                         'Taxa de Prevenção e Combate a Incêndio': '10537'}
