just_mil_est_1_grau = {'DIREITO ADMINISTRATIVO E OUTRAS MATÉRIAS DE DIREITO PÚBLICO': '9985',
                       'Atos Administrativos': '9997',
                       'Abuso de Poder': '10894',
                       'Improbidade Administrativa': '10011',
                       'Dano ao Erário': '10012',
                       'Enriquecimento ilícito': '10013',
                       'Violação aos Princípios Administrativos': '10014',
                       'Infração Administrativa': '10022',
                       'Multas e demais Sanções': '10023',
                       'Inquérito / Processo / Recurso Administrativo': '10009',
                       'Concurso Público / Edital': '10370',
                       'Anulação': '10382',
                       'Anulação e Correção de Provas / Questões': '10379',
                       'Classificação e/ou Preterição': '10381',
                       'Militar': '10324',
                       'Processo Administrativo Disciplinar / Sindicância': '10363',
                       'Advertência / Repreensão': '10364',
                       'Impedimento / Detenção / Prisão': '10365',
                       'Licenciamento / Exclusão': '10366',
                       'Suspensão': '4271',
                       'Regime': '10325',
                       'Adidos, Agregados e Adjuntos': '10331',
                       'Anistia Política': '10330',
                       'Corpo Feminino': '10336',
                       'Curso de Formação': '10327',
                       'Estabilidade': '10329',
                       'Ex-combatentes': '10333',
                       'Ingresso e Concurso': '10326',
                       'Promoção': '10334',
                       'Reintegração': '10328',
                       'Serviço Militar dos Profissionais da Saúde': '10335',
                       'Transferência de Unidade': '10910',
                       'DIREITO CIVIL': '899',
                       'Fatos Jurídicos': '7947',
                       'Ato / Negócio Jurídico': '4701',
                       'Defeito, nulidade ou anulação': '4703',
                       'Prescrição e Decadência': '5632',
                       'Pessoas naturais': '5754',
                       'DIREITO DO TRABALHO': '864',
                       'Responsabilidade Civil do Empregador': '2567',
                       'Indenização por Dano Material': '8808',
                       'Acidente de Trabalho': '8809',
                       'DIREITO PENAL': '287',
                       'Contravenções Penais': '3692',
                       'Omissão de comunicação de crime': '12355',
                       'Recusa de dados sobre a própria identificação ou qualificação': '12356',
                       'Simulação de Qualidade de Funcionário': '12348',
                       'Uso ilegítimo de uniforme ou distintivo': '12349',
                       'Crimes contra a vida': '3369',
                       'Feminicídio': '12091',
                       'Homicídio Agravado pela Prática de Extermínio de Seres Humanos': '12130',
                       'Fato Atípico': '10952',
                       'DIREITO PENAL MILITAR': '11068',
                       'Crime Culposo': '11069',
                       'Crime Tentado': '11071',
                       'Crimes contra a Administração da Justiça Militar': '11072',
                       'Auto-acusação falsa': '11358',
                       'Coação': '11359',
                       'Comunicação falsa de crime': '11360',
                       'Corrupção ativa de testemunha, perito ou intérprete': '11361',
                       'Denunciação caluniosa': '11362',
                       'Desacato': '11363',
                       'Desobediência a decisão judicial': '11364',
                       'Desobediência a decisão sobre perda ou suspensão de atividade ou direito': '11365',
                       'Exploração de prestígio': '11366',
                       'Falso testemunho ou falsa perícia': '11367',
                       'Favorecimento pessoal': '11368',
                       'Favorecimento real': '11369',
                       'Inutilização,sonegação ou descaminho de material probante': '11370',
                       'Publicidade opressiva': '11371',
                       'Recusa de função na Justiça Militar': '11372',
                       'Crimes contra a Administração Militar': '11073',
                       'Concussão, Excesso de Exação e Desvio': '11308',
                       'Concussão': '11355',
                       'Desvio': '11356',
                       'Excesso de exação': '11357',
                       'Corrupção': '11309',
                       'Corrupção ativa': '11352',
                       'Corrupção passiva': '11353',
                       'Participação ilícita': '11354',
                       'Crimes contra o dever funcional': '11310',
                       'Abandono de cargo': '11336',
                       'Abuso de confiança ou boa fé': '11337',
                       'Aplicação ilegal de verba ou dinheiro': '11338',
                       'Condescendência criminosa': '11339',
                       'Exercício funcional ilegal': '11340',
                       'Extravio, sonegação ou inutilização de livro ou documento': '11341',
                       'Inobservancia de lei, regulamento ou instrução': '11342',
                       'Obstáculo à hasta pública, concorrência ou tomada de preços': '11344',
                       'Patrocínio indébito': '11345',
                       'Prevaricação': '11346',
                       'Violação de sigilo de proposta de concorrência': '11347',
                       'Violação de sigilo funcional': '11348',
                       'Violação do dever funcional com o fim de lucro': '11349',
                       'Violação ou divulgação indevida de correspondência ou comunicação': '11350',
                       'Violência arbitrária': '11351',
                       'Desacato e da Desobediência': '11312',
                       'Desacato a assemelhado ou funcionário': '11326',
                       'Desacato a militar': '11327',
                       'Desacato a superior': '11328',
                       'Desobediência': '11329',
                       'Ingresso clandestino': '11330',
                       'Falsidade': '7945',
                       'Certidão ou atestado ideologicamente falso': '11318',
                       'Cheques sem fundos': '11319',
                       'Falsa identidade': '11320',
                       'Falsidade ideológica': '11321',
                       'Falsificação de documento': '11322',
                       'Supressão de documento': '11323',
                       'Uso de documento falso': '11324',
                       'Uso de documento pessoal alheio': '11325',
                       'Peculato': '11315',
                       'Peculato mediante aproveitamento ou erro de outrem': '11316',
                       'Peculato-furto': '11317',
                       'Crimes contra a Autoridade ou Disciplina Militar': '11074',
                       'Aliciação e incitamento': '11268',
                       'Aliciação para motim ou revolta': '11301',
                       'Apologia de fato criminoso ou do seu autor': '11302',
                       'Incitamento': '11303',
                       'Desrespeito a superior e a símbolo nacional ou farda': '11267',
                       'Despojamento desprezível': '11304',
                       'Desrespeito a comandante, oficial-general ou oficial de serviço': '11305',
                       'Desrespeito a símbolo nacional': '11306',
                       'Desrespeito a superior': '11307',
                       'Fuga, evasão, arrebatamento e amotinamento de presos': '11269',
                       'Amotinamento': '11297',
                       'Arrebatamento de preso ou internado': '11298',
                       'Evasão de preso ou internado': '11299',
                       'Fuga de preso ou internado': '11300',
                       'Insubordinação': '11270',
                       'Oposição a ordem de sentinela': '11293',
                       'Publicação ou crítica indevida': '11294',
                       'Recusa a obediência': '11295',
                       'Reunião ilícita': '11296',
                       'Motim e Revolta': '11271',
                       'Conspiração': '11288',
                       'Motim': '11289',
                       'Omissão de lealdade militar': '11290',
                       'Organização de grupo para prática de violência': '11291',
                       'Revolta': '11292',
                       'Resistência': '11272',
                       'Resistência mediante ameaça ou violência': '11287',
                       'Usurpação e excesso ou abuso de autoridade': '11273',
                       'Abuso de requisição militar': '11277',
                       'Assunção de comando sem ordem ou autorização': '11278',
                       'Conservação ilegal de comando': '11279',
                       'Ofensa aviltante a inferior': '11280',
                       'Operação militar sem ordem superior': '11281',
                       'Ordem arbitrária de invasão': '11282',
                       'Rigor excessivo': '11283',
                       'Uso indevido por militar de uniforme, distintivo ou insígnia': '11285',
                       'Violência contra inferior': '11286',
                       'Violência contra superior ou militar de serviço': '11274',
                       'Violência contra militar de serviço': '11275',
                       'Violência contra superior': '11276',
                       'Crimes contra a Pessoa': '11075',
                       'Crimes contra a Honra': '11223',
                       'Calúnia': '11262',
                       'Difamação': '11263',
                       'Injúria': '11264',
                       'Injuria real': '11265',
                       'Crimes contra a Liberdade': '11224',
                       'Ameaça': '11253',
                       'Constragimento ilegal': '11254',
                       'Desafio para duelo': '11255',
                       'Divulgação de segredo': '11256',
                       'Sequestro ou cárcere privado': '11257',
                       'Violação de correspondência': '11258',
                       'Violação de domicílio': '11259',
                       'Violação de recato': '11260',
                       'Violação de segredo profissional': '11261',
                       'Crimes Sexuais': '11225',
                       'Atentado violento ao pudor': '11249',
                       'Corrupção de menores': '11250',
                       'Estupro': '11251',
                       'Pederastia ou outro ato de libidinagem': '11252',
                       'Genocídio': '11248',
                       'Homicídio': '11243',
                       'Homicidio qualificado': '11244',
                       'Homicido privilegiado': '11245',
                       'Provocação direta ou auxílio a suicídio': '11246',
                       'Provocação indireta ao suicídio': '11247',
                       'Lesão Corporal e Rixa': '11228',
                       'Lesão grave': '11237',
                       'Lesão leve': '11238',
                       'Lesão levíssima': '11239',
                       'Lesão privilegiada': '11240',
                       'Lesão seguida de morte': '11241',
                       'Participação em rixa': '11242',
                       'Periclitação da Vida ou da Saúde': '11229',
                       'Abandono de pessoa': '11233',
                       'Abandono de pessoa seguida de morte ou lesão grave': '11234',
                       'Maus tratos': '11235',
                       'Maus tratos seguido de morte ou lesão grave': '11236',
                       'Ultraje Público ao Pudor': '11230',
                       'Ato obsceno': '11231',
                       'Escrito ou objeto obsceno': '11232',
                       'Crimes contra Incolumidade Pública': '11077',
                       'Contra a Saúde': '11178',
                       'Corrupção ou poluição de água potável': '11200',
                       'Envenenamento com perigo extensivo': '11201',
                       'Epidemia': '11202',
                       'Omissão de notificação de doença': '11205',
                       'Receita Ilegal': '11206',
                       'Tráfico, posse ou uso de entorpecente ou substância de efeito similar': '11207',
                       'Crimes contra os Meios de Transporte e de Comunicação': '11179',
                       'Arremesso de projétil': '11194',
                       'Atentado contra serviço de utilidade militar': '11195',
                       'Atentado contra transporte': '11196',
                       'Atentado contra viatura ou outro meio de transporte': '11197',
                       'Interrupção ou perturbação de serviço ou meio de comunicação': '11198',
                       'Perigo de desastre ferroviário': '11199',
                       'Crimes de Perigo Comum': '11180',
                       'Abuso de radiação': '11181',
                       'Desabamento ou desmoronamento': '11182',
                       'Difusão de epizootia ou praga vegetal': '11183',
                       'Embriaguez ao volante': '11184',
                       'Emprego de gás tóxico ou asfixiante': '11185',
                       'Explosão': '11186',
                       'Fuga após acidente de trânsito': '11188',
                       'Incêndio': '11189',
                       'Inundação': '11190',
                       'Perigo de inundação': '11191',
                       'Perigo resultante de violação de regra de trânsito': '11192',
                       'Subtração, ocultação ou inutilização de material de socorro': '11193',
                       'Crimes contra o Patrimônio': '11078',
                       'Apropriação Indébita': '11144',
                       'Apropriação de coisa achada': '11175',
                       'Apropriação de coisa havida acidentalmente': '11176',
                       'Apropriação indébita': '11177',
                       'Dano': '11145',
                       'Dano atenuado': '11168',
                       'Dano em aparelhos e instalações': '11169',
                       'Dano material ou aparelhamento de guerra': '11171',
                       'Dano qualificado': '11172',
                       'Dano simples': '11173',
                       'Desaparecimento,consunção ou extravio': '11174',
                       'Estelionato e outras fraudes': '11146',
                       'Abuso de pessoa': '11166',
                       'Estelionato': '11167',
                       'Furto': '11163',
                       'Furto de uso': '11164',
                       'Furto qualificado': '11165',
                       'Receptação': '11162',
                       'Roubo e Extorsão': '11149',
                       'Chantagem': '11155',
                       'Extorsão': '11156',
                       'Extorsão indireta': '11157',
                       'Extorsão mediante sequestro': '11158',
                       'Latrocínio': '11159',
                       'Roubo': '11160',
                       'Roubo qualificado': '11161',
                       'Usura': '11150',
                       'Usura pecuniária': '11154',
                       'Usurpação': '11151',
                       'Alteração de Limites': '11152',
                       'Aposição, supressão ou alteração de marca': '11153',
                       'Crimes contra o Serviço Militar e o Dever Militar': '11079',
                       'Abandono de posto e de outros crimes em serviço': '11116',
                       'Abandono de posto': '11135',
                       'Descumprimento de missão': '11136',
                       'Dormir em serviço': '11137',
                       'Embriaguez em serviço': '11138',
                       'Omissão de eficiência da força': '11139',
                       'Omissão de providências para evitar danos': '11140',
                       'Omissão de providências para salvar comandados': '11141',
                       'Omissão de socorro': '11142',
                       'Retenção indevida': '11143',
                       'Deserção': '11127',
                       'Concerto para deserção': '11126',
                       'Deserção - casos assimilados': '11128',
                       'Deserção especial': '11129',
                       'Deserção por evasão ou fuga': '11130',
                       'Deserção privilegiada': '11131',
                       'Deserção qualificada': '11132',
                       'Favorecimento a desertor': '11133',
                       'Omissão de Oficial': '11134',
                       'Exercício de comércio': '11118',
                       'Exercício de comércio por oficial': '11125',
                       'Parte Geral': '11080',
                       'Aplicação da Pena': '11081',
                       'Conversão da Pena': '11114',
                       'Substituição da Pena': '11115',
                       'Efeitos da Condenação': '11082',
                       'Perda em favor da Fazenda Pública': '11112',
                       'Reparação do Dano': '11113',
                       'Excludentes': '11083',
                       'Estado de Necessidade': '11106',
                       'Estrito Cumprimento do Dever Legal': '11108',
                       'Legítima Defesa': '11111',
                       'Extinção da punibilidade': '11084',
                       'Anistia': '11100',
                       'Indulto': '11101',
                       'Morte do Agente': '11102',
                       'Prescrição': '11103',
                       'Reabilitação': '11104',
                       'Ressarcimento do Dano': '11105',
                       'Livramento Condicional': '11085',
                       'Penas Acessórias': '11086',
                       'Inabilitação para o exercício de Função Pública': '11092',
                       'Suspensão do pátrio poder, tutela ou curatela': '11098',
                       'Suspensão dos direitos políticos': '11099',
                       'Suspensão Condicional da Pena': '11087',
                       'Tipicidade': '11088',
                       'Abolitio criminis': '11089',
                       'Princípio da Insignificância': '11090',
                       'DIREITO PROCESSUAL CIVIL E DO TRABALHO': '8826',
                       'Partes e Procuradores': '8842',
                       'Substituição Processual': '8867',
                       'Assistência Judiciária Gratuita': '8843',
                       'Capacidade Processual': '9493',
                       'Honorários Periciais': '9258',
                       'Intervenção de Terceiros': '8859',
                       'Litigância de Má-Fé': '8865',
                       'Litisconsórcio e Assistência': '8866',
                       'Procuração / Mandato': '8868',
                       'Representação em Juízo': '8873',
                       'Substituição da Parte': '9494',
                       'Sucumbência': '8874',
                       'Custas': '10658',
                       'Honorários Advocatícios': '10655',
                       'Honorários Advocatícios em Execução Contra a Fazenda Pública': '10656',
                       'Atos Processuais': '8893',
                       'Prazo': '8928',
                       'Citação': '11783',
                       'Intimação / Notificação': '10939',
                       'Nulidade': '8919',
                       'Valor da Causa': '8934',
                       'Formação, Suspensão e Extinção do Processo': '8938',
                       'Extinção do Processo Sem Resolução de Mérito': '8942',
                       'Modificação ou Alteração do Pedido': '8941',
                       'Jurisdição e Competência': '8828',
                       'Competência': '8829',
                       'Liquidação / Cumprimento / Execução': '9148',
                       'Ato Atentatório à Dignidade da Justiça': '9520',
                       'Causas Supervenientes à Sentença': '9517',
                       'Concurso de Credores': '9418',
                       'Constrição / Penhora / Avaliação / Indisponibilidade de Bens': '9163',
                       'Efeito Suspensivo / Impugnação / Embargos à Execução': '9518',
                       'Execução Provisória': '10880',
                       'Expropriação de Bens': '9180',
                       'Extinção da Execução': '9414',
                       'Fraude à Execução': '9450',
                       'Levantamento de Valor': '9160',
                       'Multa Cominatória / Astreintes': '10686',
                       'Multa de 10%': '9166',
                       'Nulidade / Inexigibilidade do Título': '9178',
                       'Obrigação de Fazer / Não Fazer': '10671',
                       'Remição': '9189',
                       'Requisição de Pequeno Valor - RPV': '10673',
                       'Sucessão': '9484',
                       'Valor da Execução / Cálculo / Atualização': '9149',
                       'Correção Monetária': '10685',
                       'Juros': '10684',
                       'Medida Cautelar': '9192',
                       'Caução / Contracautela': '9532',
                       'Indenização do Prejuízo': '9524',
                       'Liminar': '9196',
                       'Ministério Público': '8875',
                       'Objetos de cartas precatórias/de ordem': '11781',
                       'Atos executórios': '11786',
                       'Diligências': '11785',
                       'Intimação': '11782',
                       'Oitiva': '11784',
                       'Órgãos Judiciários e Auxiliares da Justiça': '8883',
                       'Do Juiz': '8884',
                       'Dos Auxiliares da Justiça': '8888',
                       'Processo e Procedimento': '8960',
                       'Antecipação de Tutela / Tutela Específica': '8961',
                       'Erro de Procedimento': '8986',
                       'Provas': '8990',
                       'Depoimento': '10940',
                       'Revelia': '9024',
                       'Vícios Formais da Sentença': '9026',
                       'Recurso': '9045',
                       'Cabimento': '9098',
                       'Efeitos': '9047',
                       'Preparo / Deserção': '9050',
                       'Tempestividade': '9060',
                       'Revisão de Tutela Antecipada Antecedente': '12152',
                       'DIREITO PROCESSUAL PENAL': '1209',
                       'Ação Penal': '4263',
                       'Excesso de prazo para instrução / julgamento': '10902',
                       'Questão Prejudicial': '10691',
                       'Trancamento': '10610',
                       'Execução Penal': '11052',
                       'Pena Privativa de Liberdade': '7791',
                       'Transferência de Preso': '10907',
                       'Habeas Corpus - Cabimento': '10891',
                       'Investigação Penal': '10604',
                       'Cerceamento de Defesa': '10606',
                       'Quebra do Sigilo Bancário': '10607',
                       'Quebra do Sigilo Fiscal': '10608',
                       'Quebra do Sigilo Telefônico': '10609',
                       'Liberdade Provisória': '7928',
                       'Medidas Assecuratórias': '10912',
                       'Busca e Apreensão de Bens': '10914',
                       'Indisponibilidade / Seqüestro de Bens': '10913',
                       'Prisão Domiciliar / Especial': '10904',
                       'Prisão em flagrante': '7929',
                       'Prisão Preventiva': '4355',
                       'DIREITO PROCESSUAL PENAL MILITAR': '11049',
                       'Correição Parcial': '11051',
                       'Requerimento da Parte': '11065',
                       'Penas restritivas de direitos': '11057',
                       'Cassação de licença para direção de veículo motorizado': '11058',
                       'Confisco': '11059',
                       'Exílio local': '11060',
                       'Interdição de estabecimento ou associação': '11061',
                       'Proibição de frequentar determinados locais': '11062',
                       'Suspensão do exercício do posto, graduação, cargo ou função': '11063',
                       'Menagem': '11054'}
